USE SIGSALUD	
SELECT * FROM ITEM WHERE     (GRUPO_RECAUDACION = '04') AND (ACTIVO = '5')

SELECT  * FROM dbo.ITEM WHERE NOMBRE LIKE '%LIPASA%'

SELECT  * FROM dbo.ITEM WHERE NOMBRE LIKE '%PC%'




SELECT     *
FROM  dbo.ITEM
WHERE NOMBRE LIKE '%PROTEINA%' AND SUBSTRING(ITEM,1,1) = '5' 


SELECT     *
FROM  dbo.ITEM
WHERE ACTIVO  = '5' 

select * from ITEM where ITEM = '50912'

/* LIPASA */
UPDATE ITEM SET ACTIVO = '5' WHERE ITEM = '50848'

/* LAB/ TROPONINA I */
UPDATE ITEM SET ACTIVO = '5' WHERE ITEM = '50912'

/* DESHIDROGENASA  */
UPDATE ITEM SET ACTIVO = '5' WHERE ITEM = '50847'

/* PROTEINA CUANTITATIVA */
UPDATE ITEM SET ACTIVO = '5' WHERE ITEM = '50853'


/* INSERT INTO [SIGSALUD].[dbo].[ITEM]([ITEM],[NOMBRE],[ABREVIATURA],[GRUPO_RECAUDACION],[CLASIFICADOR],[GRUPO_LIQUIDACION],[GRUPO_TARIFARIO],[PRESENTACION],[FAMILIA],[CLASE]
          ,[GENERICO],[LABORATORIO],[FRACCION],[INTERFASE1],[VARIABLE],[MODULO],[ACTIVO],[SYSINSERT],[SYSUPDATE],[SYSDELETE],[INTERFASE2],[PETITORIO],[STOCK],[STOCK_MINIMO]
          ,[ITEM_EXCLUSION],[ESTADO_A_CUENTA],[STOCK_CRITICO],[DISPONIBILIDAD],[APLICA_DSCTO],[PRESENTA],[CONCENTRA],[NOMBRECORTO],[CODCPT])
          
    VALUES ('52741', 'CALCIO SÉRICO', NUll, '01', '1.3.3.4.3', '01', NULL, '0', '0', '0', '0', '0', '1', '', 'N', 'CAJA', '5', '', '', '', '', '0', '0', '0', '', '4', '0', NULL, 'S', NULL, NULL, NULL, '82310')
   */ 
