use SIGSALUD

/* DECLARE @lcodigo varchar(10) = 'X40'
select * from CIEX  where codcat = 'X40'
select * from CIEXHIS where CODIGO like 'X40%'
select * from CIEX  where CIEX = 'X40'
select * from CIEXHIS  where codcat = 'X40' order by CODIGO asc
select * from CIEXHIS  where codIGO = 'X40' order by CIEX asc
select * from SEEMCIE10  where codigo like 'X50%' order by codigo asc */


ALTER TABLE ciex ALTER COLUMN nombre varchar(200)
ALTER TABLE ciexhis ALTER COLUMN nombre varchar(180)
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICIÓN A ANALGÉSICOS NO NARCÓTICOS, ANTIPIRÉTICOS Y ANTIRREUMÁTICOS' WHERE CIEX = 'X40'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, VIVIENDA' WHERE CIEX = 'X40.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X40.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, ESCUELAS, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X40.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X40.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, CALLES Y CARRETERAS' WHERE CIEX = 'X40.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X40.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X40.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, GRANJA' WHERE CIEX = 'X40.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X40.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X40.9'

/** CIEHIS ***/
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICIÓN A ANALGÉSICOS NO NARCÓTICOS, ANTIPIRÉTICOS Y ANTIRREUMÁTICOS' WHERE codigo = 'X40'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, VIVIENDA' WHERE codigo = 'X400'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, INSTITUCION RESIDENCIAL' WHERE codigo = 'X401'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, ESCUELAS, OTRAS INSTITUCIONES' WHERE codigo = 'X402'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, AREAS DE DEPORTE Y ATLETISMO' WHERE codigo = 'X403'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, CALLES Y CARRETERAS' WHERE codigo = 'X404'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, COMERCIO Y AREA DE SERVICIOS' WHERE codigo = 'X405'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE codigo = 'X406'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, GRANJA' WHERE codigo = 'X407'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, OTRO LUGAR ESPECIFICADO' WHERE codigo = 'X408'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS, LUGAR NO ESPECIFICADO' WHERE codigo = 'X409'



/*******************/
/* para X46 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES' WHERE CIEX = 'X46'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, VIVIENDA' WHERE CIEX = 'X46.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X46.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, ESCUELAS, OTRAS INSTITUCIONES Y AREAS ADMINISTRATIVAS  PUBLICAS' WHERE CIEX = 'X46.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X46.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, CALLES Y CARRETERAS' WHERE CIEX = 'X46.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X46.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X46.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, GRANJA' WHERE CIEX = 'X46.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X46.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X46.9'

/** CIEHIS ***/
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES' WHERE codigo = 'X46'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, VIVIENDA' WHERE codigo = 'X460'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, INSTITUCION RESIDENCIAL' WHERE codigo = 'X461'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, ESCUELAS, OTRAS INSTITUCIONES Y AREAS ' WHERE codigo = 'X462'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, AREAS DE DEPORTE Y ATLETISMO' WHERE codigo = 'X463'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, CALLES Y CARRETERAS' WHERE codigo = 'X464'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, COMERCIO Y AREA DE SERVICIOS' WHERE codigo = 'X465'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE codigo = 'X466'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, GRANJA' WHERE codigo = 'X467'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, OTRO LUGAR ESPECIFICADO' WHERE codigo = 'X468'
update CIEXHIS  set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DISOLVENTES ORGANICOS E HIDROCARBUROS HALOGENADOS Y SUS VAPORES, LUGAR NO ESPECIFICADO' WHERE codigo = 'X469'



/* para X41 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE' WHERE CIEX = 'X41'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, VIVIENDA' WHERE CIEX = 'X41.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X41.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X41.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X41.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, CALLES Y CARRETERAS' WHERE CIEX = 'X41.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X41.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X41.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, GRANJA' WHERE CIEX = 'X41.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X41.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X41.9'

/* ciexhis 41 */
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE' WHERE codigo = 'X41'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, VIVIENDA' WHERE codigo = 'X410'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, INSTITUCION ' WHERE codigo = 'X411'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, OTRAS INSTITUCIONES' WHERE codigo = 'X412'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, AREAS DE DEPORTE' WHERE codigo = 'X413'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, CALLES Y CARRETERAS' WHERE codigo = 'X414'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, COMERCIO Y AREA' WHERE codigo = 'X415'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, AREA INDUSTRIAL' WHERE codigo = 'X416'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, GRANJA' WHERE codigo = 'X417'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, OTRO LUGAR' WHERE codigo = 'X418'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARKINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE, LUGAR NO ESPECIFICADO' WHERE codigo = 'X419'


/* para X42 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE' WHERE CIEX = 'X42'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, VIVIENDA' WHERE CIEX = 'X42.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X42.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X42.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X42.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, CALLES Y CARRETERAS' WHERE CIEX = 'X42.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X42.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X42.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, GRANJA' WHERE CIEX = 'X42.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X42.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X42.9'


/* ciexhis 42 */
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE' WHERE codigo = 'X42'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, VIVIENDA' WHERE codigo = 'X420'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, INSTITUCION RESIDENCIAL' WHERE codigo = 'X421'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, OTRAS INSTITUCIONES Y AREAS' WHERE codigo = 'X422'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, AREAS DE DEPORTE Y ATLETISMO' WHERE codigo = 'X423'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, CALLES Y CARRETERAS' WHERE codigo = 'X424'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, COMERCIO Y AREA DE SERVICIOS' WHERE codigo = 'X425'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE codigo = 'X426'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, GRANJA' WHERE codigo = 'X427'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, OTRO LUGAR ESPECIFICADO' WHERE codigo = 'X428'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A NARCOTICOS Y PSICODISLEPTICOS [ALUCINOGENOS], NO CLASIFICADOS EN OTRA PARTE, LUGAR NO ESPECIFICADO' WHERE codigo = 'X429'




/* para X43 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO' WHERE CIEX = 'X43'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, VIVIENDA' WHERE CIEX = 'X43.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X43.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X43.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X43.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, CALLES Y CARRETERAS' WHERE CIEX = 'X43.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X43.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X43.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, GRANJA' WHERE CIEX = 'X43.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X43.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X43.9'


/* ciexhis X43 */
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO' WHERE codigo = 'X43'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, VIVIENDA' WHERE codigo = 'X430'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, INSTITUCION RESIDENCIAL' WHERE codigo = 'X431'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, OTRAS INSTITUCIONES Y AREAS' WHERE codigo = 'X432'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, AREAS DE DEPORTE Y ATLETISMO' WHERE codigo = 'X433'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, CALLES Y CARRETERAS' WHERE codigo = 'X434'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, COMERCIO Y AREA DE SERVICIOS' WHERE codigo = 'X435'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE codigo = 'X436'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, GRANJA' WHERE codigo = 'X437'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, OTRO LUGAR ESPECIFICADO' WHERE codigo = 'X438'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS QUE ACTUAN SOBRE EL SISTEMA NERVIOSO AUTONOMO, LUGAR NO ESPECIFICADO' WHERE codigo = 'X439'



/* para X44 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS' WHERE CIEX = 'X44'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, VIVIENDA' WHERE CIEX = 'X44.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X44.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X44.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X44.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, CALLES Y CARRETERAS' WHERE CIEX = 'X44.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X44.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X44.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, GRANJA' WHERE CIEX = 'X44.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X44.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X44.9'


/* para ciexhis X44 */
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS' WHERE CODIGO = 'X44'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, VIVIENDA' WHERE CODIGO = 'X440'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, INSTITUCION RESIDENCIAL' WHERE CODIGO = 'X441'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, OTRAS INSTITUCIONES Y AREAS' WHERE CODIGO = 'X442'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, AREAS DE DEPORTE Y ATLETISMO' WHERE CODIGO = 'X443'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, CALLES Y CARRETERAS' WHERE CODIGO = 'X444'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, COMERCIO Y AREA DE SERVICIOS' WHERE CODIGO = 'X445'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CODIGO = 'X446'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, GRANJA' WHERE CODIGO = 'X447'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, OTRO LUGAR ESPECIFICADO' WHERE CODIGO = 'X448'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS, Y LOS NO ESPECIFICADOS, LUGAR NO ESPECIFICADO' WHERE CODIGO = 'X449'


/* para X49 */
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS' WHERE CIEX = 'X49'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, VIVIENDA' WHERE CIEX = 'X49.0'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, INSTITUCION RESIDENCIAL' WHERE CIEX = 'X49.1'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, OTRAS INSTITUCIONES Y AREAS' WHERE CIEX = 'X49.2'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, AREAS DE DEPORTE Y ATLETISMO' WHERE CIEX = 'X49.3'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, CALLES Y CARRETERAS' WHERE CIEX = 'X49.4'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, COMERCIO Y AREA DE SERVICIOS' WHERE CIEX = 'X49.5'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CIEX = 'X49.6'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, GRANJA' WHERE CIEX = 'X49.7'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, OTRO LUGAR ESPECIFICADO' WHERE CIEX = 'X49.8'
update CIEX set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, LUGAR NO ESPECIFICADO' WHERE CIEX = 'X49.9'

/* para CIEXHIS - X49 */
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS' WHERE CODIGO = 'X49'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, VIVIENDA' WHERE CODIGO = 'X490'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, INSTITUCION RESIDENCIAL' WHERE CODIGO = 'X491'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, OTRAS INSTITUCIONES Y AREAS' WHERE CODIGO = 'X492'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, AREAS DE DEPORTE Y ATLETISMO' WHERE CODIGO = 'X493'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, CALLES Y CARRETERAS' WHERE CODIGO = 'X494'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, COMERCIO Y AREA DE SERVICIOS' WHERE CODIGO = 'X495'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, AREA INDUSTRIAL Y DE LA CONSTRUCCION' WHERE CODIGO = 'X496'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, GRANJA' WHERE CODIGO = 'X497'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, OTRO LUGAR ESPECIFICADO' WHERE CODIGO = 'X498'
update CIEXHIS set NOMBRE = 'ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS, Y LOS NO ESPECIFICADOS, LUGAR NO ESPECIFICADO' WHERE CODIGO = 'X499'

