
use SIGSALUD
select * from MEDICO where NOMBRE like '%CALDERON%'

SELECT * FROM MEDICO WHERE MEDICO IN ('CES', 'CMT')
SELECT * FROM MEDICO WHERE MEDICO IN ('CES', 'CMT', 'JRR', 'CLO')

/* UPDATE MEDICO SET TIENE_FIRMA = '1' WHERE MEDICO IN ('CES', 'CMT', 'JRR', 'CLO') */