USE SIGSALUD	
UPDATE MEDICO SET TIENE_FIRMA = '1'  WHERE MEDICO IN ('FZP','LAX', 'MAT', 'RPE', 'SAA', 'REC', 'MQR', 'QBC', 'MFI', 'MLR', 'HCD', 'OBR', 'MCS', 'CCP','CMV', 'CAM', 'BVK', 'SAY',
       'GGJ','DPJ', 'CBM', 'CGJ', 'CCV', 'CPE', 'REC')
UPDATE MEDICO SET DNI = '09761656' WHERE MEDICO = 'CAM'
UPDATE MEDICO SET NOMBRE = 'CASAVERDE CASTILLO ABEL ALBERTO' WHERE MEDICO = '034'
DELETE FROM MEDICO WHERE MEDICO = 'MAC'
UPDATE EMERGENCIA SET MEDICO = 'CAM' WHERE MEDICO = 'MAC'
UPDATE EMERGENCIA SET MEDICO1 = 'CAM' WHERE MEDICO1 = 'MAC'
