 ALTER TABLE [SIGSALUD].[dbo].[DESTINO] ADD ORDEN INT
  
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 9 
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 1 WHERE DESTINO = '10'
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 2 WHERE DESTINO = '12'
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 3 WHERE DESTINO = '07'
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 4 WHERE DESTINO = '09'
  UPDATE [SIGSALUD].[dbo].[DESTINO] SET ORDEN = 5 WHERE DESTINO = '01' 