/* DADO EL APELLIDO DE UN MEDICO, NECESITAMOS CONOCER SU USUARIO, EN QUE SISTEMA SE ENCUENTRA REGISTRADO  */
USE SIGSALUD
GO

DECLARE @lnombre varchar(100) = 'PARIONA LLAHUILLA'

SELECT * FROM MEDICO WHERE NOMBRE LIKE '%' + @lnombre + '%'
SELECT * FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombre + '%'
SELECT * FROM USUARIO WHERE NOMBRE LIKE '%' + @lnombre + '%'
SELECT * FROM CONSULTORIO  WHERE CONSULTORIO = (SELECT CONSULTORIO FROM MEDICO WHERE NOMBRE LIKE '%' + @lnombre + '%')