use SIGSALUD
DECLARE @lcfecha VARCHAR(10) = '2016-03-15'
SELECT DNI, CLAVE, NOMBRES, CARGO, FECHA_EXPIRACION FROM USUARIO_WEB 
    WHERE DNI IN (SELECT DNI FROM MEDICO WHERE MEDICO IN  (select TOP 3 MEDICO1 from EMERGENCIA order by fecha desc))
