/* Para Enfermera */
USE SIGSALUD
GO
DECLARE @lnombres varchar(100) = 'CHUYES'
declare @ldni varchar(8) = (select dni from USUARIO_WEB where NOMBRES LIKE '%' + @lnombres + '%')

/* 1 */ SELECT * FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%' ORDER BY NOMBRES ASC
/* 2 */ SELECT * FROM ACCESO_MODULO WHERE DNI = @ldni
/* 3 */ SELECT * FROM ACCESO_MENU WHERE DNI = @ldni
/* 4 */ SELECT * FROM ACCESO_SUBMENU WHERE DNI = @ldni
/* 5 */ SELECT * FROM ACCESO_BOTONES WHERE DNI = @ldni


/* SELECCION LAS PLANTILLAS */
/* SELECT * FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%')) */ 
/* SELECT * FROM PLANTILLA_MENU WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%'))) */
/* SELECT * FROM PLANTILLA_SUBMENU WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%'))) */
/* SELECT *  FROM PLANTILLA_BOTONES WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%'))) order by ID_PL_BOTON asc */ 

/* primer paso */
/* DELETE FROM ACCESO_MODULO WHERE ID_AM = '1041838415000002' */
/* delete from ACCESO_MENU WHERE ID_AM = '1014838415000002' */
/* delete from ACCESO_MENU where id_menu = '4065021315000014' */
/* DELETE FROM ACCESO_MENU WHERE ID_MENU = '0011937615000014' */

/* IMPORTANTE EJECUTAR EN EL SERVER */

/* DELETE FROM ACCESO_MENU WHERE ID_MENU LIKE '%000014%' */