USE SIGSALUD
/* EL CONTENIDO DE LA HISTORIA DE ROCHA DEBE PASAR A RUPAY */


/* HISTORIA DE ROCHA */
SELECT * FROM EMERGENCIA WHERE EMERGENCIA_ID = '16044827'


/* HISTORIA DE RUPAY */
SELECT * FROM EMERGENCIA WHERE EMERGENCIA_ID = '16044828'
 