USE SIGSALUD

use SIGSALUD
SELECT RELATO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032242'
UPDATE EMERGENCIA SET RELATO = 'PACIENTE REFIERE QUE SUFRIO ACCIDENTE DE TRANSITO ELLA SE ENCONTRABA EN MOTOTAXI Y FUE IMPACTADO POR AUTO GOLPEANDOSE LA CABEZA Y LA REGION DE LA CARA, CON SANGRADO DE LA PIRAMIDE NASAL NO PERDIDA DE CONOCIMIENTO NO VOMITOS. ASI MISMO DOLOR EN LA RODILLA DERECHA' WHERE EMERGENCIA_ID = '16032242'



use SIGSALUD
SELECT EXAMEN_FISICO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032242'
UPDATE EMERGENCIA SET EXAMEN_FISICO  = 'PIEL T/E/H LLENADO CAPILAR MENOR A DOS SEGUNDO. GLASGOW 15 LUCIDA ORIENTADA EN LA CARA: PRESENCIA DE SOLUCION DE CONTINUIDAD DE +/- 1 CM EN LA PIRAMIDE NASAL. RODILLA DERECHA DISCRETO EDEMA Y LIMITACION FUNCIONAL POR DOLOR SISTEMA NERVIOSO CENTRAL: LOTEP NO FOCALIZACION NO SIGNOS NEUROLOGICOS' WHERE EMERGENCIA_ID = '16032242'


USE SIGSALUD
update emergencia set CIEX5 = 'S02.2', TIPO_CIEX5 = 'P', CIEX6 = 'S82.0', TIPO_CIEX6 = 'P'  WHERE EMERGENCIA_ID = '16032242'


USE SIGSALUD
SELECT TRATAMIENTO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032242'
UPDATE EMERGENCIA SET TRATAMIENTO = 'CURACIÓN SE LE COLOCA STERIP STRIP, ANLAGESICOS.  RX DE CRANEO: NO LESIONES. RADIOGRAFIA DE HUESOS PROPIO DE LA NARIZ Y RODILLA: NO SIGNOS DE FRACTURA' WHERE EMERGENCIA_ID = '16032242'

/* PARA DX DE SALIDA */
update emergencia set CIEX2 = 'S80.0', TIPO_CIEX5 = 'D'  WHERE EMERGENCIA_ID = '16032242'


USE SIGSALUD
update emergencia set CIEX5 = 'S40.0', TIPO_CIEX5 = 'D', TIPO_CIEX4 = 'P', CIEX2 = 'S40.0', TIPO_CIEX2 = 'D' WHERE EMERGENCIA_ID = '15023226'


SELECT RELATO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16030774'
UPDATE EMERGENCIA SET RELATO = 'REFIERE CAIDA MAS CORTE' WHERE EMERGENCIA_ID = '16030774'




SELECT MEDICO, MEDICO1, QUIEN_ATIENDE FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032218'
UPDATE EMERGENCIA SET MEDICO1 = QUIEN_ATIENDE FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032218'



