USE SIGSALUD
update emergencia set sintomas = 'DOLOR LIMITACION FUNCIONAL BRAZO IZQ Y ADEMAS PRESENTA DOLOR Y A LA MOVILIZACION DE CADERAS', 
examen_fisico = 'HOMBRO IZQ DOLOR A LA MOVILIZACION, EQUIMOSIS -, EDEMA - CADERAS DOLOR A LA MOVILIZACION', CIEX4 = 'S72.0', CIEX1 = 'S70.0' WHERE EMERGENCIA_ID = '15023226'


/* UPDATE EMERGENCIA SET RELATO = 'PACIENTE ES TRAIDO POR PERSONAL DE BOMBEROS QUE REFIEREN QUE FUE IMPACTADO POR CUSTER, NO PERDIO EN NINGUN MOMENTO EL CONOCIMIENTO.  PACIENTE REFIERE QUE PRESENTA MUCHO DOLOR EN RODILLA IZQUIERDA, CON AUMENTO DE VOLUMEN Y DOLOR EN CODO IZQUIERDO'  WHERE EMERGENCIA_ID = '16030621' */
/* UPDATE EMERGENCIA SET CIEX5 = 'S50.1', TIPO_CIEX5 = 'D' WHERE EMERGENCIA_ID = '16030621' */

use SIGSALUD
SELECT TRATAMIENTO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16032242'

UPDATE EMERGENCIA SET TRATAMIENTO = 'SS RX DE CRANEO Y DE RODILLA, CODO IZQUIERDO  REEVALUACION CON RESULTADOS, INTERCONSULTA TRAUMATOLOGO' WHERE EMERGENCIA_ID = '16030621'


USE SIGSALUD
update emergencia set CIEX5 = 'S40.0', TIPO_CIEX5 = 'D', TIPO_CIEX4 = 'P', CIEX2 = 'S40.0', TIPO_CIEX2 = 'D' WHERE EMERGENCIA_ID = '15023226'


SELECT RELATO FROM EMERGENCIA WHERE EMERGENCIA_ID = '16030774'
UPDATE EMERGENCIA SET RELATO = 'REFIERE CAIDA MAS CORTE' WHERE EMERGENCIA_ID = '16030774'