use SIGSALUD
select * from EMERGENCIA where EMERGENCIA_ID = '15056486'
 
eXEC SP_get_emergencia_det_web_10 '15056486'


id_eme_det_web
15072721

select DETALLE from EMERGENCIA_DET_WEB where ID_EME_DET_WEB = '15056486'

/* update EMERGENCIA_DET_WEB set detalle = '02:00 AM PACIENDE DUERME, MANTIENE SUEÑO CONSERVADO, CONTINUA CON HIDRATACION. 
04:00 AM SE ADMINISTRA OXACILINA 2 GR EV DILUIDO Y LENTO
06:00 AM PACIENTE DESPIERTA REFIERE SENTIRSE UN POCO MEJOR.
07:30 AM PACIENTE QUEDA EN OBSERVACION , CONTINUA CON HIDRATACION.EV PP
AL CONTROL P/A 100/ 60 mmHg FC: 86 X FR: 18 X T° 37.2 SAT O2 95 % 
DIURESIS: 1 VEZ+' where ID_EME_DET_WEB = '15072425' */

'10-12 AM. PACIENTE EN SU UNIDAD. NO SIGNO DE ALARMA.  12:00 PM. SE ADM: CEFTRIAXONA 2 GR EV (VOLUTROL)  1-2 PM. SE3 BRINDA CONFORT Y CAMBIO POSTURAL  SE INSTALA I FCO DE DEXTROSA AL 5% + ELECROLITOS A XXX GTX  2:00 PM. SE ADM: OMEPRAZOL 40 MG EV (VOLUTROL)  4:00 PM. EN COMPAÑIA DE FAMILIARES.'


/* update EMERGENCIA_DET_WEB set detalle = '10-12 AM. PACIENTE EN SU UNIDAD. NO SIGNO DE ALARMA.  12:00 PM. SE ADM: CEFTRIAXONA 2 GR EV (VOLUTROL)  1-2 PM. SE3 BRINDA CONFORT Y CAMBIO POSTURAL  SE INSTALA I FCO DE DEXTROSA AL 5% + ELECROLITOS A XXX GTX  2:00 PM. SE ADM: OMEPRAZOL 40 MG EV (VOLUTROL)  4:00 PM. EN COMPAÑIA DE FAMILIARES.'
 where ID_EME_DET_WEB = '16000458'  */
 
 
' id_eme_det_web	codigo_profesional	abreviatura	profesional	foto	fecha	hora	emergencia_id	detalle	procedimiento	tipo_hidrico	temp	pa	fc	fr	sat_ox	peso	lugar	tipo_proceso	estado	paciente	via_oral	parenteral	tratamiento	transfusiones	infusiones	h2o	otros_i	subtotal_i	diuresis	deposiciones	drenajes	vomitos	perd_insens	otros_e	subtotal_e	bh_parcial	turno	nro_horas	estado_emergencia_id	ahora_profesional	antes_consul	ahora_consul
16000458	MPJ	ENF	ENF. MAYTA PAUCARA JULISSA ELIZABETH	42055619.jpg	02/01/2016	16:46: PM	15056486	10-12 AM. PACIENTE EN SU UNIDAD. NO SIGNO DE ALARMA.  12:00 PM. SE ADM: CEFTRIAXONA 2 GR EV (VOLUTROL)  1-2 PM. SE3 BRINDA CONFORT Y CAMBIO POSTURAL  SE INSTALA I FCO DE DEXTROSA AL 5% + ELECROLITOS A XXX GTX  2:00 PM. SE ADM: OMEPRAZOL 40 MG EV (VOLUTROL)  4:00 PM. EN COMPAÑIA DE FAMILIARES.	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	SALA DE OBSERVACION	P02	1	2015250383	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	3	NULL	NULL	NULL '

' id_eme_det_web	codigo_profesional	abreviatura	profesional	foto	fecha	hora	emergencia_id	detalle	procedimiento	tipo_hidrico	temp	pa	fc	fr	sat_ox	peso	lugar	tipo_proceso	estado	paciente	via_oral	parenteral	tratamiento	transfusiones	infusiones	h2o	otros_i	subtotal_i	diuresis	deposiciones	drenajes	vomitos	perd_insens	otros_e	subtotal_e	bh_parcial	turno	nro_horas	estado_emergencia_id	ahora_profesional	antes_consul	ahora_consul
16000363	MPJ	ENF	ENF. MAYTA PAUCARA JULISSA ELIZABETH	42055619.jpg	02/01/2016	09:36: AM	15056486	 7:30 AM. PACIENTE VARON, ADULTO MAYOR, SE ENCUENTRA EN CAMILLA EN ESPERA DE REFERENCIA  A HOSPITAL DE MAYOR COMPLEJIDAD. DX. MEDICO: CA DE ESTOMAGO.       AL EXAMEN PACIENTE DESPIERTO, CON TENDENCIA A LA SOMNOLENCIA, HIPOACTIVO, ADELGAZADO, QUEJUMBROSO AL CONTACTO, VENTILA O2 AMBIENTAL, PIEL PALIDA, SEMIHUMEDA,EDEMA DE MMSS Y MMII. PORTA SNG A GRAVEDAD CON ESCAZO DRENAJE DE SECRESION... CATETER EV PERIFERICO EN MSD PASANDO DEXTROSA AL 5% + ELECTROLITOS +- 500CC PP.  08:00 AM. SE MONITORIZA FUNCIONES VITALES:  PA 91/51 MMHG   FC  61X    SATO2 99%    T 37°C   FR 14X    SE BRINDA COMODIDAD Y CONFORT  SE COLOCA GUANTES DE AIRE EN TALONES A FIN DE EVITAR UPP  09:00 AM. PACIENTE EN OBSERVACION  	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	SALA DE OBSERVACION	P02	1	2015250383	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	3	NULL	NULL	NULL '

/* delete from EMERGENCIA_DET_WEB  where ID_EME_DET_WEB = '16000458' */


/* delete from EMERGENCIA_DET_WEB  where ID_EME_DET_WEB = '16000363' */



update EMERGENCIA_DET_WEB set detalle =  ' 7:30 AM. PACIENTE VARON, ADULTO MAYOR, SE ENCUENTRA EN CAMILLA EN ESPERA DE REFERENCIA  A HOSPITAL DE MAYOR COMPLEJIDAD. DX. MEDICO: CA DE ESTOMAGO.
     AL EXAMEN PACIENTE DESPIERTO, CON TENDENCIA A LA SOMNOLENCIA, HIPOACTIVO, ADELGAZADO, QUEJUMBROSO AL CONTACTO, VENTILA O2 AMBIENTAL, PIEL PALIDA, SEMIHUMEDA,EDEMA DE MMSS Y MMII. PORTA SNG A GRAVEDAD CON ESCAZO DRENAJE DE SECRESION... CATETER EV PERIFERICO EN MSD PASANDO DEXTROSA AL 5% + ELECTROLITOS +- 500CC PP.  08:00 AM. SE MONITORIZA FUNCIONES VITALES:  PA 91/51 MMHG   FC  61X    SATO2 99%    T 37°C   FR 14X    SE BRINDA COMODIDAD Y CONFORT  SE COLOCA GUANTES DE AIRE EN TALONES A FIN DE EVITAR UPP  09:00 AM. PACIENTE EN OBSERVACION  '
       where ID_EME_DET_WEB = '16000363'  




' hora  aten:
 14:13 '
 


select * from V_EMERGENCIA_PROCE_ENF_BALANCE_HIDRICO where emergencia_id='15056486' and estado=1 order by fecha, hora