USE SIGSALUD
declare @lcfecha1 datetime = convert(datetime, '2017-02-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-02-28', 101)

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J18.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J18.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J18.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J18.1' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J18.1' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J18.1' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J12' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J12' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J12' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J13' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J13' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J13' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J14' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J14' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J14' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J15' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J15' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J15' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'J16' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'J16' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'J16' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

UNION ALL

SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J18.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J18.1' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J12' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J13' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J14' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J15' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J16' AND TipoEdad = '1' AND Edad < 5 group by DX1 
