USE SIGSALUD
declare @lcfecha1 datetime = convert(datetime, '2017-02-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-02-28', 101)

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'A37' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'A37' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'A37' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J18.0' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J18.0' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J18.0' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J05.0' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J05.0' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J05.0' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J05.1' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J05.1' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J05.1' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J90' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J90' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J90' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J85.1' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J85.1' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J85.1' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J86' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J86' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J86' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J10' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J10' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J10' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J11' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J11' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J11' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J93.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J93.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J93.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT CIEX1 AS CIEX, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX1 = 'J18.8' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT CIEX2 AS CIEX, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX2 = 'J18.8' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT CIEX3 AS CIEX, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,7) < '000a02m'  and
CIEX3 = 'J18.8' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

UNION ALL

SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A37' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J18.0' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J05.0' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J05.1' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J90' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J85.1' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J86' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J10' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J11' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J93.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT DX1 as CIEX, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'J18.8' AND TipoEdad = '1' AND Edad < 5 group by DX1 
