USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_EMECIEX]    Script Date: 10/22/2015 12:38:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_EMECIEX](
	[IDEMECIEX] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NULL,
	[CIEX] [nvarchar](50) NULL,
	[FRECUENCIA] [int] NOT NULL,
 CONSTRAINT [PK_TMP_EMECIEX] PRIMARY KEY CLUSTERED 
(
	[IDEMECIEX] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


