select * from MEDICO where NOMBRE like 'macha%'

* 16045507

select MEDICO, MEDICO1, quien_atiende, CONSULTORIO   from EMERGENCIA where EMERGENCIA_ID = '16045507'

SELECT * FROM CONSULTORIO  ORDER BY NOMBRE ASC

update EMERGENCIA set ESTADO = '3', QUIEN_ATIENDE = 'MRE', CONSULTORIO = '1096'  where EMERGENCIA_ID = '16045507'

select 

