/* SELECCIONAR USUARIOS DE EMERGENCIA, ENFERMERA, MEDICO   */
use SIGSALUD
go

/* select * from USUARIO_WEB where dni = '41242857' */


DECLARE @lnombresenfermera varchar(100) = 'JUAN CARLOS'
DECLARE @lnombresmedico varchar(100) = 'ERIKA LOAYZA'  

DECLARE @ldni varchar(8) = '10244901'  

select * from USUARIO_WEB where dni = '41242857'
SELECT DNI, CLAVE, NOMBRES, UNIDAD_ORGANICA, CARGO,  ESTADO, FECHA_EXPIRACION, SESION, FOTO FROM USUARIO_WEB WHERE NOMBRES LIKE '%' +  @lnombresenfermera + '%' ORDER BY NOMBRES ASC
SELECT DNI, CLAVE, NOMBRES, UNIDAD_ORGANICA, CARGO,  ESTADO, FECHA_EXPIRACION, SESION, FOTO FROM USUARIO_WEB WHERE NOMBRES LIKE '%' +  @lnombresmedico + '%' ORDER BY NOMBRES ASC
SELECT DNI, CLAVE, NOMBRES, UNIDAD_ORGANICA, CARGO,  ESTADO, FECHA_EXPIRACION, SESION, FOTO FROM USUARIO_WEB WHERE dni = @ldni
SELECT * FROM medico WHERE dni = @ldni

SELECT * FROM medico WHERE medico = 'MPJ'
SELECT * FROM medico WHERE nombre like '%DEZA%'

/* update USUARIO_WEB set CARGO = 'ENFERMERO' where dni = '41242857' */

 






 