declare @lcfecha1 datetime = convert(datetime, '2017-03-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-03-23', 101)

TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_CIEMERHOS]
INSERT INTO [SIGSALUD].[dbo].[TMP_CIEMERHOS]([SERVICIO],[CANTIDAD])

SELECT 'EMERGENCIA ' AS SERVICIO,  COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00.9') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO,  COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00.9') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00.9') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00.9') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00.9') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00.9') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00.9') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00.9') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00.9') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 



UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00.9') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00.9') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00.9') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL
/*** SEGUNDO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL


/** FIN DE SEGUNDO DX */


/** INICIO DEL TERCER DX ***/

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.9') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.9') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.9') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.9') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.9') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.9') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.9') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.9') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.9') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.9') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.9') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.9') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 





/** FIN DE TERCERO DX */


UNION ALL

/** INICIO DEL CUARTO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09.9') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09.9') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09.9') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09.9') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09.9') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09.9') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09.9') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09.9') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09.9') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A09.9') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A09.9') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A09.9') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL


/*** FIN DE CUARTO DX ****/



/** INICIO DE QUINTO */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A00') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A00') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A00') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL


/*** FIN DE QUINTO DX */


/* INICIO DE SEXTO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

/* FIN DE SEXTO DX */

UNION ALL

/* INICIO DE SETIMO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.1') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.1') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.1') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.1') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.1') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.1') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.1') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.1') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.1') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.1') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.1') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.1') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL
/* FIN DE SETIMO DX */


/* INICIO DE OCTAVO DX */


SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.2') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.2') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.2') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.2') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.2') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.2') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.2') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.2') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.2') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.2') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.2') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.2') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL
/* FIN DE OCTAVO DX */


/* INICIO DEL NOVENO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.3') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.3') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.3') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.3') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.3') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.3') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.3') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.3') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.3') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.3') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.3') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.3') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


/* FIN DE NOVENO DX */

UNION ALL

/* INICIO DE DECIMO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.4') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.4') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.4') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.4') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.4') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.4') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.4') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.4') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.4') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A01.4') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A01.4') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A01.4') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 



UNION ALL
/* FIN DE DECIMO DX */



/* INICIO DE ONCEAVO DX */


SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A02') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A02') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A02') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A02') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A02') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A02') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A02') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A02') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A02') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A02') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A02') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A02') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

/* FIN DE ONCEAVO DX */


/* INICIO DE DOCEAVO DX */


SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

/* FIN DE DOCEAVO DX */


/* INICIO DE TRECEAVO DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03.9') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03.9') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03.9') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03.9') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03.9') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03.9') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03.9') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03.9') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03.9') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A03.9') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A03.9') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A03.9') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

/* FIN DE TRECEAVO DX */




/* INICIO DE CATORCE DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.5') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.5') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.5') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.5') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.5') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.5') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.5') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.5') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.5') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A04.5') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A04.5') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A04.5') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 




/* FIN DE CATORCE DX */

UNION ALL


/* INICIO DE QUINCE */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A05') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A05') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A05') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A05') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A05') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A05') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A05') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A05') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A05') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A05') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A05') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A05') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL


/* FIN DE QUINCEAVO */



/* INICIO DE DIECESIS DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

/* FIN DE DIECISESIS DX */



/*  INICIO DE 17 */


SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06.2') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06.2') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06.2') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06.2') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06.2') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06.2') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06.2') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06.2') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06.2') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A06.2') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A06.2') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A06.2') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

/* FIN DE 17 DX */

/* INICIO DE 18 DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A07') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A07') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A07') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A07') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A07') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A07') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A07') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A07') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A07') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A07') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A07') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A07') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

/* FIN DE 18 DX */


/* INICIO DE 19 DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL
/* FIN DE 19 DX */


/* INICIO DEL 20 DX */

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.2') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.2') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.2') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.2') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.2') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.2') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.2') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.2') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.2') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.2') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.2') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.2') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL
/* FIN DE 20 DX */



/** INCIO DE 21 DX */


SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.3') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.3') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.3') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.3') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.3') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.3') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.3') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.3') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.3') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.3') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.3') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.3') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL


/**** FIN DE 21 DX ***/


/** INICIO DE 22 DX **/

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.4') AND CIEX2 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.4') AND CIEX1 IN ('E86') AND  CIEX3 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.4') AND CIEX2 IN ('E86') AND  CIEX1 IN ('E86', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.4') AND CIEX2 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.4') AND CIEX1 IN ('R57.1') AND  CIEX3 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.4') AND CIEX2 IN ('R57.1') AND  CIEX1 IN ('R57.1', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 


UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.4') AND CIEX2 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.4') AND CIEX1 IN ('K56') AND  CIEX3 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.4') AND CIEX2 IN ('K56') AND  CIEX1 IN ('K56', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 

UNION ALL

SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A08.4') AND CIEX2 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A08.4') AND CIEX1 IN ('E87.2') AND  CIEX3 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 
UNION ALL
SELECT 'EMERGENCIA ' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A08.4') AND CIEX2 IN ('E87.2') AND  CIEX1 IN ('E87.2', '0') AND TIPO_CIEX1 = 'D'  GROUP BY CIEX1 




/** FIN DE 22 DX ****/



UNION ALL

SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 IN ('A00.9', 'E86', 'R57.1', 'K56.0', 'E87.2') and TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A09.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A04.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A09.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A00', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A01.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in('A01.1', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A01.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A01.3', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A01.4', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A02.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A03.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A03.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 



UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A04.5', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A05', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A06.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A07', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A08.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A08.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A08.3', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A08.4', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
 
 UNION ALL

SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 IN ('A00.9', 'E86', 'R57.1', 'K56.0', 'E87.2') and TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('A09.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A04.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A09.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A00', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A01.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in('A01.1', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A01.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A01.3', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A01.4', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A02.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A03.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A03.9', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 



UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A04.5', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A05', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  


UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A06.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A07', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A08.0', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A08.2', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  

UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A08.3', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 
  
  
UNION ALL
SELECT 'HOSPITALIZACION ' AS SERVICIO, COUNT(DX2) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX2 in ('A08.4', 'E86', 'R57.1', 'K56.0', 'E87.2') AND TipoEdad = '1' AND Edad < 5 group by DX2 

SELECT SERVICIO, SUM(CANTIDAD) AS CANTIDAD FROM [SIGSALUD].[dbo].[TMP_CIEMERHOS] GROUP BY SERVICIO

