  USE SIGSALUD
  declare @lcfecha1 datetime = convert(datetime, '2017-03-01', 101)
  declare @lcfecha2 datetime = convert(datetime, '2017-03-23', 101)
 TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_CIEMERHOS2] 
 INSERT INTO [SIGSALUD].[dbo].[TMP_CIEMERHOS2]([SERVICIO],[CANTIDAD]) 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('J45.0')  AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('J45.0') AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('J45.0')  AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('J45.9')  AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('J45.9') AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('J45.9')  AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('A46') AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('A46') AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('A46') AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('J44.8') AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('J44.8')  AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('J44.8') AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 IN ('J44.9') AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 IN ('J44.9') AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 IN ('J44.9') AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

UNION ALL

SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 IN ('J45.0') and TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('J45.9') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('J46') AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('J44.8') AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 in ('J44.9') AND TipoEdad = '1' AND Edad < 5 group by DX1 

 SELECT SERVICIO, SUM(CANTIDAD) AS CANTIDAD FROM [SIGSALUD].[dbo].[TMP_CIEMERHOS2] GROUP BY SERVICIO  
 
 

declare @lcfecha1 datetime = convert(datetime, '2017-03-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-03-23', 101)
select * from ATENCIOND where id_cita  in (select ID_CITA  from ATENCIONC where FECHA BETWEEN @lcfecha1 AND @lcfecha2) and DX LIKE ('J01%')



select ID_CITA  from ATENCIONC where FECHA BETWEEN @lcfecha1 AND @lcfecha2

/* AGREGAR EN CONDICON LOS DEFINITIVOS */


select * from ATENCIOND where id_cita  in (select ID_CITA  from ATENCIONC where FECHA BETWEEN @lcfecha1 AND @lcfecha2) and DX in ('J01')

select * from ATENCIOND where id_cita  in (select ID_CITA  from ATENCIONC where FECHA BETWEEN @lcfecha1 AND @lcfecha2) and DX in ('J029')