  USE SIGSALUD
  declare @lcfecha1 datetime = convert(datetime, '2017-03-01', 101)
  declare @lcfecha2 datetime = convert(datetime, '2017-03-23', 101)
  
TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_CIEMERHOS2] 
INSERT INTO [SIGSALUD].[dbo].[TMP_CIEMERHOS2]([SERVICIO],[CANTIDAD]) 
 
  
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A00.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 

UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A00.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A00.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A09' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A09' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A09' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A04.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A04.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A04.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A09.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A09.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A09.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A00' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A00' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A00' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A01' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A01' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A01' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A01.1' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A01.1' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A01.1' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A01.2' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A01.2' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A01.2' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3



union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A01.3' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A01.3' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A01.3' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A01.4' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A01.4' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A01.4' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A02' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A02' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A02' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A03' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A03' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A03' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A03.9' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A03.9' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A03.9' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A04.5' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A04.5' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA', COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A04.5' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3



union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A05' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A05' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A05' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A06' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A06' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A06' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A06.2' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A06.2' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A06.2' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A07' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A07' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A07' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A08' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A08' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A08' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A08.2' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A08.2' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A08.2' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A08.3' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A08.3' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A08.3' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3


union all 

SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX1) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX1 = 'A08.4' AND TIPO_CIEX1 = 'D' GROUP BY CIEX1 
UNION ALL 
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX2) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX2 = 'A08.4' AND TIPO_CIEX2 = 'D' GROUP BY CIEX2
UNION ALL
SELECT 'EMERGENCIA' AS SERVICIO, COUNT(CIEX3) AS CANTIDAD FROM EMERGENCIA WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND substring(EDAD,1,3) < '005' and
CIEX3 = 'A08.4' AND TIPO_CIEX3 = 'D' GROUP BY CIEX3

UNION ALL

SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A00.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION'  AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A09' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION'  AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A04.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A09.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT 'HOSPITALIZACION'  AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A00' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A01' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A01.1' AND TipoEdad = '1' AND Edad < 5 group by DX1 
 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A01.2' AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A01.3' AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A01.4' AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A02' AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A03' AND TipoEdad = '1' AND Edad < 5 group by DX1 


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A03.9' AND TipoEdad = '1' AND Edad < 5 group by DX1 



UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A04.5' AND TipoEdad = '1' AND Edad < 5 group by DX1 

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A05' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  


UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A06.2' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
  
UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A07' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A08' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A08.2' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  

UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A08.3' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
  
UNION ALL
SELECT 'HOSPITALIZACION' AS SERVICIO, COUNT(DX1) as CANTIDAD FROM HOSPITALIZACION 
  WHERE FECHA1 BETWEEN @lcfecha1 AND @lcfecha2 and DX1 = 'A08.4' AND TipoEdad = '1' AND Edad < 5 group by DX1 
  
SELECT SERVICIO, SUM(CANTIDAD) AS CANTIDAD FROM [SIGSALUD].[dbo].[TMP_CIEMERHOS2] GROUP BY SERVICIO


