
use sigsalud 
DECLARE @lfecha1 varchar(10) = '2016-03-01'
DECLARE @lfecha2 varchar(10) = '2016-03-31'

SELECT COUNT(A.emergencia_id) AS CNT
    FROM EMERGENCIA A INNER JOIN
     BDCATEGORIAS B ON B.COD_CAT = A.CODGRUPO INNER JOIN
     dbo.CIEX C ON A.CIEX1 = C.CIEX 
WHERE A.FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101) AND CIEX1 <> '0'

/*
SELECT COUNT(A.emergencia_id) AS CNT
FROM EMERGENCIA A INNER JOIN
     BDCATEGORIAS B ON B.COD_CAT = A.CODGRUPO 
WHERE A.FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101) AND CIEX1 <> '0' */

SELECT     dbo.EMERGENCIA.ESTADO, dbo.EMERGENCIA.FECHA, dbo.EMERGENCIA.SEXO, dbo.EMERGENCIA.CONSULTORIO, dbo.CONSULTORIO.NOMBRE, 
                      dbo.EMERGENCIA.EDAD, dbo.EMERGENCIA.CIEX1, dbo.CIEX.NOMBRE AS Expr1, dbo.EMERGENCIA.CODGRUPO, dbo.BDCATEGORIAS.DESC_CAT, 
                      dbo.BDCATEGORIAS.COD_CAP, dbo.BDCAPITULOS.DESC_CAP, dbo.BDCAPITULOS.COD_CIE, dbo.BDCATEGORIAS.COD_GRU, dbo.BDGRUPOS.DESC_GRU, 
                      dbo.BDGRUPOS.COD_GRU + dbo.BDGRUPOS.COD_CAP AS CAPI
FROM         dbo.EMERGENCIA INNER JOIN
                      dbo.CONSULTORIO ON dbo.EMERGENCIA.CONSULTORIO = dbo.CONSULTORIO.CONSULTORIO INNER JOIN
                      dbo.CIEX ON dbo.EMERGENCIA.CIEX1 = dbo.CIEX.CIEX INNER JOIN
                      dbo.BDCATEGORIAS ON dbo.EMERGENCIA.CODGRUPO = dbo.BDCATEGORIAS.COD_CAT INNER JOIN
                      dbo.BDCAPITULOS ON dbo.BDCATEGORIAS.COD_CAP = dbo.BDCAPITULOS.COD_CAP INNER JOIN
                      dbo.BDGRUPOS ON dbo.BDCATEGORIAS.COD_CAP = dbo.BDGRUPOS.COD_CAP AND dbo.BDCATEGORIAS.COD_GRU = dbo.BDGRUPOS.COD_GRU
                      WHERE  EMERGENCIA.FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101)
                      
/*
SELECT * FROM TABLA1
WHERE EMERGENCIA_ID NOT IN
(SELECT TABLA2.EMERGENCIA_ID FROM TABLA2)
*/