/* PARA CERRAR */
declare @lcfecha varchar(10) = '2018-01-08'
update [SIGSALUD].[dbo].[CUENTA] set estado = '2' where estado = '1' and seguro = '01' and ORIGEN = 'EM' and  CUENTAID in 
(select CUENTAID  from [SIGSALUD].[dbo].[EMERGENCIA] where ESTADO in ('4', '5')  AND SEGURO = '01' AND 
FECHA  = CONVERT(DATETIME, @lcfecha, 101) and datediff (hh, CONVERT(TIME, HORA_SAL), CONVERT(TIME, GETDATE())) >= 6)
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA < CONVERT(DATETIME, @lcfecha, 101) 


/* PARA REVISION */

SELECT GETDATE() - 1, convert(datetime, '2017-12-04',101), CONVERT(VARCHAR(10), GETDATE() - 1, 120) 

declare @lcfecha_revisar datetime = convert(datetime, CONVERT(VARCHAR(10), GETDATE() - 1, 120) ,101)
SELECT @lcfecha_revisar, A.FECHA, A.HORA, A.FECHA_SAL, A.HORA_SAL, A.NOMBRES, A.ESTADO AS ESTADO_EMERGENCIA, B.ESTADO AS ESTADO_CUENTA,B.NOMBRE, B.SEGURO, B.FECHA_APERTURA FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_revisar
AND B.ORIGEN = 'EM' AND B.ESTADO = '1' order by fecha DESC 
SELECT * FROM [SIGSALUD].[dbo].[CUENTA]  WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha_revisar, 101) 
ORDER BY CUENTAID DESC




/* PARA ACTUALIZAR TODOS LAS CUENTAS DE DIAS ANTERIORES */
declare @lcfecha_actualizar datetime = convert(datetime, '2018-01-08',101)
UPDATE [SIGSALUD].[dbo].[CUENTA] SET ESTADO = '2' WHERE CUENTAID IN (SELECT B.CUENTAID FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_actualizar 
AND B.ORIGEN = 'EM' AND B.ESTADO = '1')
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA < CONVERT(DATETIME, @lcfecha_actualizar, 101) 

-- 99


/* Revisar solo las cuentas de liquidaciones - consultorios  */
declare @lcfecha_revisar datetime = convert(datetime, '2017-11-29',101)
SELECT * FROM [SIGSALUD].[dbo].[CUENTA]  WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA < CONVERT(DATETIME, @lcfecha_revisar, 101) 
ORDER BY CUENTAID DESC





/*************** EJECUTAR *******/

declare @lcfecha_revisar datetime = convert(datetime, CONVERT(VARCHAR(10), GETDATE() - 1, 120) ,101)
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE CUENTAID IN (SELECT B.CUENTAID FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_revisar
AND B.ORIGEN = 'EM' AND B.ESTADO = '1')
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN IN ('LB', 'CE', 'OT', 'AD') AND SEGURO = '01' AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha_revisar, 101) 



SELECT ESTADO, * FROM [SIGSALUD].[dbo].[CUENTA] 

SELECT ORIGEN FROM [SIGSALUD].[dbo].[CUENTA] GROUP BY ORIGEN 



declare @lcfecha_revisar datetime = convert(datetime, CONVERT(VARCHAR(10), GETDATE() - 1, 120) ,101)
SELECT A.CUENTAID, B.CUENTAID, A.FECHA, A.HORA, A.FECHA_SAL, A.HORA_SAL, A.NOMBRES, A.ESTADO AS ESTADO_EMERGENCIA, B.ESTADO AS ESTADO_CUENTA,B.NOMBRE, B.SEGURO, B.FECHA_APERTURA FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_revisar
AND B.ORIGEN = 'EM' AND B.ESTADO = '1' order by fecha DESC 
SELECT * FROM [SIGSALUD].[dbo].[CUENTA]  WHERE ESTADO = '1' and ORIGEN IN ('LB', 'CE', 'OT', 'AD')  AND SEGURO = '01' 
   AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha_revisar, 101)  ORDER BY CUENTAID DESC


select CUENTAID from [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17053432'


select CASE WHEN ESTADO = '0' THEN 'CTA. ANULADA' WHEN ESTADO = '1' THEN 'CTA. LIQ. ACTIVO - ABIERTA' WHEN ESTADO = '2' THEN 'CTA. PRE LIQUIDADO - CERRADA'
     WHEN ESTADO = '4' THEN 'CTA. CANCELADO - AUDITADA' ELSE 'CTA. ANTIGUA / NO DEFINIDA' END ESTADO_CUENTA from [SIGSALUD].[dbo].[CUENTA]
      WHERE CUENTAID = (select CUENTAID from [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17052673')


select * from [SIGSALUD].[dbo].[CUENTA]
      WHERE CUENTAID = (select CUENTAID from [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17052673')
      
select * from [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17052673'





select ESTADO, 
CASE WHEN ESTADO = '0' THEN 'CTA. ANULADA'
     WHEN ESTADO = '1' THEN 'CTA. LIQ. ACTIVO - ABIERTA'
     WHEN ESTADO = '2' THEN 'CTA. PRE LIQUIDADO - CERRADA'
     WHEN ESTADO = '4' THEN 'CTA. CANCELADO - AUDITADA'
     ELSE 'CTA. ANTIGUA / NO DEFINIDA' END ESTADO_CUENTA
  from [SIGSALUD].[dbo].[CUENTA]
GROUP BY ESTADO


SELECT A.CUENTAID, B.CUENTAID, A.FECHA, A.HORA, A.FECHA_SAL, A.HORA_SAL, A.NOMBRES, A.ESTADO AS ESTADO_EMERGENCIA, B.ESTADO AS ESTADO_CUENTA,B.NOMBRE, B.SEGURO, B.FECHA_APERTURA FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_revisar
AND B.ORIGEN = 'EM' AND B.ESTADO = '1' order by fecha DESC 
SELECT * FROM [SIGSALUD].[dbo].[CUENTA]  WHERE ESTADO = '1' and ORIGEN IN ('LB', 'CE', 'OT', 'AD')  AND SEGURO = '01' 
   AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha_revisar, 101)  ORDER BY CUENTAID DESC



