/* SET LANGUAGE SPANISH */

SELECT FECHA, CONVERT(VARCHAR(10), FECHA, 103)  AS FECHVAR, SUBSTRING(CONVERT(VARCHAR(10), FECHA, 103), 1,2) AS DIA, 
  SUBSTRING(CONVERT(VARCHAR(10), FECHA, 103), 4,2) AS MES, SUBSTRING(CONVERT(VARCHAR(10), FECHA, 103), 7,5) AS ANIO  FROM EMERGENCIA ORDER BY DIA, MES, ANIO DESC