DECLARE @indice INTEGER;
DECLARE @anho INTEGER;
DECLARE @anho_hoy VARCHAR(4);
DECLARE @codigo VARCHAR(8);
SET @anho_hoy = SUBSTRING(CONVERT(CHAR,YEAR(GETDATE())),3,2);
SELECT @indice = ISNULL(SUBSTRING(MAX(ID_EME_DET_WEB),3,8),0) FROM EMERGENCIA_DET_WEB WHERE ID_EME_DET_WEB like @anho_hoy+'%';
SELECT @anho = SUBSTRING(MAX(ID_EME_DET_WEB),1,2) FROM EMERGENCIA_DET_WEB;
if(@anho=@anho_hoy)
	SET @indice = @indice + 1;
else
	SET @indice = 1;
SET @codigo = @anho_hoy + RIGHT('000000' + Ltrim(Rtrim(@indice)),6)	
SELECT @codigo AS  CODIGO

SELECT MAX(ID_EME_DET_WEB) AS IDWEB FROM EMERGENCIA_DET_WEB
/* 15049792  */

SELECT * FROM  EMERGENCIA_DET_WEB WHERE ID_EME_DET_WEB = '15049792'

   select CONVERT(CHAR(2), SUBSTRING(CONVERT(CHAR,YEAR(GETDATE())),3,2)) AS ANIO_HOY, SUBSTRING(MAX(ID_PROCE_WEB),1,2) AS ANIO, SUBSTRING(MAX(ID_PROCE_WEB),3,6) AS CORRE, (CONVERT(INT, SUBSTRING(MAX(ID_PROCE_WEB),3,6)) + 1) AS SIGUE
	                    from dbo.EMERGENCIA_PROC_WEB