
/* Para Enfermera */
  DECLARE @lnombres varchar(100) = 'chuyes'  
 
 /* Para Medicos */
  /* DECLARE @lnombres varchar(100) = 'RAMOS'  */

/* Para Administradores */
/* DECLARE @lnombres varchar(100) = 'OBESO CAMONES'  */


/* Para Busqueda DNI */
/*DECLARE @ldni varchar(10) = '09728433'
SELECT * FROM USUARIO_WEB WHERE DNI = @ldni */

/* SELECCION DEL USUARIO Y SUS PERMISOS */
/* SELECT * FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%' ORDER BY NOMBRES ASC
SELECT * FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%')
SELECT * FROM ACCESO_MENU WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%')
SELECT * FROM ACCESO_SUBMENU WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%') */
/* SELECT * FROM ACCESO_BOTONES WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%') */

/* SELECCION LAS PLANTILLAS */
SELECT * FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%'))
SELECT * FROM PLANTILLA_MENU WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%')))
SELECT * FROM PLANTILLA_SUBMENU WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%')))
SELECT *  FROM PLANTILLA_BOTONES WHERE ID_PL_M IN (SELECT ID_PL_M FROM PLANTILLA_MODULO where NOMBRE IN (SELECT NOMBRE FROM ACCESO_MODULO WHERE DNI = (SELECT DNI FROM USUARIO_WEB WHERE NOMBRES LIKE '%' + @lnombres + '%'))) order by ID_PL_BOTON asc


/* select * from USUARIO_WEB where CARGO = 'MEDICO' order by NOMBRES asc
   select * from USUARIO_WEB where CARGO = 'MEDICO' order by NOMBRES asc */
   
   /* INSERT INTO ACCESO_BOTONES (ID_BOTON, NOMBRE, ICONO, ESTADO, ID_SUBMENU, ID_MENU, ID_AM, DNI, ID_HTML)
           VALUES ('1014876315000033', 'Desbloquear Paciente Cerrado', '<i class="fa fa-list-alt"></i>', '1','1014876315000005', '1014876315000004', '1014876315000002', '10148763', 'desbloquear-paciente')  */
      
  
/*  SELECT * FROM PLANTILLA_SUBMENU   */
  
/* update PLANTILLA_SUBMENU set ESTADO = '0' where ID_PL_SUBMENU = '15000024' */
 
 /* DELETE FROM PLANTILLA_SUBMENU WHERE ID_PL_SUBMENU = '15000024'
 
 DELETE FROM PLANTILLA_BOTONES  WHERE ID_PL_SUBMENU = '15000024' */
 
 
 /* 
 SELECT * FROM ACCESO_SUBMENU WHERE ID_MENU LIKE '%15000004'
 SELECT * FROM ACCESO_MENU WHERE NOMBRE LIKE '%Otras aten%'
 select * from plantilla_submenu 
UPDATE PLANTILLA_SUBMENU set ESTADO = 1 where ID_PL_SUBMENU = 15000006
select * from plantilla_botones where id_pl_submenu = 15000006
UPDATE plantilla_botones SET ESTADO = 1 where id_pl_submenu = 15000006 */

