/* AGREGAR PROCESO PARA PACIENTE AUSENCTADO */

  
INSERT INTO [SIGSALUD].[dbo].[EMERGENCIA_TIPO_PROCESO_WEB]([TIPO_PROCESO],[DESCRIPCION],[ESTADO])
     VALUES ('P15', 'PACIENTE DE EMERGENCIA AUSENTADO', 1)