/* PROGRAMA EJECUTADO A LAS 19:00 */

declare @lcfecha varchar(10) = '2017-11-09'
UPDATE [SIGSALUD].[dbo].[CUENTA] SET ESTADO = '2' where ESTADO = '1' and ORIGEN = 'EM' AND SEGURO = '01' AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha, 101) 
AND CUENTAID IN (select CUENTAID from [SIGSALUD].[dbo].[EMERGENCIA] where ESTADO = '4'  AND SEGURO = '01' AND 
FECHA BETWEEN  CONVERT(DATETIME, '2016-06-06', 101) AND CONVERT(DATETIME, @lcfecha, 101))
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha, 101) 

