use sigsalud
SELECT     EM.ESTADO, EM.EMERGENCIA_ID, EM.FECHA, EM.HORA, EM.ORDEN, EM.PACIENTE, PA.HISTORIA, EM.NOMBRES, OCU.NOMBRE AS OCUPACION, 
                      EM.FECHA_NACIMIENTO, EM.SEXO, SEG.NOMBRE AS NOMBRE_SEGURO, EM.CIEX1, CX.NOMBRE AS NOMBRE_DIAGNOSTICO1, EM.CIEX2, 
                      CX2.NOMBRE AS NOMBRE_DIAGNOSTICO2, EM.CIEX3, CX3.NOMBRE AS NOMBRE_DIAGNOSTICO3, EM.CIEX4, CX4.NOMBRE AS NOMBRE_DIAGNOSTICO4, 
                      EM.CIEX5, CX5.NOMBRE AS NOMBRE_DIAGNOSTICO5, EM.CIEX6, CX6.NOMBRE AS NOMBRE_DIAGNOSTICO6, EM.CONSULTORIO, 
                      CON.NOMBRE AS NOMBRE_CONSULTORIO, EM.CUENTAID, EM.MOTIVO_EMERGENCIA, EM.USUARIO AS USUARIO_ADMISION, ME.NOMBRE AS NOMBRE_MOTIVO, 
                      MED3.MEDICO, MED3.NOMBRE AS NOMBRE_MEDICO, EM.DIRECCION, EM.ESTADO_CIVIL, EC.NOMBRE AS NOMBRE_ESTADOCIVIL, EM.DISTRITO, 
                      EM.DOCUMENTO, EM.DOCUMENTOA, EM.TELEFONO1, EM.TELEFONO2, EM.ACOMPANANTE, EM.PATERNO, EM.MATERNO, EM.NOMBRE AS NOMBRE_PACIENTE, 
                      EM.EDAD, SEX.NOMBRE AS NOMBRE_SEXO, EM.SEGURO, EM.PRE_AFILIACION, EM.OBSERVACION1, EM.OBSERVACION2, EM.LOCALIDAD, 
                      LOC.Nombre AS NOMBRE_LOCALIDAD, EM.CONSULTORIO1, EM.TIPOATENCION, EM.PRIORIDAD, EM.TEMPERATURA, EM.PRESION, EM.PULSO, EM.FR, EM.FC, 
                      EM.SAT_OX, MED.ABREVIATURA + '.' + UW.NOMBRES AS USUARIO_FN_VITALES, EM.EXAMEN_FISICO, EM.RELATO, EM.EVOLUCION, EM.SINTOMAS, 
                      EM.TRATAMIENTO, EM.TIPO_CIEX1, EM.TIPO_CIEX2, EM.TIPO_CIEX3, EM.TIPO_CIEX4, EM.TIPO_CIEX5, EM.TIPO_CIEX6, EM.HORA_ATEN, EM.PESO, EM.HORA_SAL, 
                      EM.FECHA_SAL, DS.NOMBRE AS DESTINO, EM.MEDICO AS MEDICO_SALIDA, MED2.NOMBRE AS NOMBRE_MEDICO_SALIDA, 
                      MED4.ABREVIATURA + ' ' + MED4.NOMBRE AS USUARIO_ALTA_ENF, EM.FECHA_HORA_ALTA_ENF, EM.PRESIOND, EL.DESCRIPCION AS ESTADO_PACIENTE, 
                      EM.FECHA_ATENCION, EM.ESTABLECIMIENTO, R.NOMBRE AS DESRELIGION, EM.QUIEN_ATIENDE, EM.HORAINICIOATENCION
FROM         dbo.EMERGENCIA AS EM LEFT OUTER JOIN
                      dbo.MEDICO AS MEDX ON EM.USUARIO_FN_VITALES = MEDX.MEDICO LEFT OUTER JOIN
                      dbo.USUARIO_WEB AS UW ON MEDX.DNI = UW.DNI LEFT OUTER JOIN
                      dbo.MEDICO AS MED ON UW.DNI = MED.DNI INNER JOIN
                      dbo.SEGURO AS SEG ON EM.SEGURO = SEG.SEGURO INNER JOIN
                      dbo.CIEX AS CX ON EM.CIEX1 = CX.CIEX INNER JOIN
                      dbo.CONSULTORIO AS CON ON EM.CONSULTORIO = CON.CONSULTORIO INNER JOIN
                      dbo.MOTIVO_EMERGENCIA AS ME ON EM.MOTIVO_EMERGENCIA = ME.MOTIVO_EMERGENCIA INNER JOIN
                      dbo.MEDICO AS MED2 ON EM.MEDICO = MED2.MEDICO INNER JOIN
                      dbo.ESTADO_CIVIL AS EC ON EM.ESTADO_CIVIL = EC.ESTADO_CIVIL INNER JOIN
                      dbo.SEXO AS SEX ON EM.SEXO = SEX.SEXO INNER JOIN
                      dbo.LOCALIDAD AS LOC ON EM.LOCALIDAD = LOC.Localidad LEFT OUTER JOIN
                      dbo.PACIENTE AS PA ON EM.PACIENTE = PA.PACIENTE INNER JOIN
                      dbo.CIEX AS CX2 ON EM.CIEX2 = CX2.CIEX INNER JOIN
                      dbo.CIEX AS CX3 ON EM.CIEX3 = CX3.CIEX INNER JOIN
                      dbo.CIEX AS CX4 ON EM.CIEX4 = CX4.CIEX INNER JOIN
                      dbo.CIEX AS CX5 ON EM.CIEX5 = CX5.CIEX INNER JOIN
                      dbo.CIEX AS CX6 ON EM.CIEX6 = CX6.CIEX INNER JOIN
                      dbo.DESTINO AS DS ON EM.DESTINO = DS.DESTINO INNER JOIN
                      dbo.MEDICO AS MED3 ON EM.MEDICO1 = MED3.MEDICO LEFT OUTER JOIN
                      dbo.MEDICO AS MED4 ON EM.USUARIO_ALTA_ENF = MED4.DNI LEFT OUTER JOIN
                      dbo.EMERGENCIA_LUGAR_WEB AS EL ON EM.ESTADO_PACIENTE = EL.LUGAR INNER JOIN
                      dbo.RELIGION AS R ON R.RELIGION = EM.RELIGION INNER JOIN
                      dbo.OCUPACION AS OCU ON PA.OCUPACION = OCU.OCUPACION
                                            
                      WHERE EM.EMERGENCIA_ID =  '16043321'
                      


DECLARE @lidemergencia varchar(13) =  '16043321' /* '16037314'   */
use SIGSALUD
/* USUARIO QUE REGISTRO FUNCIONES VITALES )POR LO GENERAL LA ENFERMERA O EL TECNICO) EXISTE EN LA TABLA MEDICOS - RELACIONADO POR CODIGO DEL MEDICO   COMPARA LA TABLA DE EMERGENCIA Y LA TABLA MEDICO */
select MEDICO AS USUARIO_FN_VITALES from MEDICO where MEDICO = (select usuario_fn_vitales from EMERGENCIA where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA QUE EL USUARIO QUE HA INGRESAOD EN EL SISTEMA (TABLA USUARIO_WEB) EXISTA EN LA TABLA MEDICOS -- COMPARANDO LOS DNI - TABLAS USUARIO_WEB Y TABLA MEDICOS*/
select DNI from usuario_web where dni = (select dni from medico where medico = (select usuario_fn_vitales from EMERGENCIA where EMERGENCIA_ID = @lidemergencia))

/* COMPRUEBA EL USUARIO DE FUNCIONES VITALES PARA OBTENER LA ABREVIATURA : UNIDO POR DNI - TABLA MEDICO Y TABLA DE EMERGENCIA */
select MEDICO from medico where medico = (select MEDICO from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA QUE EL CODIGO DE SEGURO EXISTE TABLA SEGURO Y TABLA DE EMERGENCIA */
select SEGURO from SEGURO where SEGURO = (select SEGURO from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA QUE EL CODIGO DE CONSULTORIO EXISTE - TABLA CONSULTORIO Y TABLA EMERGENCIA */
select CONSULTORIO from consultorio where consultorio = (select consultorio from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA QUE EL CODIGO DE MOTIVO DE EMERGENCIA EXISTE - TABLA MOTIVO_EMERGENCIA Y TABLA EMERGENCIA */
select MOTIVO_EMERGENCIA from motivo_emergencia where MOTIVO_EMERGENCIA  = (select MOTIVO_EMERGENCIA from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA TABLA ESTADO CIVIL Y TABLA EMERGENCIA UNIDO PRO CODIGO ESTADO CIVIL */
select ESTADO_CIVIL from estado_civil where estado_civil = (select estado_civil from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA TABLA SEXO Y LA TABLA EMERGENCIA UNIDO POR LA COLUMNA SEXO */
select SEXO from sexo where SEXO = (select sexo from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA TABLA LOCALIDAD EN TABLA LOCALIDAD Y TABLA DE EMERGENCIA */
select LOCALIDAD from localidad where localidad = (select localidad from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMRPUEBA CODIGO DE PACIENTE EN TABLA PACIENTE Y EMERGENCIA */
select PACIENTE from paciente where paciente = (select paciente from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA EL PRIMER DIAGNOSTICO DX 4 - DIAGNOSTICO DE ENTRADA  TABLA CIEX Y TABLA DE EMERGENCIA */
select CIEX AS CIEX4 from CIEX where ciex = (select ciex4 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)
/* COMPRUEBA EL SEGUNDO DIAGNOSTICO DX 5 - SEGUNDO DIAGNOSTICO DE ENTRADA  TABLA CIEX Y TABLA DE EMERGENCIA */
select CIEX AS CIEX5 from CIEX where ciex = (select ciex5 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)
/* COMPRUEBA EL TERCER DIAGNOSTICO DX 6 - TERCER DIAGNOSTICO DE ENTRADA  TABLA CIEX Y TABLA DE EMERGENCIA */
select CIEX AS CIEX6 from CIEX where ciex = (select ciex6 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA EL DIAGNOSTICO DE SALIDA DX1 - TABLA CIEX Y TABLA EMERGENCIA */
select CIEX AS CIEX1 from CIEX where ciex = (select ciex1 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA EL DIAGNOSTICO DE SALIDA DX2 - TABLA CIEX Y TABLA EMERGENCIA */
select CIEX AS CIEX2 from CIEX where ciex = (select ciex2 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA EL DIAGNOSTICO DE SALIDA DX3 - TABLA CIEX Y TABLA EMERGENCIA */
select CIEX AS CIEX3 from CIEX where ciex = (select ciex3 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* COMPRUEBA EL DESTINO TABLA DESTINO Y EMERGENCIA  */
select DESTINO  from destino where destino = (select destino from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* VERIFICA EL NOMBRE DEL MEDICO - TABLA MEDICO - EMERGENCIA, COLUMNA DE COMPARACION : MEDICO1 */
select MEDICO AS MEDICO1 from medico where medico  = (select MEDICO1 from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)


/* VERIFICA IGUALDAD DE EN LAS TABLAS EMERGENCIA_LUGAR_WEB Y EMERGENCIA UNIDO POR LA CONDICION : LUGAR = ESTADO_PACIENTE */
select LUGAR from emergencia_lugar_web where lugar = (select estado_paciente from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* VERIFICA IGUALDAD DE LOS CODIGOS DE RELIGION TABLA RELIGION Y TABLA EMERGENCIA */
select RELIGION from religion where religion = (select religion from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia)

/* VERIFICA QUE OCUPACION ESTE IGUAL EN EL TABLA OCUPACION, PACIENTE Y EMERGENCIA */
select OCUPACION from ocupacion where ocupacion = (select OCUPACION  from paciente where paciente = (select paciente from EMERGENCIA  where EMERGENCIA_ID = @lidemergencia))



use SIGSALUD
declare @lidemergencia varchar(13) = '16037441'
SELECT * FROM dbo.V_UTILIZAR_HC_EMER_WEB WHERE EMERGENCIA_ID = @lidemergencia


select usuario_fn_vitales from EMERGENCIA where EMERGENCIA_ID = '16037438'
JGM
update emergencia set usuario_fn_vitales = '' from EMERGENCIA where EMERGENCIA_ID = '16037438'


update EMERGENCIA set CIEX4 = '0' where EMERGENCIA_ID = '16037438'
update EMERGENCIA set CIEX4 = '' where EMERGENCIA_ID = '16037438'

select RELIGION from EMERGENCIA where EMERGENCIA_ID = '16037438'
update EMERGENCIA set RELIGION = '' where EMERGENCIA_ID = '16037438'
update EMERGENCIA set RELIGION = '01' where EMERGENCIA_ID = '16037438'

select LOCALIDAD from EMERGENCIA where EMERGENCIA_ID = '16037438'
update EMERGENCIA set localidad = 'L01' where EMERGENCIA_ID = '16037438'

select paciente from EMERGENCIA where EMERGENCIA_ID = '16037438'
/* 2015251890 */

update EMERGENCIA set paciente = '2015251890' where EMERGENCIA_ID = '16037438'
update EMERGENCIA set paciente = '' where EMERGENCIA_ID = '16037438'


SELECT CIEX4, CIEX5, CIEX6, CIEX1, CIEX2, CIEX3 FROM EMERGENCIA WHERE EMERGENCIA_ID = '16043321'




