use SIGSALUD
select * from EMERGENCIA where EMERGENCIA_ID = '16032212'

select * from EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16032212' and TIPO_PROCESO = 'P04'
select * from EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16032212' and TIPO_PROCESO = 'P12'

select * from V_EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16032212'

SELECT [TIPO_PROCESO],[DESCRIPCION],[ESTADO]  FROM [SIGSALUD].[dbo].[EMERGENCIA_TIPO_PROCESO_WEB]


delete from EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16032212' and TIPO_PROCESO = 'P04'