   declare @lcbuscanombres varchar(250) = 'PEREZ CARRASCO'
   select ESTADO, EMERGENCIA_ID, convert(varchar(10), fecha, 103) AS FECHA_EMERGENCIA,   HORA, a.ORDEN, ESTADO, A.PATERNO, A.materno, a.NOMBRE, A.NOMBRES, a.consultorio, b.NOMBRE AS NOMBRE_CONSULTORIO, A.FECHA_NACIMIENTO, A.EDAD, A.SEXO, A.ESTADO_CIVIL, A.DIRECCION, HORA_ATEN, 
     convert(varchar(10), FECHA_ATENCION, 103) AS FECHA_ATENCION_EMERGENCIA, PRIORIDAD,  SINTOMAS, RELATO, EXAMEN_FISICO, CIEX4, TIPO_CIEX4, CIEX5, TIPO_CIEX5,CIEX6, TIPO_CIEX6, TRATAMIENTO, fecha_salida, observacion_egreso,  CIEX1, TIPO_CIEX1, CIEX2, TIPO_CIEX2, CIEX3, TIPO_CIEX3, C.HISTORIA, C.DOCUMENTO, D.NOMBRE NOMBRE_SEGURO, E.NOMBRE NOMBRE_RELIGION,
    UPPER(F.NOMBRE) NOMBRE_OCUPACION, g.NOMBRE as NOMBRE_CIEX4, H.NOMBRE AS NOMBRE_CIEX5, I.NOMBRE AS NOMBRE_CIEX6, J.NOMBRE NOMBRE_MEDICO, FECHA_SALIDA, convert(char(5), FECHA_SALIDA, 108) as HORA_SALIDA,
    CONVERT(VARCHAR(10), FECHA_SALIDA, 103) FECHA_SAL, UPPER(K.NOMBRE) AS NOMBRE_DESTINO, a.destino,  A.ESTABLECIMIENTO, l.NOMBRE as NOMBRE_CIEX1, m.NOMBRE as NOMBRE_CIEX2, n.NOMBRE as NOMBRE_CIEX3, a.TIPO_CIEX1, a.TIPO_CIEX2, a.TIPO_CIEX3
     from emergencia a left join CONSULTORIO b on b.CONSULTORIO = a.CONSULTORIO LEFT JOIN PACIENTE C ON C.PACIENTE = A.PACIENTE  LEFT JOIN SEGURO D ON D.SEGURO = A.SEGURO LEFT JOIN RELIGION E
     ON E.RELIGION = A.RELIGION  LEFT JOIN OCUPACION F ON F.OCUPACION = C.OCUPACION left join CIEX G on g.CIEX = a.CIEX4 LEFT JOIN CIEX H ON H.CIEX = A.CIEX5
     LEFT JOIN CIEX I ON I.CIEX = A.CIEX6 LEFT JOIN MEDICO J ON J.MEDICO = A.QUIEN_ATIENDE LEFT JOIN DESTINO K ON K.DESTINO = A.DESTINO 
     left join CIEX l on l.CIEX = a.CIEX1 left join CIEX M ON M.CIEX = A.CIEX2 left join CIEX N on n.CIEX = a.CIEX3  where  A.NOMBRES like '%' + @lcbuscanombres + '%' ORDER BY FECHA DESC   



UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '25/02/2017', 103) + CAST('14:39' AS DATETIME), CIEX1 = 'S80.8', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17008101'   


UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '25/02/2017', 103) + CAST('02:40' AS DATETIME), CIEX1 = 'T00', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17008103'   


UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '25/02/2017', 103) + CAST('02:45' AS DATETIME), CIEX1 = 'S50.1', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17008104'
 
UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '06/03/2017', 103) + CAST('03:40' AS DATETIME), CIEX1 = 'S91.3', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17009420'
 

UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '06/03/2017', 103) + CAST('06:00' AS DATETIME), CIEX1 = 'S00', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17009419'
 

UPDATE EMERGENCIA SET DESTINO = '12', FECHA_SALIDA = CONVERT(DATETIME, '06/03/2017', 103) + CAST('04:00' AS DATETIME), CIEX1 = 'S01.9', TIPO_CIEX1 = 'D'
 WHERE EMERGENCIA_ID = '17009421'
 


UPDATE EMERGENCIA SET FECHA_SALIDA = CONVERT(DATETIME, '01/03/2017', 103) + CAST('10:39' AS DATETIME) WHERE EMERGENCIA_ID = '17008704'

UPDATE EMERGENCIA SET DESTINO = '04', observacion_egreso = 'REFERIDO LEY DE EMERGENCIA HOSPITAL HIPOLITO UNANUE', FECHA_SALIDA = CONVERT(DATETIME, '06/03/2017', 103) + CAST('06:17' AS DATETIME) WHERE EMERGENCIA_ID = '17009418'


SELECT * FROM DESTINO 


SELECT  FECHA_SALIDA FROM EMERGENCIA WHERE EMERGENCIA_ID = '16041655'   
SELECT CONVERT(DATETIME, '09/09/2015', 103) + CAST('03:30' AS DATETIME)

UPDATE EMERGENCIA SET FECHA_SALIDA = CONVERT(DATETIME, '09/09/2015', 103) + CAST('03:30' AS DATETIME) WHERE EMERGENCIA_ID = '15039158'   
SELECT  FECHA_SALIDA FROM EMERGENCIA WHERE EMERGENCIA_ID = '15039158'   

UPDATE EMERGENCIA SET DESTINO = '12', CIEX1 = 'T11.1', TIPO_CIEX1 = 'D',
  FECHA_SALIDA = CONVERT(DATETIME, '06/03/2017', 103) + CAST('03:30' AS DATETIME) WHERE EMERGENCIA_ID = '17009417'




SELECT CONVERT(DATETIME, '09/09/2015', 103) + CAST('03:30' AS DATETIME)
     
     
SELECT * FROM V_EMERGENCIA WHERE EMERGENCIA_ID = '16041655'

select * from ciex where CIEX = 'T06'

SELECT NOMBRE_MEDICO FROM V_EMERGENCIA WHERE EMERGENCIA_ID = '16041655'


SELECT nombre FROM ciex WHERE ciex = ?lcciex


/* OCHOA MENESES */
UPDATE EMERGENCIA SET FECHA_SALIDA = CONVERT(DATETIME, '09/09/2015', 103) + CAST('03:30' AS DATETIME) WHERE EMERGENCIA_ID = '15039158'   


SELECT * FROM USUARIO_WEB WHERE DNI = '44730374'
UPDATE USUARIO_WEB SET NOMBRES = 'TAFUR NAVARRO KATHERINE' WHERE DNI = '44730374'

SELECT * FROM USUARIO WHERE USUARIO = 'CTAFUR'


