/* PARA LOS TECNICOS PUEDEN VER A QUIEN ASIGNO MEDICOS */
USE SIGSALUD
/* correcto */
USE SIGSALUD
INSERT INTO [SIGSALUD].[dbo].[MEDICO] (MEDICO, NOMBRE, ACTIVO, EESS, COLEGIO, PROFESION, ESPECIALIDAD, CARGO, ABREVIATURA, CONSULTORIO, OLD, COLESP, DNI, firma, TIENE_FIRMA, CODHIS,
CONTRATO)
VALUES ('CSE','CANTARO SURICHAQUI ENMA IBETH',CONVERT(NUMERIC(3,0), 1),'0000005947', '0', '', '0041','', 'TEC', '2052','','0', '44561085', 'dn.jpg', '0', '0', '(NINGUNO)')

/* correcto */
USE SIGSALUD
INSERT INTO [SIGSALUD].[dbo].[MEDICO] (MEDICO, NOMBRE, ACTIVO, EESS, COLEGIO, PROFESION, ESPECIALIDAD, CARGO, ABREVIATURA, CONSULTORIO, OLD, COLESP, DNI, firma, TIENE_FIRMA, CODHIS,
CONTRATO)
VALUES ('CNH','CALDERON NOLASCO HENRY',CONVERT(NUMERIC(3,0), 1),'0000005947', '0', '', '0041','', 'TEC', '2052','','0', '40450578', 'dn.jpg', '0', '0', '(NINGUNO)')



/* DELETE FROM MEDICO WHERE MEDICO = 'CSE' */
SELECT * FROM medico WHERE MEDICO = 'CSE'
UNION ALL
SELECT * FROM medico WHERE MEDICO = 'CNH'