select  FICHAFAM,  
 COUNT(*) AS CUENTA 
 CASE 
 WHEN TIPOEDAD 'A' THEN 
 CASE 
  WHEN EDAD >=0 AND EDAD <=11 THEN '1'
  WHEN EDAD >=12 AND EDAD <=17 THEN '2'
  WHEN EDAD >=18 AND EDAD <=29 THEN '3'
  WHEN EDAD >=30 AND EDAD <=59  THEN '4'
  WHEN EDAD >=60 AND EDAD <=100 THEN '5' 
  END
  END
 
 from HIS  WHERE SEXO='M' and periodo='092015' 
 GROUP by FICHAFAM  ORDER BY FICHAFAM 


USE SIGSALUD
GO
SELECT * FROM HIS  WHERE SEXO='M' and periodo='092015' 

SELECT * FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'A' 

SELECT * FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'M' 

SELECT * FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'D' 


SELECT DIAGNOST1, COUNT(DIAGNOST1) as TOTALCIEX FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'A' 
        and EDAD between 20 and 24 AND DIAGNOST1 = 'D' OR DIAGNOST2 = 'D' OR DIAGNOST3 = 'D' OR DIAGNOST4 = 'D' OR DIAGNOST5 = 'D' OR DIAGNOST6 = 'D'
         GROUP BY DIAGNOST1, DIAGNOST2, DIAGNOST3, DIAGNOST4
         

SELECT COUNT(*) AS TOTAL  FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'A' 
        and EDAD between 20 and 24 AND (DIAGNOST1 = 'D' OR DIAGNOST2 = 'D' OR DIAGNOST3 = 'D' OR DIAGNOST4 = 'D' OR DIAGNOST5 = 'D' OR DIAGNOST6 = 'D')
        

SELECT COUNT(*) AS TOTAL  FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD NOT IN ('A') 
         AND (DIAGNOST1 = 'D' OR DIAGNOST2 = 'D' OR DIAGNOST3 = 'D' OR DIAGNOST4 = 'D' OR DIAGNOST5 = 'D' OR DIAGNOST6 = 'D')


SELECT COUNT(*) AS TOTAL  FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'D' 
         AND (DIAGNOST1 = 'D' OR DIAGNOST2 = 'D' OR DIAGNOST3 = 'D' OR DIAGNOST4 = 'D' OR DIAGNOST5 = 'D' OR DIAGNOST6 = 'D')




SELECT * FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'A' and EDAD between 20 and 24  ORDER BY CODIGO1 ASC

SELECT COUNT(edad) as cantidad FROM HIS  WHERE SEXO='M' and ANIO = '2015' AND MES = '7' AND TIPOEDAD = 'A' and EDAD between 25 and 29



COUNT(edad) for (BETWEEN(ledad,20, 24)
 COUNT(edad) for (BETWEEN(ledad,25, 29)
 
  COUNT(edad) for (BETWEEN(ledad,30, 34)
  
    COUNT(edad) for (BETWEEN(ledad,35, 39)
    
        COUNT(edad) for (BETWEEN(ledad,40, 44)
        
     COUNT(edad) for (BETWEEN(ledad,45, 49)
    COUNT(edad) for (BETWEEN(ledad,50, 54)
  COUNT(edad) for (BETWEEN(ledad,55, 59)
  
    COUNT(edad) for (BETWEEN(ledad,60,64)

 COUNT(edad) for (BETWEEN(ledad,65,150)
