use sigsalud 
  DECLARE @lfecha1 varchar(10) = '2016-01-01'
  DECLARE @lfecha2 varchar(10) = '2016-06-30'
 /*  SELECT * FROM V_EMERGENCIA WHERE FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101) ORDER BY FECHA ASC   */
  
  SELECT     dbo.EMERGENCIA.ESTADO, dbo.EMERGENCIA.EMERGENCIA_ID, dbo.EMERGENCIA.FECHA, dbo.EMERGENCIA.HORA, dbo.EMERGENCIA.ORDEN, 
                      dbo.EMERGENCIA.PACIENTE, dbo.PACIENTE.HISTORIA, dbo.EMERGENCIA.NOMBRES, dbo.EMERGENCIA.FECHA_NACIMIENTO, dbo.EMERGENCIA.SEXO, 
                      dbo.SEGURO.NOMBRE AS NOMBRE_SEGURO, dbo.CIEX.NOMBRE AS NOMBRE_DIAGNOSTICO, dbo.EMERGENCIA.CONSULTORIO, 
                      dbo.CONSULTORIO.NOMBRE AS NOMBRE_CONSULTORIO, dbo.EMERGENCIA.CUENTAID, dbo.EMERGENCIA.MOTIVO_EMERGENCIA, dbo.EMERGENCIA.USUARIO, 
                      dbo.MOTIVO_EMERGENCIA.NOMBRE AS NOMBRE_MOTIVO, dbo.EMERGENCIA.MEDICO, dbo.MEDICO.NOMBRE AS NOMBRE_MEDICO, 
                      dbo.EMERGENCIA.DIRECCION, dbo.EMERGENCIA.ESTADO_CIVIL, dbo.ESTADO_CIVIL.NOMBRE AS NOMBRE_ESTADOCIVIL, dbo.EMERGENCIA.DISTRITO, 
                      dbo.EMERGENCIA.DOCUMENTO, dbo.EMERGENCIA.DOCUMENTOA, dbo.EMERGENCIA.TELEFONO1, dbo.EMERGENCIA.TELEFONO2, 
                      dbo.EMERGENCIA.ACOMPANANTE, dbo.EMERGENCIA.PATERNO, dbo.EMERGENCIA.MATERNO, dbo.EMERGENCIA.NOMBRE AS NOMBRE_PACIENTE, 
                      dbo.EMERGENCIA.EDAD, dbo.EMERGENCIA.NOMBRE, dbo.SEXO.NOMBRE AS NOMBRE_SEXO, dbo.EMERGENCIA.SEGURO, dbo.EMERGENCIA.PRE_AFILIACION, 
                      dbo.EMERGENCIA.OBSERVACION1, dbo.EMERGENCIA.OBSERVACION2, dbo.EMERGENCIA.LOCALIDAD, dbo.LOCALIDAD.Nombre AS Nombre_Localidad, 
                      dbo.EMERGENCIA.CONSULTORIO1, dbo.EMERGENCIA.CIEX4, dbo.EMERGENCIA.MEDICO1, dbo.EMERGENCIA.ENTIDAD, dbo.EMERGENCIA.HORA_ATEN, 
                      dbo.EMERGENCIA.ESTABLECIMIENTO, dbo.EMERGENCIA.CONDICION_EGRESO, dbo.EMERGENCIA.FECHA_ING, dbo.EMERGENCIA.FECHA_SAL, 
                      dbo.EMERGENCIA.NUMCAMA, dbo.EMERGENCIA.HORA_ING, dbo.EMERGENCIA.HORA_SAL, dbo.EMERGENCIA.HORA_EST, dbo.EMERGENCIA.DESTINO, 
                      dbo.EMERGENCIA.CIEX3, dbo.EMERGENCIA.CIEX2, dbo.EMERGENCIA.CIEX1, dbo.EMERGENCIA.ESTANCIA, dbo.CONDICION_EGRESO.NOMBRE AS DESEGRESO, 
                      dbo.EMERGENCIA.TIPOATENCION, dbo.EMERGENCIA.PRIORIDAD, dbo.EMERGENCIA.MEDICO2, dbo.EMERGENCIA.CIEX5, dbo.EMERGENCIA.FECHA_ING1, 
                      dbo.EMERGENCIA.FECHA_SAL1, dbo.EMERGENCIA.NUMCAMA1, dbo.EMERGENCIA.HORA_ING1, dbo.EMERGENCIA.HORA_SAL1, dbo.EMERGENCIA.HORA_EST1, 
                      dbo.EMERGENCIA.CIEX6, dbo.EMERGENCIA.CIEX7, dbo.EMERGENCIA.CIEX8, dbo.EMERGENCIA.CIEX9, dbo.EMERGENCIA.RELIGION, 
                      dbo.RELIGION.NOMBRE AS DESRELIGION, dbo.EMERGENCIA.QUIEN_ATIENDE, dbo.EMERGENCIA.SEGUROLIQ, ESPECIALIDAD.NOMBRE
FROM         dbo.EMERGENCIA INNER JOIN
                      dbo.LOCALIDAD ON dbo.EMERGENCIA.LOCALIDAD = dbo.LOCALIDAD.Localidad INNER JOIN
                      dbo.CONDICION_EGRESO ON dbo.EMERGENCIA.CONDICION_EGRESO = dbo.CONDICION_EGRESO.CONDICION_EGRESO INNER JOIN
                      dbo.RELIGION ON dbo.EMERGENCIA.RELIGION = dbo.RELIGION.RELIGION LEFT OUTER JOIN
                      dbo.MEDICO ON dbo.EMERGENCIA.MEDICO = dbo.MEDICO.MEDICO LEFT OUTER JOIN
                      dbo.CONSULTORIO ON dbo.EMERGENCIA.CONSULTORIO = dbo.CONSULTORIO.CONSULTORIO LEFT OUTER JOIN
                      DBO.ESPECIALIDAD ON dbo.CONSULTORIO.ESPECIALIDAD = ESPECIALIDAD.ESPECIALIDAD LEFT OUTER JOIN
                      dbo.SEGURO ON dbo.EMERGENCIA.SEGURO = dbo.SEGURO.SEGURO LEFT OUTER JOIN
                      dbo.SEXO ON dbo.EMERGENCIA.SEXO = dbo.SEXO.SEXO LEFT OUTER JOIN
                      dbo.ESTADO_CIVIL ON dbo.EMERGENCIA.ESTADO_CIVIL = dbo.ESTADO_CIVIL.ESTADO_CIVIL LEFT OUTER JOIN
                      dbo.PACIENTE ON dbo.EMERGENCIA.PACIENTE = dbo.PACIENTE.PACIENTE LEFT OUTER JOIN
                      dbo.MOTIVO_EMERGENCIA ON dbo.EMERGENCIA.MOTIVO_EMERGENCIA = dbo.MOTIVO_EMERGENCIA.MOTIVO_EMERGENCIA LEFT OUTER JOIN
                      dbo.CIEX ON dbo.EMERGENCIA.CIEX1 = dbo.CIEX.CIEX
WHERE EMERGENCIA.FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101) ORDER BY EMERGENCIA.FECHA ASC   
 
 
  SELECT * FROM EMERGENCIA WHERE FECHA between CONVERT(datetime, @lfecha1,101) and CONVERT(datetime, @lfecha2,101) ORDER BY FECHA ASC


SELECT A.NOMBRE, B. NOMBRE FROM CONSULTORIO A LEFT JOIN ESPECIALIDAD B ON B.ESPECIALIDAD =  A.ESPECIALIDAD 

SELECT * FROM ESPECIALIDAD 
    
    
28904
    
    
    '2016-01-01'