/* REPORTE ALEXANDRA ESTADISTICA */

use sigsalud
DECLARE @lcfecha1 DATETIME = CONVERT(DATETIME, '2016-12-01', 101)
DECLARE @lcfecha2 DATETIME = CONVERT(DATETIME, '2016-12-31', 101)

SELECT 'MEDICINA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA SIS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
/** PARA SOAT **/
SELECT 'MEDICINA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA SOAT' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL 

/** PARA ESSALUD **/
SELECT 'MEDICINA ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  ESSALUD' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL
/** PARA MILITAR **/
SELECT 'MEDICINA MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  MILITAR' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL
/** OTROS  **/
SELECT 'MEDICINA OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  OTROS' AS CONCEPTO, COUNT(EMERGENCIA_ID) AS CONTAR FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 


/*
SELECT * FROM CONSULTORIO ORDER BY NOMBRE ASC
SELECT * FROM SEGURO ORDER BY NOMBRE ASC
'09', '05', '14', '16', '04', '13', '0', '08'
*/