/* volver a eliminar el fallecido, DE LA TABLA EMERGENCIA Y DEL DETALLE DE PROCEDIMIENTOS  */

declare @lidemergencia varchar(13) = '16021069'
select USUARIO_FN_VITALES, QUIEN_ATIENDE, ESTADO from EMERGENCIA WHERE EMERGENCIA_ID=@lidemergencia
SELECT  ID_EME_DET_WEB,PROFESIONAL,EMERGENCIA_ID,FECHA,HORA,FECHA_HORA_REG,TIPO_PROCESO,LUGAR,
	AHORA_PROFESIONAL,ESTADO FROM EMERGENCIA_DET_WEB WHERE EMERGENCIA_ID=@lidemergencia
	
 UPDATE EMERGENCIA SET USUARIO_FN_VITALES='', QUIEN_ATIENDE='', ESTADO=2 WHERE EMERGENCIA_ID=@lidemergencia 
 DELETE FROM EMERGENCIA_DET_WEB WHERE EMERGENCIA_ID=@lidemergencia

select USUARIO_FN_VITALES, QUIEN_ATIENDE, ESTADO from EMERGENCIA WHERE EMERGENCIA_ID=@lidemergencia
SELECT  ID_EME_DET_WEB,PROFESIONAL,EMERGENCIA_ID,FECHA,HORA,FECHA_HORA_REG,TIPO_PROCESO,LUGAR,
	AHORA_PROFESIONAL,ESTADO FROM EMERGENCIA_DET_WEB WHERE EMERGENCIA_ID=@lidemergencia