USE SIGSALUD

DECLARE @lcdni varchar(13) = '16036520'
SELECT ESTADO, MOTIVO_AUSENCIA, * from EMERGENCIA where EMERGENCIA_ID = @lcdni
 update EMERGENCIA set ESTADO = '2', MOTIVO_AUSENCIA = '' where EMERGENCIA_ID = @lcdni
SELECT ESTADO, MOTIVO_AUSENCIA, * from EMERGENCIA where EMERGENCIA_ID = @lcdni 