USE SIGSALUD

declare @lcfechainicio varchar(10) = '2017-03-01'
declare @lcfechafin    varchar(10)= '2017-03-31'

/* para emergencia */
truncate table [dbo].[EMER1]
INSERT INTO [dbo].[EMER1]([CONSULTORIO],[PROCE_MED_1],[PROCE_MED_2],[PROCE_MED_3])
SELECT CONSULTORIO, PROCE_MED_1, PROCE_MED_2, PROCE_MED_3 FROM EMERGENCIA WHERE FECHA BETWEEN CONVERT(DATETIME, @lcfechainicio, 101) AND  CONVERT(DATETIME, @lcfechafin, 101) 
AND PROCE_MED_1 <> '0'
UNION ALL
SELECT CONSULTORIO, PROCE_MED_1, PROCE_MED_2, PROCE_MED_3 FROM EMERGENCIA WHERE FECHA BETWEEN CONVERT(DATETIME, @lcfechainicio, 101) AND  CONVERT(DATETIME, @lcfechafin, 101) 
AND PROCE_MED_2 <> '0'
UNION ALL
SELECT CONSULTORIO, PROCE_MED_1, PROCE_MED_2, PROCE_MED_3 FROM EMERGENCIA WHERE FECHA BETWEEN CONVERT(DATETIME, @lcfechainicio, 101) AND  CONVERT(DATETIME, @lcfechafin, 101) 
AND PROCE_MED_3 <> '0'

SELECT CONSULTORIO, PROCE_MED_1, COUNT(PROCE_MED_1) CONTAR FROM EMER1 GROUP BY CONSULTORIO, PROCE_MED_1 ORDER BY CONSULTORIO ASC


declare @lcfechaprocesar varchar(6) = '032017'
/* para consultorio */

SELECT HSERVICIO, CODIGO1, COUNT(CODIGO1) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO1,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO1 
UNION ALL 
SELECT HSERVICIO, CODIGO2, COUNT(CODIGO2) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO2,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO2 
UNION ALL
SELECT HSERVICIO, CODIGO3, COUNT(CODIGO3) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO3,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO3 
UNION ALL
SELECT HSERVICIO, CODIGO4, COUNT(CODIGO4) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO4,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO4 
UNION ALL
SELECT HSERVICIO, CODIGO5, COUNT(CODIGO5) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO5,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO5 
UNION ALL
SELECT HSERVICIO, CODIGO6, COUNT(CODIGO6) AS COD FROM HIS  WHERE PERIODO = @lcfechaprocesar AND SUBSTRING(CODIGO6,1,1) = '9' 
GROUP BY HSERVICIO, CODIGO6 


/* Para Hospitalizacion */
declare @lcfechainicio varchar(10) = '2017-03-01'
declare @lcfechafin    varchar(10)= '2017-03-31'


SELECT CODIGOESPE12, PROCEDIM1, COUNT(PROCEDIM1) AS CONTAR FROM HOSPITALIZACION WHERE FECHA1 BETWEEN CONVERT(DATETIME, @lcfechainicio, 101) AND  CONVERT(DATETIME, @lcfechafin, 101) 
  AND PROCEDIM1 <> '0' GROUP BY CODIGOESPE12, PROCEDIM1
UNION ALL
SELECT CODIGOESPE12, PROCEDIM2, COUNT(PROCEDIM2) AS CONTAR FROM HOSPITALIZACION WHERE FECHA1 BETWEEN CONVERT(DATETIME, @lcfechainicio, 101) AND  CONVERT(DATETIME, @lcfechafin, 101) 
  AND PROCEDIM2 <> '0' GROUP BY CODIGOESPE12, PROCEDIM2

  /*
SELECT * FROM [dbo].[EMERGENCIA_PROC_WEB]

SELECT * FROM   [dbo].[EmergenciaDetalleProcedimiento]

SELECT * FROM [dbo].[EMERGENCIA_PROCE_ENF]
*/