DECLARE @V_DATE_FROM DATE = '01/07/2015'
DECLARE @V_DATE_TO DATE = '05/07/2015'

SELECT
T1.ORDEN,
CONVERT(VARCHAR(10), T1.FECHA, 103) FECHA,
T1.HORA,
ISNULL(T1.PATERNO + ' ' + T1.MATERNO + ' ' + T1.NOMBRE, '') PACIENTE,
T1.SEXO GENERO,
ISNULL(T1.PRIORIDAD, '') PRIORIDAD,
T2.NOMBRE SEGURO,
T1.DIRECCION + ',  ' + T3.NOMBRE  + ',  ' + T4.DISTRITO + ',  ' + T4.PROVINCIA DIRECCION,
T1.ACOMPANANTE,
T6.NOMBRE OCUPACION,
T7.NOMBRE MOTIVO_EMERGENCIA,
T8.NOMBRE DIAGNOSTICO,
CASE T1.TIPO_CIEX1
WHEN '0' THEN ''
ELSE T1.TIPO_CIEX1
END TIPO_DX,
CASE
WHEN T1.PRIORIDAD IN('Prioridad 1', 'Prioridad 2') THEN 'EMERGENCIA'
WHEN T1.PRIORIDAD IN('Prioridad 3', 'Prioridad 4') THEN 'URGENCIA'
ELSE T1.PRIORIDAD
END TIPO_ATENCION,
T1.TRATAMIENTO,
T9.NOMBRE DESTINO,
T11.NOMBRE + ',  ' + T10.NOMBRE DATOS_PROFESIONAL, T10.FIRMA
FROM EMERGENCIA T1
INNER JOIN SEGURO T2 ON T2.SEGURO = T1.SEGURO
LEFT JOIN LOCALIDAD T3 ON T3.LOCALIDAD = T1.LOCALIDAD 
LEFT JOIN UBIGEO T4 ON T4.UBIGEO = T1.DISTRITO
LEFT JOIN PACIENTE T5 ON T5.PACIENTE = T1.PACIENTE
LEFT JOIN OCUPACION T6 ON T6.OCUPACION = T5.OCUPACION
INNER JOIN MOTIVO_EMERGENCIA T7 ON T7.MOTIVO_EMERGENCIA = T1.MOTIVO_EMERGENCIA
INNER JOIN CIEX T8 ON T8.CIEX = T1.CIEX1
INNER JOIN DESTINO T9 ON T9.DESTINO = T1.DESTINO
INNER JOIN MEDICO T10 ON T10.MEDICO = T1.MEDICO
INNER JOIN ESPECIALIDAD T11 ON T11.ESPECIALIDAD = T10.ESPECIALIDAD
WHERE FECHA BETWEEN @V_DATE_FROM AND @V_DATE_TO
ORDER BY FECHA, HORA ASC