/* SELECCIONE LOS USUARIOS, CARGO, ESTADO, CLAVE PARA SISTEMA DE EMERGENCIA */

SELECT * FROM USUARIO_WEB ORDER BY NOMBRES ASC

SELECT * FROM USUARIO_WEB ORDER BY CARGO ASC

SELECT DNI, NOMBRES, CARGO, ESTADO, CLAVE FROM USUARIO_WEB WHERE NOMBRES LIKE '%MAITA VICENTE MARINO MOISES%'
SELECT DNI, NOMBRES, CARGO, ESTADO, CLAVE FROM USUARIO_WEB WHERE NOMBRES LIKE '%MAITA VICENTE PEDRO%'

SELECT DNI, NOMBRES, CARGO, ESTADO, CLAVE FROM USUARIO_WEB WHERE NOMBRES LIKE '%CHUYES TOLEDO REYNA%'
SELECT DNI, NOMBRES, CARGO, ESTADO, CLAVE FROM USUARIO_WEB WHERE NOMBRES LIKE '%CHACA LLANOS ELVIS ARTURO%'

SELECT DNI, NOMBRES, CARGO, ESTADO, CLAVE FROM USUARIO_WEB WHERE NOMBRES LIKE '%OBESO CAMONES%'
