

SELECT EMERGENCIA_ID, FECHA, CONVERT(varchar(10), fecha, 103) as nfecha,  HORA, TEMPERATURA, PRESION, PRESIOND, PULSO, FC, FR, SAT_OX, PESO, USUARIO_FN_VITALES, QUIEN_ATIENDE, MEDICO1 
FROM [SIGSALUD].[dbo].[EMERGENCIA]  WHERE EMERGENCIA_ID = '18004570'

UPDATE 

select CONVERT(datetime, '05/01/2018', 103)


update [SIGSALUD].[dbo].[EMERGENCIA] set USUARIO_FN_VITALES = '', QUIEN_ATIENDE = ''  WHERE EMERGENCIA_ID = '18004438'


  SELECT top 1 ID_EME_DET_WEB, CODIGO_PROFESIONAL, PROFESIONAL, EMERGENCIA_ID, AHORA_PROFESIONAL FROM [SIGSALUD].[dbo].[v_EMERGENCIA_DET_WEB]  WHERE EMERGENCIA_ID = '18004570'  AND TIPO_PROCESO = 'P06'   order by FECHA_HORA_REG desc 
  
SELECT top 1 ID_EME_DET_WEB, PROFESIONAL, B.NOMBRE AS ENFERMERA, AHORA_PROFESIONAL,  
FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB] A LEFT JOIN 
 [SIGSALUD].[dbo].[MEDICO]  B ON A.PROFESIONAL = B.MEDICO 
  WHERE EMERGENCIA_ID = '18004570'  AND TIPO_PROCESO = 'P06'   order by FECHA_HORA_REG desc   


  
    
SELECT * FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB]  
WHERE EMERGENCIA_ID = '18004570'  AND TIPO_PROCESO = 'P06'   order by FECHA_HORA_REG desc     
  

SELECT top 1 ID_EME_DET_WEB, PROFESIONAL, EMERGENCIA_ID, AHORA_PROFESIONAL FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB]  WHERE EMERGENCIA_ID = '18004438' AND TIPO_PROCESO = 'P06'
order by FECHA_HORA_REG desc



  
SELECT top 1 ID_EME_DET_WEB, PROFESIONAL, EMERGENCIA_ID, AHORA_PROFESIONAL FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB]  WHERE EMERGENCIA_ID = '18004438' AND TIPO_PROCESO = 'P06'
order by FECHA_HORA_REG desc

select NOMBRE from [SIGSALUD].[dbo].[MEDICO] 

update 
18012216


SELECT top 1 ID_EME_DET_WEB, PROFESIONAL, EMERGENCIA_ID, AHORA_PROFESIONAL FROM [SIGSALUD].[dbo].[v_EMERGENCIA_DET_WEB]  WHERE EMERGENCIA_ID = '18004438' AND TIPO_PROCESO = 'P06'
order by FECHA_HORA_REG desc


 SELECT top 1 ID_EME_DET_WEB, PROFESIONAL, EMERGENCIA_ID, AHORA_PROFESIONAL FROM [SIGSALUD].[dbo].[v_EMERGENCIA_DET_WEB]  WHERE EMERGENCIA_ID = '18004438' AND TIPO_PROCESO = 'P06'   order by FECHA_HORA_REG desc   
 

SELECT * FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB]  WHERE TIPO_PROCESO = 'P06'
 order by EMERGENCIA_ID desc


UPDATE [SIGSALUD].[dbo].[EMERGENCIA] SET TEMPERATURA = , PRESION = , PRESIOND = '', PULSO = '', FC = '', FR = '', SAT_OX = '', PESO = ''  WHERE EMERGENCIA_ID = ?
