/* Obtener Medicos */

USE SIGSALUD
TRUNCATE TABLE MEDICO_SIN_FIRMA
DROP TABLE MEDICOSF_TOTAL
INSERT INTO [SIGSALUD].[dbo].[MEDICO_SIN_FIRMA]
           ([MEDICO_SIN_FIRMA])
select MEDICO as MEDICO_EMERGENCIA from EMERGENCIA WHERE FECHA >= CONVERT(DATETIME, '2015-03-05', 101) group by MEDICO
UNION ALL
select MEDICO1 as MEDICO_EMERGENCIA from EMERGENCIA WHERE FECHA >= CONVERT(DATETIME, '2015-03-05', 101) group by medico1
UNION ALL
select quien_atiende as MEDICO_EMERGENCIA from EMERGENCIA WHERE FECHA >= CONVERT(DATETIME, '2015-03-05', 101) group by quien_atiende
DELETE FROM MEDICO_SIN_FIRMA WHERE LEN(MEDICO_SIN_FIRMA) <> 3
SELECT MEDICO, NOMBRE, DNI, ACTIVO, TIENE_FIRMA, ABREVIATURA  INTO MEDICOSF_TOTAL FROM MEDICO WHERE MEDICO IN (select DISTINCT MEDICO_SIN_FIRMA from MEDICO_SIN_FIRMA  ) 
SELECT MEDICO, NOMBRE, DNI, ACTIVO, TIENE_FIRMA, ABREVIATURA FROM MEDICOSF_TOTAL WHERE  ABREVIATURA = 'MED' 
AND tiene_firma = '0' AND ACTIVO = '1' AND SUBSTRING(DNI,1,3) <> '000'  AND MEDICO NOT IN ('YHS', 'YPJ', '') ORDER BY NOMBRE ASC



SELECT QUIEN_ATIENDE, COUNT(QUIEN_ATIENDE) AS CUENTA FROM EMERGENCIA WHERE QUIEN_ATIENDE IN (SELECT MEDICO FROM MEDICOSF_TOTAL WHERE  ABREVIATURA = 'MED' 
AND tiene_firma = '0' AND ACTIVO = '1' AND SUBSTRING(DNI,1,3) <> '000'  AND MEDICO NOT IN ('YHS', 'YPJ')) GROUP BY QUIEN_ATIENDE 



/* SELECT * FROM EMERGENCIA WHERE QUIEN_ATIENDE = DPJ' ORDER BY FECHA ASC */
 
