/* VER USUARIO MEDICO QUE ESTA DE TURNO */

USE SIGSALUD
/* ELECT QUIEN_ATIENDE FROM EMERGENCIA  ORDER BY FECHA DESC */
DECLARE @lmedico varchar(5)= 'sem'
SELECT MEDICO, NOMBRE, DNI, '' CLAVE FROM MEDICO WHERE MEDICO = @lmedico
UNION ALL
SELECT  @lmedico MEDICO, NOMBRES AS NOMBRE, DNI , CLAVE  FROM USUARIO_WEB WHERE DNI = (SELECT DNI FROM MEDICO WHERE MEDICO = @lmedico)


