/* VER : MEDICO, ENFERMERA DE TURNO */

USE SIGSALUD
DECLARE @LCFECHA1 VARCHAR(12) = '2016-10-17'
DECLARE @LCFECHA2 VARCHAR(12) = '2016-10-17'

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'turno_medico')
	BEGIN
		DROP TABLE turno_medico   
	END
select medico into turno_medico from EMERGENCIA WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) group by MEDICO
ALTER TABLE turno_medico alter column medico varchar(10);
ALTER TABLE turno_medico add fecha_expiracion varchar(50);
INSERT INTO [SIGSALUD].[dbo].[turno_medico]
           ([medico])
(select MEDICO1 as medico from EMERGENCIA WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) and medico1 is not null group by MEDICO1 
union all
select QUIEN_ATIENDE as medico from EMERGENCIA WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) and QUIEN_ATIENDE is not null  group by QUIEN_ATIENDE)
union all
select PROFESIONAL as medico from  dbo.EMERGENCIA_DET_WEB where FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101)

select A.MEDICO, A.NOMBRE, A.ABREVIATURA, A.DNI, B.CLAVE, UPPER(A.NOMBRE_ESPECIALIDAD) AS ESPECIALIDAD, 
CASE WHEN A.TIENE_FIRMA = '1' THEN 'TIENE FIRMA' ELSE '--- NO TIENE FIRMA---' END AS TIENE_FIRMA, B.FECHA_EXPIRACION from V_MEDICO A 
LEFT JOIN USUARIO_WEB B ON B.DNI = A.DNI  where A.MEDICO  in (select distinct MEDICO from [SIGSALUD].[dbo].[turno_medico] where MEDICO <> '0') and A.ABREVIATURA IN ('MED', 'OBS')
order by A.ABREVIATURA,  a.NOMBRE asc


select A.MEDICO, A.NOMBRE, A.ABREVIATURA, A.DNI, B.CLAVE, UPPER(A.NOMBRE_ESPECIALIDAD) AS ESPECIALIDAD, 
CASE WHEN A.TIENE_FIRMA = '1' THEN 'TIENE FIRMA' ELSE '--- NO TIENE FIRMA---'  END AS TIENE_FIRMA,  B.FECHA_EXPIRACION from V_MEDICO A 
LEFT JOIN USUARIO_WEB B ON B.DNI = A.DNI  where A.MEDICO  in (SELECT PROFESIONAL FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB] 
        WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) GROUP BY PROFESIONAL) and A.ABREVIATURA = 'ENF' 
        ORDER BY A.NOMBRE ASC
        

select A.MEDICO, A.NOMBRE, A.ABREVIATURA, A.DNI, B.CLAVE, UPPER(A.NOMBRE_ESPECIALIDAD) AS ESPECIALIDAD, 
CASE WHEN A.TIENE_FIRMA = '1' THEN 'TIENE FIRMA' ELSE '--- NO TIENE FIRMA---'  END AS TIENE_FIRMA,  B.FECHA_EXPIRACION from V_MEDICO A 
LEFT JOIN USUARIO_WEB B ON B.DNI = A.DNI  where A.MEDICO  in (SELECT PROFESIONAL FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB] 
        WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) GROUP BY PROFESIONAL) and A.ABREVIATURA = 'TEC'
order by a.NOMBRE asc        


select A.MEDICO, A.NOMBRE, A.ABREVIATURA, A.DNI, B.CLAVE, UPPER(A.NOMBRE_ESPECIALIDAD) AS ESPECIALIDAD, 
CASE WHEN A.TIENE_FIRMA = '1' THEN 'TIENE FIRMA' ELSE '--- NO TIENE FIRMA---'  END AS TIENE_FIRMA,  B.FECHA_EXPIRACION from V_MEDICO A 
LEFT JOIN USUARIO_WEB B ON B.DNI = A.DNI  where A.MEDICO  in (SELECT PROFESIONAL FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB] 
        WHERE FECHA between CONVERT(DATETIME, @lcfecha1, 101) and CONVERT(DATETIME, @lcfecha2, 101) GROUP BY PROFESIONAL) and A.ABREVIATURA = 'OBS'
order by a.NOMBRE asc        