

DECLARE @lanio INT = 2015

SELECT 'PRIORIDAD 1' AS PRIORIDAD, COUNT(Prioridad) AS TOTAL FROM EMERGENCIA WHERE YEAR(FECHA) = @lanio AND PRIORIDAD = 'Prioridad 1'
UNION ALL
SELECT 'PRIORIDAD 2' AS PRIORIDAD, COUNT(Prioridad) AS TOTAL FROM EMERGENCIA WHERE YEAR(FECHA) = @lanio AND PRIORIDAD = 'Prioridad 2'
UNION ALL
SELECT 'PRIORIDAD 3' AS PRIORIDAD, COUNT(Prioridad) AS TOTAL FROM EMERGENCIA WHERE YEAR(FECHA) = @lanio AND PRIORIDAD = 'Prioridad 3'
UNION ALL
SELECT 'PRIORIDAD 4' AS PRIORIDAD, COUNT(Prioridad) AS TOTAL FROM EMERGENCIA WHERE YEAR(FECHA) = @lanio AND PRIORIDAD = 'Prioridad 4'

