use SIGSALUD
select estado, * from EMERGENCIA where EMERGENCIA_ID = '16020732'


update EMERGENCIA set ESTADO = '3' where EMERGENCIA_ID = '16020732'
update EMERGENCIA set ESTADO = '3' where EMERGENCIA_ID = '16020733'


SELECT * FROM MEDICO WHERE MEDICO = 'THW'