


SELECT MEDICO1, MEDICO, QUIEN_ATIENDE FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'

SELECT * FROM [SIGSALUD].[dbo].[V_EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'

SELECT * FROM [SIGSALUD].[dbo].[TMP_EMER_REPARAR] WHERE EMERGENCIA_ID = '18007315'

[SIGSALUD].[dbo].[TMP_EMER_REPARAR]


        declare @lfecha1 datetime = convert(datetime, '2018-02-01', 101)
        declare @lfecha2 datetime = convert(datetime, '2018-02-28', 101)
        
--        TRUNCATE TABLE  [SIGSALUD].[dbo].[TMP_EMER_REPARAR]
        SELECT EMERGENCIA_ID, FECHA, NOMBRES, ESTADO, PACIENTE, HISTORIA, NOMBRE_SEGURO, NOMBRE_CONSULTORIO, OBSERVACION1, NOMBRE_MEDICO 
              FROM [SIGSALUD].[dbo].[V_EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'
              
       Select * FROM [SIGSALUD].[dbo].[V_UTILIZAR_HC_EMER_WEB] WHERE EMERGENCIA_ID = '18007315'
       Select * FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB] WHERE EMERGENCIA_ID = '18007315'
                     
              --  WHERE EMERGENCIA_ID NOT IN ('89000002', '89000001') AND FECHA between  @lfecha1 and @lfecha2 and estado <> '0' ORDER BY EMERGENCIA_ID DESC


SELECT     EM.ESTADO, EM.EMERGENCIA_ID, EM.FECHA, EM.HORA, EM.ORDEN, EM.PACIENTE, PA.HISTORIA, EM.NOMBRES, OCU.NOMBRE AS OCUPACION, 
                      EM.FECHA_NACIMIENTO, EM.SEXO, SEG.NOMBRE AS NOMBRE_SEGURO, EM.CIEX1, CX.NOMBRE AS NOMBRE_DIAGNOSTICO1, EM.CIEX2, 
                      CX2.NOMBRE AS NOMBRE_DIAGNOSTICO2, EM.CIEX3, CX3.NOMBRE AS NOMBRE_DIAGNOSTICO3, EM.CIEX4, CX4.NOMBRE AS NOMBRE_DIAGNOSTICO4, 
                      EM.CIEX5, CX5.NOMBRE AS NOMBRE_DIAGNOSTICO5, EM.CIEX6, CX6.NOMBRE AS NOMBRE_DIAGNOSTICO6, EM.CONSULTORIO, 
                      CON.NOMBRE AS NOMBRE_CONSULTORIO, EM.CUENTAID, EM.MOTIVO_EMERGENCIA, EM.USUARIO AS USUARIO_ADMISION, ME.NOMBRE AS NOMBRE_MOTIVO, 
                      MED3.MEDICO, MED3.NOMBRE AS NOMBRE_MEDICO, EM.DIRECCION, EM.ESTADO_CIVIL, EC.NOMBRE AS NOMBRE_ESTADOCIVIL, EM.DISTRITO, 
                      EM.DOCUMENTO, EM.DOCUMENTOA, EM.TELEFONO1, EM.TELEFONO2, EM.ACOMPANANTE, EM.PATERNO, EM.MATERNO, EM.NOMBRE AS NOMBRE_PACIENTE, 
                      EM.EDAD, SEX.NOMBRE AS NOMBRE_SEXO, EM.SEGURO, EM.PRE_AFILIACION, EM.OBSERVACION1, EM.OBSERVACION2, EM.LOCALIDAD, 
                      LOC.Nombre AS NOMBRE_LOCALIDAD, EM.CONSULTORIO1, EM.TIPOATENCION, EM.PRIORIDAD, EM.TEMPERATURA, EM.PRESION, EM.PULSO, EM.FR, EM.FC, 
                      EM.SAT_OX, MED.ABREVIATURA + '.' + UW.NOMBRES AS USUARIO_FN_VITALES, EM.EXAMEN_FISICO, EM.RELATO, EM.EVOLUCION, EM.SINTOMAS, 
                      EM.TRATAMIENTO, EM.TIPO_CIEX1, EM.TIPO_CIEX2, EM.TIPO_CIEX3, EM.TIPO_CIEX4, EM.TIPO_CIEX5, EM.TIPO_CIEX6, EM.HORA_ATEN, EM.PESO, EM.HORA_SAL, 
                      EM.FECHA_SAL, DS.NOMBRE AS DESTINO, EM.MEDICO AS MEDICO_SALIDA, MED2.NOMBRE AS NOMBRE_MEDICO_SALIDA, 
                      MED4.ABREVIATURA + ' ' + MED4.NOMBRE AS USUARIO_ALTA_ENF, EM.FECHA_HORA_ALTA_ENF, EM.PRESIOND, EL.DESCRIPCION AS ESTADO_PACIENTE, 
                      EM.FECHA_ATENCION, EM.ESTABLECIMIENTO, R.NOMBRE AS DESRELIGION, EM.QUIEN_ATIENDE, EM.HORAINICIOATENCION
FROM         dbo.EMERGENCIA AS EM LEFT OUTER JOIN
                      dbo.MEDICO AS MEDX ON EM.USUARIO_FN_VITALES = MEDX.MEDICO   LEFT OUTER JOIN
                      dbo.USUARIO_WEB AS UW ON MEDX.DNI = UW.DNI LEFT OUTER JOIN
                      dbo.MEDICO AS MED ON UW.DNI = MED.DNI INNER JOIN
                      dbo.SEGURO AS SEG ON EM.SEGURO = SEG.SEGURO INNER JOIN
                      dbo.CIEX AS CX ON EM.CIEX1 = CX.CIEX INNER JOIN
                      dbo.CONSULTORIO AS CON ON EM.CONSULTORIO = CON.CONSULTORIO INNER JOIN
                      dbo.MOTIVO_EMERGENCIA AS ME ON EM.MOTIVO_EMERGENCIA = ME.MOTIVO_EMERGENCIA INNER JOIN
                      dbo.MEDICO AS MED2 ON EM.MEDICO = MED2.MEDICO INNER JOIN
                      dbo.ESTADO_CIVIL AS EC ON EM.ESTADO_CIVIL = EC.ESTADO_CIVIL INNER JOIN
                      dbo.SEXO AS SEX ON EM.SEXO = SEX.SEXO INNER JOIN
                      dbo.LOCALIDAD AS LOC ON EM.LOCALIDAD = LOC.Localidad LEFT OUTER JOIN
                      dbo.PACIENTE AS PA ON EM.PACIENTE = PA.PACIENTE INNER JOIN
                      dbo.CIEX AS CX2 ON EM.CIEX2 = CX2.CIEX INNER JOIN
                      dbo.CIEX AS CX3 ON EM.CIEX3 = CX3.CIEX INNER JOIN
                      dbo.CIEX AS CX4 ON EM.CIEX4 = CX4.CIEX INNER JOIN
                      dbo.CIEX AS CX5 ON EM.CIEX5 = CX5.CIEX INNER JOIN
                      dbo.CIEX AS CX6 ON EM.CIEX6 = CX6.CIEX INNER JOIN
                      dbo.DESTINO AS DS ON EM.DESTINO = DS.DESTINO INNER JOIN
                      dbo.MEDICO AS MED3 ON EM.MEDICO1 = MED3.MEDICO LEFT OUTER JOIN
                      dbo.MEDICO AS MED4 ON EM.USUARIO_ALTA_ENF = MED4.DNI LEFT OUTER JOIN
                      dbo.EMERGENCIA_LUGAR_WEB AS EL ON EM.ESTADO_PACIENTE = EL.LUGAR INNER JOIN
                      dbo.RELIGION AS R ON R.RELIGION = EM.RELIGION INNER JOIN
                      dbo.OCUPACION AS OCU ON PA.OCUPACION = OCU.OCUPACION 
                      WHERE EM.EMERGENCIA_ID = '18005473'
                      
SELECT CIEX1, CIEX2, CIEX3, CIEX4, CIEX5, CIEX6 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia

declare @lidemergencia varchar(13) = '18005270'

SELECT CASE WHEN CIEX = '' THEN 'ERROR CIEX1' END AS  VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX1 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)


UNION ALL
SELECT 'ERROR DE CIEX2' AS VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX2 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE CIEX3' AS VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX3 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE CIEX4' AS VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX4 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE CIEX5' AS VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX5 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE CIEX6' AS VER_ERROR FROM [SIGSALUD].[dbo].[CIEX] WHERE CIEX IN (SELECT CIEX6 FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE COLUMNA MEDICO' AS VER_ERROR FROM [SIGSALUD].[dbo].[MEDICO] WHERE MEDICO IN (SELECT USUARIO_FN_VITALES FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE SEGURO' AS VER_ERROR FROM [SIGSALUD].[dbo].[SEGURO] WHERE SEGURO IN (SELECT SEGURO  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE CONSULTORIO' AS VER_ERROR FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE CONSULTORIO IN (SELECT CONSULTORIO  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE MOTIVO EMERGENCIA' AS VER_ERROR FROM [SIGSALUD].[dbo].[MOTIVO_EMERGENCIA] WHERE MOTIVO_EMERGENCIA IN (SELECT MOTIVO_EMERGENCIA  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE TIPO DE DESTINO' AS VER_ERROR FROM [SIGSALUD].[dbo].[DESTINO] WHERE DESTINO  IN (SELECT DESTINO  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE MEDICO1' AS VER_ERROR FROM [SIGSALUD].[dbo].[MEDICO] WHERE MEDICO IN (SELECT MEDICO1  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE USUARIO_ALTA_ENFERMERA' AS VER_ERROR FROM [SIGSALUD].[dbo].[MEDICO] WHERE MEDICO IN (SELECT USUARIO_ALTA_ENF  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE LUGAR EMERGENCIA' AS VER_ERROR FROM [SIGSALUD].[dbo].[EMERGENCIA_LUGAR_WEB] WHERE LUGAR IN (SELECT ESTADO_PACIENTE  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE RELIGION' AS VER_ERROR FROM [SIGSALUD].[dbo].[RELIGION] WHERE RELIGION IN (SELECT RELIGION FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)
UNION ALL
SELECT 'ERROR DE TIPO OCUPACION' AS VER_ERROR FROM [SIGSALUD].[dbo].[OCUPACION] WHERE OCUPACION IN (SELECT OCUPACION FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = @lidemergencia)


SELECT * FROM [SIGSALUD].[dbo].[MEDICO] WHERE MEDICO = 'Mqr'

SELECT medico, nombre FROM [SIGSALUD].[dbo].[MEDICO] order by NOMBRE

SELECT * FROM [SIGSALUD].[dbo].[MEDICO] ORDER BY MEDICO

SELECT MEDICO FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'  
SELECT * FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'  
SELECT * FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'  

SELECT NOMBRES, MEDICO, MEDICO1, QUIEN_ATIENDE,MEDICO_CODIGO_GINE, USUARIO_ALTA_ENF, USUARIO_ANT_OBSTETRICIA, USUARIO_FN_VITALES, USUARIO_EXAMEN_OBSTETRICO  
FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'  

SELECT *  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '18007315'  





                      
                      
                                    

