
SELECT * FROM [SIGSALUD].[dbo].[CUENTA] WHERE CUENTAID='1801731' 
SELECT * FROM [SIGSALUD].[dbo].[CUENTADET] WHERE CUENTAID='1801731' 



SELECT * FROM [SIGSALUD].[dbo].[CUENTA] WHERE CUENTAID='1803394' 
SELECT * FROM [SIGSALUD].[dbo].[CUENTADET] WHERE CUENTAID='1803394' 



SELECT * FROM [SIGSALUD].[dbo].[CUENTA] WHERE CUENTAID='1801731' 

UNION ALL
SELECT * FROM [SIGSALUD].[dbo].[CUENTA] WHERE CUENTAID='1803394' 


UPDATE [SIGSALUD].[dbo].[CUENTA] SET IMPORTE = NULL WHERE CUENTAID='1801731' 


SELECT * FROM [SIGSALUD].[dbo].[CUENTA] WHERE FECHA_APERTURA >= CONVERT(DATETIME, '2018-01-04', 101) AND IMPORTE IS NULL 

UPDATE [SIGSALUD].[dbo].[CUENTA] SET IMPORTE = 0, CARGO = 0, DESCUENTO = 0, ABONO = 0 WHERE FECHA_APERTURA >= CONVERT(DATETIME, '2018-01-04', 101) AND IMPORTE IS NULL 


