USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMPHCPACI]    Script Date: 06/28/2016 14:35:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMPHCPACI](
	[PACIENTE] [char](10) NOT NULL,
	[HISTORIA] [char](20) NOT NULL,
	[NOMBRES] [char](90) NOT NULL,
	[FECHA_APERTURA] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


