USE SIGSALUD
select ESTADO, FECHA, historia, NOMBRES, NOMBRE_CONSULTORIO, NOMBRE_MEDICO, NOMBRE_SEGURO, FECHA_SALIDA, HORA_SALIDA, FECHA_RETORNO, HORA_RETORNO, upper(NOMBRES) CONDICION,
EST_PAC, USUARIOS from V_ARCHIVOMOV where FECHA BETWEEN CONVERT(datetime, '2016-07-01', 101) AND CONVERT(datetime, '2016-07-11', 101) and ESTADO = '3' ORDER BY
NOMBRE_CONSULTORIO, FECHA  ASC



select ESTADO, FECHA, historia, NOMBRES, NOMBRE_CONSULTORIO, NOMBRE_MEDICO, NOMBRE_SEGURO, FECHA_SALIDA, HORA_SALIDA, FECHA_RETORNO, HORA_RETORNO, upper(NOMBRES) CONDICION,
EST_PAC, USUARIOS from ARCHIVO_MOV where FECHA BETWEEN CONVERT(datetime, '2015-10-30', 101) AND CONVERT(datetime, '2015-10-30', 101) and ESTADO = '2' ORDER BY
NOMBRE_CONSULTORIO, FECHA  ASC 




USE SIGSALUD
select ESTADO, NOMBRE_CONSULTORIO, FECHA, historia, NOMBRES, NOMBRE_MEDICO, NOMBRE_SEGURO, FECHA_SALIDA, HORA_SALIDA, FECHA_RETORNO, HORA_RETORNO, upper(NOMBRE) CONDICION,
EST_PAC, USUARIOS from V_ARCHIVOMOV where FECHA BETWEEN CONVERT(datetime, '2015-01-01', 101) AND CONVERT(datetime, '2015-10-31', 101) and ESTADO = '2' ORDER BY
NOMBRE_CONSULTORIO, FECHA  ASC