/* VER LAS HISTORIAS CLINICAS QUE NO TUVIERON MOVIMIENTO */

/*
TRUNCATE TABLE [SIGSALUD].[dbo].[TMPHCPACI]
INSERT INTO [SIGSALUD].[dbo].[TMPHCPACI]([PACIENTE],[HISTORIA],[NOMBRES],[FECHA_APERTURA])
 SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA FROM PACIENTE where YEAR(fecha_apertura) = 2015 AND MONTH(fecha_apertura) = 1
SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA FROM [SIGSALUD].[dbo].[TMPHCPACI]

SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA FROM PACIENTE where YEAR(fecha_apertura) = 2014 AND MONTH(fecha_apertura) = 1 AND day(fecha_apertura) between 1 AND 2
*/

declare @lpaci varchar(13) = '2015246073'
SELECT PACIENTE, HISTORIA, NOMBRES  FROM PACIENTE WHERE PACIENTE = @lpaci
SELECT * FROM EMERGENCIA WHERE PACIENTE = @lpaci
SELECT * FROM ATENCIONC WHERE PACIENTE = @lpaci
select PACIENTE from HOSPITALIZACION WHERE PACIENTE = @lpaci


declare @lanio int = 2015
declare @lmes int = 2
TRUNCATE TABLE [SIGSALUD].[dbo].[TMPHCPACI]
INSERT INTO [SIGSALUD].[dbo].[TMPHCPACI]([PACIENTE],[HISTORIA],[NOMBRES],[FECHA_APERTURA])
   SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA FROM PACIENTE where YEAR(fecha_apertura) = @lanio AND MONTH(fecha_apertura) = @lmes
  SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA FROM [SIGSALUD].[dbo].[TMPHCPACI]
