 SELECT CODACT, b.nombre FROM [BDPERSONAL].[dbo].[ASISTENCIA] A
     left join [BDPERSONAL].[dbo].[MAESTRO] b on b.CODIGO = a.CODIGO 
        WHERE a.CODACT NOT IN ('V', 'D', 'D.', 'DM', '', 'M4')  AND a.CODIGO in (SELECT CODIGO FROM [BDPERSONAL].[dbo].[MAESTRO] 
           WHERE DNI in  (SELECT DNI FROM [SIGSALUD].[dbo].[USUARIO] WHERE USUARIO in (SELECT usuario FROM [SIGSALUD].[dbo].[ARCHIVO_PARAMETRO] WHERE CONSULTORIO = '5080')))
           AND CONVERT(DATETIME, CONVERT(VARCHAR(4), AÑO) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), MES), 2) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), DIA),2), 101) BETWEEN
           
          
          
       
       
SELECT CONVERT(DATETIME, CONVERT(VARCHAR(4), AÑO) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), MES), 2) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), DIA),2), 101)  FROM ASISTENCIA       

 
 DECLARE @LCNOMBRE VARCHAR(100) = 'ROJAS'
 SELECT CODIGO AS ID, 'MAESTRO' AS UNIDAD, DNI, NOMBRE FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE NOMBRE LIKE '%' + @LCNOMBRE + '%'
 UNION ALL 
 SELECT USUARIO AS ID, 'USUARIO' AS UNIDAD, DNI, NOMBRE FROM [SIGSALUD].[dbo].[USUARIO] WHERE NOMBRE LIKE '%' + @LCNOMBRE + '%'
 
 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO] SET DNI = '46248959' WHERE CODIGO = '084676'
 UPDATE [SIGSALUD].[dbo].[USUARIO] SET DNI = '07658644' WHERE USUARIO = 'JSANTOSP'
 
 SELECT USUARIO, NOMBRE  FROM dbo.ARCHIVO_PARAMETRO GROUP BY USUARIO, NOMBRE
 use sigsalud	
 SELECT * FROM CONSULTORIO ORDER BY NOMBRE ASC
 
SELECT NOMBRE FROM USUARIO WHERE USUARIO IN (SELECT USUARIO  FROM dbo.ARCHIVO_PARAMETRO WHERE CONSULTORIO = '5060' AND USUARIO NOT IN ('SUPERVISOR', 'AJARA'))

select ID_CITA, TURNO, ESTADO, CONSULTORIO, NOMBRE_CONSULTORIO, FECHA, historia, NOMBRES, NOMBRE_MEDICO, NOMBRE_SEGURO, FECHA_SALIDA, HORA_SALIDA, FECHA_RETORNO, HORA_RETORNO, upper(NOMBRE) CONDICION,
    EST_PAC, USUARIOS from V_ARCHIVOMOV
    
    
    
    
 SELECT CODACT, b.nombre FROM [BDPERSONAL].[dbo].[ASISTENCIA] A
     left join [BDPERSONAL].[dbo].[MAESTRO] b on b.CODIGO = a.CODIGO 
        WHERE a.CODACT NOT IN ('V', 'D', 'D.', 'DM', '', 'M4')  AND a.CODIGO in (SELECT CODIGO FROM [BDPERSONAL].[dbo].[MAESTRO] 
           WHERE DNI in  (SELECT DNI FROM [SIGSALUD].[dbo].[USUARIO] WHERE USUARIO in (SELECT usuario FROM [SIGSALUD].[dbo].[ARCHIVO_PARAMETRO] WHERE CONSULTORIO = '5020')))
           AND CONVERT(DATETIME, CONVERT(VARCHAR(4), AÑO) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), MES), 2) + '-' + RIGHT('00' + CONVERT(VARCHAR(2), DIA),2), 101) = CONVERT(datetime, '2016-08-11', 101)
           
use BDPERSONAL           
select * from MAESTRO where NOMBRE like 'carrasco%'     

select * from ASISTENCIA where CODIGO = '084223'      and AÑO = 2016 and MES = 8 and DIA = 11
               