USE SIGSALUD

/* BUSCAR EN EMEGENCIA */

select ID_CITA, HISTORIA, ESTADO, NOMBRES, FECHA, ORIGEN, FECHA_SAL, HORA_SAL, FECHA_ING, HORA_ING from ARCHIVO_MOV where NOMBRES like 'CASIMIRO%' order by FECHA desc 

SELECT FECHA_PAGO, HORA, TURNO, NOMBRE_CONSULTORIO, NOMBRE_MEDICO, NOMBRE_SEGURO, usuarios FROM V_ARCHIVOMOV WHERE ID_CITA = '140158807'

select ESTADO from ARCHIVO_MOV GROUP BY ESTADO 



SELECT * FROM V_EMERGENCIA WHERE NOMBRES LIKE 'casimiro marro%' order by fecha desc
SELECT ESTADO, emergencia_id, FECHA, HORA, historia, NOMBRES, NOMBRE_SEGURO, NOMBRE_DIAGNOSTICO, NOMBRE_CONSULTORIO, * FROM v_EMERGENCIA WHERE NOMBRES LIKE 'OBESO CAMO%'

select estado, NRO_ATENCION, CONSULTORIO, FECHA_ATENCION from V_ATENCION_SEGURO where HISTORIA = '0145228' order by FECHA_ATENCION desc

select FECHA, HORA, * from EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16004866'

select AHORA_PROFESIONAL, LUGAR, substring(detalle,1,220) as deta from V_EMERGENCIA_DET_WEB where EMERGENCIA_ID = '16004866'

SELECT CASE WHEN ESTADOH IS NULL THEN 'NULO' ELSE ESTADOH END AS ESTADO_FINAL, PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA, FECHA_NACIMIENTO, DOCUMENTO,*
 FROM PACIENTE  WHERE NOMBRES LIKE 'OBESO CAMO%'


use SIGSALUD
select * from ARCHIVO_MOV where NOMBRES like 'obeso%'
select * from ARCHIVO_MOV order by fecha asc



         SELECT PACIENTE, HISTORIA, NOMBRES, FECHA_APERTURA, FECHA_NACIMIENTO, DOCUMENTO 
            FROM PACIENTE WHERE HISTORIA LIKE '%' + '0000174' + '%'




SELECT * FROM ORDENC

SELECT * FROM PACIENTE WHERE PACIENTE = '2008138384'
SELECT * FROM ATENCIONC  WHERE PACIENTE = '2008138384'

SELECT * FROM ARCHIVO_MOV WHERE PACIENTE = '2008138384'
SELECT * FROM CITA WHERE PACIENTE = '2008138384'
SELECT * FROM V_PAGOC WHERE PACIENTE = '2008138384' ORDER BY FECHA DESC
SELECT * FROM V_PAGOD WHERE PAGOID = '16108806'

SELECT * FROM EMERGENCIA WHERE PACIENTE = '2008138384' ORDER BY FECHA DESC
SELECT * FROM V_HOSPITALIZACION  WHERE PACIENTE = '2008138384'


SELECT ESTADOH FROM PACIENTE GROUP BY ESTADOH 


SELECT ESTADO_HISTO FROM PACIENTE GROUP BY ESTADO_HISTO



select * from CITA order by FECHA desc