

SELECT CONVERT(VARCHAR(4), AÑO) + '-' +  RIGHT('00' +  CONVERT(VARCHAR(2), MES),2) + '-' + RIGHT('00' +  CONVERT(VARCHAR(2), DIA),2) AS FECHA_PROGRAMACION,
CODACT, HORAI, HORAS FROM [BDPERSONAL].[dbo].[ASISTENCIA]
WHERE CODIGO = '084076' AND MES = 1 AND AÑO = 2018 AND CODACT <> 'D'
ORDER BY DIA 



