USE SIGSALUD
ALTER TABLE HIS ALTER COLUMN CODIGO1 CHAR(10)
ALTER TABLE HIS ALTER COLUMN CODIGO2 CHAR(10)
ALTER TABLE HIS ALTER COLUMN CODIGO3 CHAR(10)
ALTER TABLE HIS ALTER COLUMN CODIGO4 CHAR(10)
ALTER TABLE HIS ALTER COLUMN CODIGO5 CHAR(10)
ALTER TABLE HIS ALTER COLUMN CODIGO6 CHAR(10)



USE HISR
ALTER TABLE HIS ALTER COLUMN COD1 VARCHAR(10)
ALTER TABLE HIS ALTER COLUMN COD2 VARCHAR(10)
ALTER TABLE HIS ALTER COLUMN COD3 VARCHAR(10)


ALTER TABLE HIS ALTER COLUMN COD4 VARCHAR(10)
ALTER TABLE HIS ALTER COLUMN COD5 VARCHAR(10)
ALTER TABLE HIS ALTER COLUMN COD6 VARCHAR(10)
USE HISR
ALTER TABLE HIS_DX ALTER COLUMN DX CHAR(10)



