

use SIGSALUD
select * from ATENCIONC where FECHA = CONVERT(DATETIME, '2015-12-01', 101) AND NOMCONSULTORIO = 'REHABILITACION TERAPIA'
/* UPDATE ATENCIONC SET TIPO_CITA = 'C' where FECHA = CONVERT(DATETIME, '2015-12-01', 101) AND NOMCONSULTORIO = 'REHABILITACION TERAPIA'  */


' REHABILITACION TERAPIA '
' 302201
' 14128375209

select * from ATENCIONC where NOMBRES like 'CORTABRAZO NAVARRO%' AND FECHA = CONVERT(DATETIME, '2015-12-01', 101) ORDER BY FECHA ASC

' 375
'
SELECT * FROM HIS WHERE PERIODO = '122015' AND HSERVICIO LIKE 'REHABILITACION TERAPIA' ORDER BY ANIO, MES, DIA ASC

select * from ATENCIONC where FECHA = CONVERT(DATETIME, '2015-12-01', 101)  AND NOMBRES like 'CORTABRAZO NAVARRO LUZ%'  ORDER BY FECHA DESC
select * from ATENCIONC where  FECHA >= CONVERT(DATETIME, '2015-12-01', 101) AND NOMBRES like 'CORTABRAZO NAVARRO LUZ%' ORDER BY FECHA DESC
SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE '%CANCER%'
SELECT * FROM CONSULTORIO WHERE CONSULTORIO = '1028'
select * from ATENCIONC where FECHA = CONVERT(DATETIME, '2015-12-01', 101) AND NOMCONSULTORIO = 'REHABILITACION TERAPIA'
/* UPDATE ATENCIONC SET TIPO_CITA = 'C' where FECHA = CONVERT(DATETIME, '2015-12-01', 101) AND NOMCONSULTORIO = 'REHABILITACION TERAPIA' */

SELECT * FROM MEDICO WHERE MEDICO = 'GRL'


select * from ATENCIONC where FECHA = CONVERT(DATETIME, '2015-12-01', 101)  AND NOMCONSULTORIO = 'REHABILITACION TERAPIA'  ORDER BY FECHA DESC


select * from ATENCIOND where  ID_CITA = '150151110'


SELECT * FROM CONSULTORIO WHERE HIS_CODSERVICIO = '301203' ORDER BY CONSULTORIO  ASC
SELECT * FROM CONSULTORIO ORDER BY CONSULTORIO ASC
