USE SIGSALUD

SELECT * FROM CIEXHIS WHERE CODCAT <> 'X' AND CODCAT = 'A00' ORDER BY CODCAT ASC

SELECT CODCAT FROM CIEXHIS WHERE CODCAT <> 'X' GROUP BY CODCAT ORDER BY CODCAT ASC

SELECT * FROM CIEXHIS WHERE CODCAT <> 'X' AND CODCAT = 'A00' 
A00

SELECT COD_CAT + COD_ENF AS CODIGO, UPPER(DESC_ENF) DESC_ENF FROM dbo.CIEX_10  WHERE COD_CAT LIKE 'A00%'