USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMPCODIGORESUMEN]    Script Date: 01/26/2016 18:00:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMPCODIGORESUMEN](
	[NKEY] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](20) NOT NULL,
	[DESCRICPION] [varchar](100) NULL,
	[SUBTOTAL] [int] NULL,
 CONSTRAINT [PK_TMPCODIGORESUMEN] PRIMARY KEY CLUSTERED 
(
	[NKEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


