USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_REJEPRO]    Script Date: 08/01/2016 16:26:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_REJEPRO](
	[IDREJEPRO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRECONSULTORIO] [varchar](50) NULL,
	[MEDICO] [varchar](5) NULL,
	[NOMBRE_MEDICO] [varchar](150) NULL,
	[EJECUTADO] [int] NULL,
	[ATENCIONES] [int] NULL,
	[PROGRAMADO] [int] NULL,
	[FECHA_REPORTE] [datetime] NULL,
	[USUARIO] [varchar](50) NULL,
 CONSTRAINT [PK_TMP_REJEPRO] PRIMARY KEY CLUSTERED 
(
	[IDREJEPRO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


