/* REVISAR BD EMERGENCIA */
use SIGSALUD
SELECT doc_iden, COUNT(doc_iden) as contar  FROM  dbo.SEEMEMERGENCIA  group by doc_iden ORDER BY doc_iden ASC

update dbo.SEEMEMERGENCIA set DOC_IDEN = '0' where DOC_IDEN is null 
Update dbo.SEEMEMERGENCIA set doc_iden = '0' where doc_iden in ('199999999', '1EN TRAMITE', '1NO RECUERD', '1NO TIENE', '099999999', '0NO RECUERD', '0NO SABE', '10', '17786084', '1E-27809075', '215.563.095', '2CC 5560553', '295.475.972', '0EN TRAMITE', '1', '1N', '1NO RECUERD')
update dbo.SEEMEMERGENCIA set DOC_IDEN = '107667395' where DOC_IDEN = '1076673951'
update dbo.SEEMEMERGENCIA set DOC_IDEN = '107677774' where DOC_IDEN = '1076777748'
update dbo.SEEMEMERGENCIA set DOC_IDEN = '110013605' where DOC_IDEN = '11001360521'
update dbo.SEEMEMERGENCIA set DOC_IDEN = '142759920' where DOC_IDEN = '1427599203'
update dbo.SEEMEMERGENCIA set DOC_IDEN = '172744060' where DOC_IDEN = '1727440604'
update dbo.SEEMEMERGENCIA set DOC_IDEN = '172744060' where DOC_IDEN = '1727440604'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '0' where ADOC_IDEN is null 
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '0' where ADOC_IDEN = '1068085995'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '0' where ADOC_IDEN in ('0', '10', '1068085995', '10989622', '1EN TRAMITE', '1', '1N', '1NO RECUERD') 
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107665825' where ADOC_IDEN = '1076658252'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107685041' where ADOC_IDEN = '107+685041'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107666996' where ADOC_IDEN = '1076669969'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107667415' where ADOC_IDEN = '1076674159'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107668451' where ADOC_IDEN = '1076684510'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107673864' where ADOC_IDEN = '1076738648'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '109728771' where ADOC_IDEN = '1097287717'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '109670108' where ADOC_IDEN = '1096701088'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '10989622' where ADOC_IDEN = '1098765075'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '116174444' where ADOC_IDEN = '1161744444'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107665825' where ADOC_IDEN = '1076658252'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '116257527' where ADOC_IDEN = '1162575279'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '110170014' where ADOC_IDEN = '110170014}'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '107654259' where ADOC_IDEN = '07654259'
update dbo.SEEMEMERGENCIA set ADOC_IDEN = '140563628' where ADOC_IDEN = '1405+63628'
UPDATE dbo.SEEMEMERGENCIA SET FECEGR = fecate WHERE FECEGR = ''
UPDATE dbo.SEEMEMERGENCIA SET HOREGR = HORATE WHERE HOREGR = ''
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = SUBSTRING(ADOC_IDEN,1,9) where LEN(ADOC_IDEN) = 10 AND SUBSTRING(ADOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = SUBSTRING(DOC_IDEN,1,9) where LEN(DOC_IDEN) = 10 AND SUBSTRING(DOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = SUBSTRING(ADOC_IDEN,1,9) where LEN(ADOC_IDEN) = 10 AND SUBSTRING(ADOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = SUBSTRING(DOC_IDEN,1,9) where LEN(DOC_IDEN) = 10 AND SUBSTRING(DOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = DOC_IDEN + '1' where LEN(DOC_IDEN) = 8
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = ADOC_IDEN + '12' where LEN(ADOC_IDEN) = 5
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = '0' where LEN(ADOC_IDEN) = 5
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = DOC_IDEN + '1' where LEN(DOC_IDEN) = 8







SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) = 12 AND SUBSTRING(DOC_IDEN,1,1) = '1'

SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) <> 9 and SUBSTRING(DOC_IDEN,1,1) = '1'
update SEEMEMERGENCIA set doc_iden = '0' where LEN(DOC_IDEN) <> 9 and SUBSTRING(DOC_IDEN,1,1) = '1'

SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) <> 9 and SUBSTRING(DOC_IDEN,1,1) = '2'
update SEEMEMERGENCIA set doc_iden = '0' where LEN(DOC_IDEN) <> 9 and SUBSTRING(DOC_IDEN,1,1) = '0'



SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD, REPLACE(DOC_IDEN,'.', '') as doc_iden_final FROM dbo.SEEMEMERGENCIA where SUBSTRING(DOC_IDEN,1,1) = '2' and len(SUBSTRING(DOC_IDEN,2,11))>8 order by LEN(DOC_IDEN) desc

SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD, REPLACE(DOC_IDEN,'-', '') as doc_iden_final FROM dbo.SEEMEMERGENCIA where SUBSTRING(DOC_IDEN,1,1) = '1' and SUBSTRING(DOC_IDEN,2,8) = 'NO TIENE'

update SEEMEMERGENCIA set doc_iden = REPLACE(DOC_IDEN,'.', '')  where SUBSTRING(DOC_IDEN,1,1) = '2' and len(SUBSTRING(DOC_IDEN,2,11))>9
update SEEMEMERGENCIA set doc_iden = REPLACE(DOC_IDEN,'-', '')  where SUBSTRING(DOC_IDEN,1,1) = '2' and len(SUBSTRING(DOC_IDEN,2,11))>1


update SEEMEMERGENCIA set doc_iden = '0'  where SUBSTRING(DOC_IDEN,1,1) = '1' and SUBSTRING(DOC_IDEN,2,5) = '00000'

update SEEMEMERGENCIA set doc_iden = '0'  where SUBSTRING(DOC_IDEN,1,1) = '1' and SUBSTRING(DOC_IDEN,2,8) = '99999999'


SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD, REPLACE(DOC_IDEN,'-', '') as doc_iden_final FROM dbo.SEEMEMERGENCIA where SUBSTRING(DOC_IDEN,1,1) = '1' and SUBSTRING(DOC_IDEN,2,8) = '99999999'


update  dbo.SEEMEMERGENCIA set doc_iden = '0' where SUBSTRING(DOC_IDEN,1,1) = '1' and SUBSTRING(DOC_IDEN,2,8) = 'NO TIENE'






update SEEMEMERGENCIA set doc_iden = '0'  where SUBSTRING(DOC_IDEN,1,1) = '2' and len(SUBSTRING(DOC_IDEN,2,11))<9



update SEEMEMERGENCIA set doc_iden = '1' + SUBSTRING(DOC_IDEN,2,11)  where SUBSTRING(DOC_IDEN,1,1) = '1' and len(SUBSTRING(DOC_IDEN,2,11))>0


UNION ALL 
SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) = 10
UNION ALL 
SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) = 11
UNION ALL 
SELECT DOC_IDEN, LEN(DOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(DOC_IDEN) = 0

 









SELECT Adoc_iden FROM  dbo.SEEMEMERGENCIA  group by Adoc_iden ORDER BY ADOC_IDEN ASC
SELECT FINANCIA FROM  dbo.SEEMEMERGENCIA  group by FINANCIA ORDER BY FINANCIA ASC

SELECT * FROM dbo.SEEMEMERGENCIA WHERE CONVERT(DATE, fecate, 3) <   CONVERT(DATETIME, '01/10/16', 3)
SELECT * FROM dbo.SEEMEMERGENCIA WHERE CONVERT(DATE, fecate, 3) >   CONVERT(DATETIME, '31/10/16', 3)

SELECT * FROM dbo.SEEMEMERGENCIA WHERE CONVERT(DATE, FECEGR, 3) >=   CONVERT(DATETIME, '01/11/16', 3)

SELECT * FROM dbo.SEEMEMERGENCIA WHERE CONVERT(DATE, fecate, 3) >   CONVERT(DATETIME, '31/10/16', 3)



use SIGSALUD
select * FROM dbo.SEEMEMERGENCIA



SELECT * FROM dbo.SEEMEMERGENCIA WHERE CONVERT(DATE, FECEGR, 101) = 
select  * from dbo.SEEMEMERGENCIA order by FECEGR asc

select  * from dbo.SEEMEMERGENCIA order by CONVERT(DATETIME, FECATE, 3)  asc

select  NOMB, APELL, fecate, FECEGR from dbo.SEEMEMERGENCIA order by CONVERT(DATETIME, FECEGR, 3)  asc






/* ADOC_IDEN */

SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 9
UNION ALL 
SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 10 
UNION ALL 
SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 11
UNION ALL 
SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 1


UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = SUBSTRING(ADOC_IDEN,1,9) where LEN(ADOC_IDEN) = 10 AND SUBSTRING(ADOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = SUBSTRING(DOC_IDEN,1,9) where LEN(DOC_IDEN) = 10 AND SUBSTRING(DOC_IDEN,1,1) = '1'
UPDATE dbo.SEEMEMERGENCIA SET DOC_IDEN = DOC_IDEN + '1' where LEN(DOC_IDEN) = 8
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = ADOC_IDEN + '12' where LEN(ADOC_IDEN) = 5
UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = '0' where LEN(ADOC_IDEN) = 5




SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 9

SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 10


SELECT ADOC_IDEN, LEN(ADOC_IDEN) AS LONGITUD FROM dbo.SEEMEMERGENCIA where LEN(ADOC_IDEN) = 10 AND SUBSTRING(ADOC_IDEN,1,1) = '1'

UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = ADOC_IDEN + '12' where LEN(ADOC_IDEN) = 5

UPDATE dbo.SEEMEMERGENCIA SET ADOC_IDEN = '0' where LEN(ADOC_IDEN) = 5










