USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[SEMMEDICOS]    Script Date: 03/31/2016 12:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SEMMEDICOS](
	[IDMEDICO] [int] IDENTITY(1,1) NOT NULL,
	[CODPSAL] [varchar](11) NULL,
	[NOMBRE] [varchar](100) NULL,
	[PLAZA] [numeric](6, 0) NULL,
	[COD_2000] [varchar](10) NULL,
	[COD_PROF] [varchar](2) NULL,
	[COD_COND] [varchar](1) NULL,
	[FECHA_ING] [varchar](8) NULL,
	[FECHA_BAJA] [varchar](8) NULL,
	[DNI] [varchar](10) NULL,
 CONSTRAINT [PK_SEMMEDICOS] PRIMARY KEY CLUSTERED 
(
	[IDMEDICO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


