/*  ver caso de seem egresos */
USE SIGSALUD
SELECT EMERGENCIA_ID, FECHA, HORA, PATERNO, MATERNO, NOMBRE, NOMBRES, FECHA_NACIMIENTO, SEXO, DIRECCION, TIPO_DOCUMENTO, DOCUMENTO, ACOMPANANTE, TIPO_DOCUMENTOA, DOCUMENTOA, USUARIO
   FROM EMERGENCIA WHERE NOMBRES LIKE '.%' ORDER BY FECHA DESC



SELECT EMERGENCIA_ID, FECHA, HORA, B.HISTORIA, B.PATERNO, B.MATERNO, B.NOMBRE, B.NOMBRES, B.FECHA_NACIMIENTO, B.SEXO, B.DIRECCION, B.TIPO_DOCUMENTO, B.DOCUMENTO, A.ACOMPANANTE, A.TIPO_DOCUMENTOA, A.DOCUMENTOA,
A.USUARIO  FROM EMERGENCIA A LEFT JOIN PACIENTE B ON B.PACIENTE = A.PACIENTE WHERE A.NOMBRES LIKE '.%' ORDER BY FECHA DESC



SELECT EMERGENCIA_ID, FECHA, HORA, B.HISTORIA, B.PATERNO, B.MATERNO, B.NOMBRE, B.NOMBRES, B.FECHA_NACIMIENTO, B.SEXO, B.DIRECCION, B.TIPO_DOCUMENTO, B.DOCUMENTO, A.ACOMPANANTE, A.TIPO_DOCUMENTOA, A.DOCUMENTOA,
A.USUARIO  FROM EMERGENCIA A LEFT JOIN PACIENTE B ON B.PACIENTE = A.PACIENTE WHERE B.PATERNO = '' ORDER BY FECHA DESC



SELECT * FROM EMERGENCIA
SELECT EMERGENCIA_ID, FECHA, HORA, PATERNO, MATERNO, NOMBRE, NOMBRES, FECHA_NACIMIENTO, SEXO, DIRECCION, TIPO_DOCUMENTO, DOCUMENTO, ACOMPANANTE, TIPO_DOCUMENTOA, DOCUMENTOA, USUARIO
   FROM EMERGENCIA WHERE PATERNO = '' ORDER BY FECHA DESC
