use sigsalud	
/* enero - junio -2016 */
select 'HOSPITALIZACION' AS SERVICIO, COUNT(NUMATENCION) AS SUB_TOTAL
 from ATENCION_SEGURO where FECHA_ATENCION between CONVERT(datetime, '2016-01-01', 101) and CONVERT(datetime, '2016-06-30', 101) and ESTADO = '2'
  AND ORIGEN = 'HO' AND SEGURO = '01' GROUP BY ORIGEN
UNION ALL  
select 'EMERGENCIA' AS SERVICIO, COUNT(NUMATENCION) AS SUB_TOTAL
 from ATENCION_SEGURO where FECHA_ATENCION between CONVERT(datetime, '2016-01-01', 101) and CONVERT(datetime, '2016-06-30', 101) and ESTADO = '2'
  AND ORIGEN = 'EM' AND SEGURO = '01' GROUP BY ORIGEN
UNION ALL  
select 'CONSULTORIO EXTERNO ' AS SERVICIO, COUNT(NUMATENCION) AS SUB_TOTAL
 from ATENCION_SEGURO where FECHA_ATENCION between CONVERT(datetime, '2016-01-01', 101) and CONVERT(datetime, '2016-06-30', 101) and ESTADO = '2'
  AND ORIGEN = 'CE' AND SEGURO = '01' GROUP BY ORIGEN

   