USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[FUAS_EQUIVALENTES]    Script Date: 08/01/2016 12:47:49 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FUAS_EQUIVALENTES](
	[NUMFUA_ANTERIOR] [varchar](100) NULL,
	[NUMFUA_NUEVO] [varchar](100) NULL,
	[IDKEY] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


