use sigsalud

select TOP 1 ATENCION_SEGURO_ID, NUMATENCION, PACIENTE  from ATENCION_SEGURO order by NUMATENCION desc 
select *  from ATENCION_SEGURO order by NUMATENCION desc 

/* select * from ATENCION_SEGURO order by NUMATENCION desc  */
/* select ATENCION_SEGURO_ID, NUMATENCION from ATENCION_SEGURO WHERE FECHA_ATENCION BETWEEN CONVERT(DATETIME, '2015-07-15',101) AND CONVERT(DATETIME, '2015-08-30',101)  order by NUMATENCION desc
select * from ATENCION_SEGURO WHERE ATENCION_SEGURO_ID = '15037242' */
/* INSERT INTO [SIGSALUD].[dbo].[ATENCION_SEGURO] (ATENCION_SEGURO_ID, NUMATENCION, PACIENTE, HISTORIA, NOMBRES, FECHA_ATENCION, HORA_ATENCION, ESTADO)
  VALUES (?lnid,?lnfua,'2008014541', '0014552', 'YCHPAS LIMACO ESTHER', GETDATE(), '00:00', '0') */
/* INSERT INTO [SIGSALUD].[dbo].[ATENCION_SEGURO] (ATENCION_SEGURO_ID, NUMATENCION, PACIENTE, HISTORIA, NOMBRES, FECHA_ATENCION, HORA_ATENCION, ESTADO)
  VALUES ('15072117','2101520064701','2008014541', '0014552', 'YCHPAS LIMACO ESTHER', GETDATE(), '00:00', '0') */

select * from PACIENTE where PACIENTE = '2008014541'

select TOP 1 ATENCION_SEGURO_ID, NUMATENCION from ATENCION_SEGURO order by NUMATENCION desc 
select TOP 1 (CONVERT(NUMERIC(8,0), ATENCION_SEGURO_ID) + 1) AS NID, (CONVERT(NUMERIC(18,0), NUMATENCION) + 1) AS NFUA  from ATENCION_SEGURO order by NUMATENCION desc 
select TOP 1 (CONVERT(NUMERIC(8,0), ATENCION_SEGURO_ID) + 1) AS NID, (CONVERT(NUMERIC(18,0), NUMATENCION) + 1 + 200) AS NFUA  from ATENCION_SEGURO order by NUMATENCION desc 
select TOP 1 (CONVERT(NUMERIC(8,0), ATENCION_SEGURO_ID) + 1) AS NID, (CONVERT(NUMERIC(18,0), NUMATENCION) + 1 + 200 + 1) AS NFUA  from ATENCION_SEGURO order by NUMATENCION desc 


  select TOP 1 ATENCION_SEGURO_ID, NUMATENCION, FECHA_ATENCION, HORA_ATENCION  from ATENCION_SEGURO order by NUMATENCION desc 
  


