/* DIGITAL BUENOS */

ALTER TABLE RAYOSX  ADD DB8_10 INT NOT NULL  CONSTRAINT RAYOS_X_DB8_10 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DB14_17 INT NOT NULL  CONSTRAINT RAYOS_X_DB14_17 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DB14_14 INT NOT NULL  CONSTRAINT RAYOS_X_DB14_14 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DB10_12 INT NOT NULL  CONSTRAINT RAYOS_X_DB10_12 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DB11_14 INT NOT NULL  CONSTRAINT RAYOS_X_DB11_14 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DB24_30 INT NOT NULL  CONSTRAINT RAYOS_X_DB24_30 DEFAULT ((0));


/* DIGITALES MALOS */

ALTER TABLE RAYOSX  ADD DM8_10 INT NOT NULL  CONSTRAINT RAYOS_X_DM8_10 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DM14_17 INT NOT NULL  CONSTRAINT RAYOS_X_DM14_17 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DM14_14 INT NOT NULL  CONSTRAINT RAYOS_X_DM14_14 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DM10_12 INT NOT NULL  CONSTRAINT RAYOS_X_DM10_12 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DM11_14 INT NOT NULL  CONSTRAINT RAYOS_X_DM11_14 DEFAULT ((0));
ALTER TABLE RAYOSX  ADD DM24_30 INT NOT NULL  CONSTRAINT RAYOS_X_DM24_30 DEFAULT ((0));
