/* UTILIDAD PARA CMBIAR EL IP PARA EL SISTEMA DE EMERGENCIA */

SELECT * FROM ACCESO_MODULO
SELECT *  FROM PLANTILLA_MODULO

/* update ACCESO_MODULO set URL = REPLACE(url,'192.168.0.9','192.168.3.12')
   Update plantilla_MODULO set URL = REPLACE(url,'192.168.0.9','192.168.3.12')  */

SELECT * FROM ACCESO_MODULO
SELECT *  FROM PLANTILLA_MODULO



