USE [SIGSALUD]
GO

/****** Object:  StoredProcedure [dbo].[SP_RAYOSX_CUADRO1]    Script Date: 05/03/2017 16:29:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_RAYOSX_CUADRO1](
@inicio VARCHAR(10),
@fin VARCHAR(10)
)
AS BEGIN

SET LANGUAGE SPANISH

SELECT * FROM (
	SELECT 
	'0' AS ORDEN,
	-- ORDENES TOTAL
	'TOTAL' AS CLASIFICACION,ISNULL(COUNT(RAYOSX),0) AS ORDENES,
	-- EXAMENES TOTAL
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE FECHA BETWEEN @inicio AND @fin) AS EXAMENES,
	-- PLACAS TOTAL
	ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) AS PLACAS, 
	-- ORDENES POR CONSULTORIO
	(SELECT COUNT(RAYOSX) FROM RAYOSX WHERE UPS='C' AND FECHA BETWEEN @inicio AND @fin) AS ORDENES_CO, 
	-- EXAMENES POR CONSULTORIO
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE A.UPS='C' AND FECHA BETWEEN @inicio AND @fin) AS EXAMENES_CO,
	-- PLACAS POR CONSULTORIO
	(SELECT ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) FROM RAYOSX WHERE UPS='C' AND FECHA BETWEEN @inicio AND @fin) AS PLACAS_CO,
	-- ORDENES POR HOSPITALIZACION
	(SELECT COUNT(RAYOSX) FROM RAYOSX WHERE UPS='H' AND FECHA BETWEEN @inicio AND @fin) AS ORDENES_HO,
	-- EXAMENES POR HOSPITALIZACION
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE A.UPS='H' AND FECHA BETWEEN @inicio AND @fin) AS EXAMENES_HO,
	-- PLACAS POR HOSPITALIZACION
	(SELECT ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) FROM RAYOSX WHERE UPS='H' AND FECHA BETWEEN @inicio AND @fin) AS PLACAS_HO,
	-- ORDENES POR EMERGENCIA
	(SELECT COUNT(RAYOSX) FROM RAYOSX WHERE UPS='E' AND FECHA BETWEEN @inicio AND @fin) AS ORDENES_EM,
	-- EXAMENES POR EMERGENCIA
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE A.UPS='E' AND FECHA BETWEEN @inicio AND @fin) AS EXAMENES_EM,
	-- PLACAS POR EMERGENCIA
	(SELECT ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) FROM RAYOSX WHERE UPS='E' AND FECHA BETWEEN @inicio AND @fin) AS PLACAS_EM,
	-- ORDENES POR PERIFERICO
	(SELECT COUNT(RAYOSX) FROM RAYOSX WHERE UPS='PE' AND FECHA BETWEEN @inicio AND @fin) AS ORDENES_PE,
	-- EXAMENES POR PERIFERICO
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE A.UPS='PE' AND FECHA BETWEEN @inicio AND @fin) AS EXAMENES_PE,
	-- PLACAS POR PERIFERICO
	(SELECT ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) FROM RAYOSX WHERE UPS='PE' AND FECHA BETWEEN @inicio AND @fin) AS PLACAS_PE,
	-- ORDENES POR PRIVADO O PARTICULAR
	(SELECT COUNT(RAYOSX) FROM RAYOSX WHERE UPS='PA' AND FECHA BETWEEN @inicio AND @fin) AS ORDENES_PA,
	-- EXAMENES POR PRIVADO O PARTICULAR
	(SELECT ISNULL(SUM(B.CANTIDAD),0) FROM RAYOSX A INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE A.UPS='PA' AND FECHA BETWEEN @inicio AND @fin) AS EXAMENES_PA,
	-- PLACAS POR PRIVADO O PARTICULAR
	(SELECT ISNULL(SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12),0) FROM RAYOSX WHERE UPS='PA' AND FECHA BETWEEN @inicio AND @fin) AS PLACAS_PA		
	FROM RAYOSX WHERE FECHA BETWEEN @inicio AND @fin
	
	UNION ALL

	SELECT 
	A.ORDEN,A.CLASIFICACION,A.ORDENES,B.EXAMENES,C.PLACAS,A.ORDENES_CO,B.EXAMENES_CO,C.PLACAS_CO,A.ORDENES_HO,EXAMENES_HO,PLACAS_HO,
	ORDENES_EM,EXAMENES_EM,PLACAS_EM,ORDENES_PE,EXAMENES_PE,PLACAS_PE,ORDENES_PA,EXAMENES_PA,PLACAS_PA
	FROM (
	SELECT
	ORDEN,
	CLASIFICACION,
	SUM(C+H+E+PE+PA) AS ORDENES,
	C AS ORDENES_CO,H AS ORDENES_HO,E AS ORDENES_EM,
	PE AS ORDENES_PE,PA AS ORDENES_PA FROM (
	SELECT
	ORDEN,
	CLASIFICACION,
	ISNULL(C,0) AS C,ISNULL(H,0) AS H,ISNULL(E,0) AS E,
	ISNULL(PE,0) AS PE,ISNULL(PA,0) AS PA FROM(
		SELECT 	CASE 
		WHEN EDAD >=0 AND EDAD <=31 AND TIPO_EDAD<>'A' THEN '1' 
		WHEN EDAD >=1 AND EDAD <=4 AND TIPO_EDAD='A'  THEN '2'
		WHEN EDAD >=5 AND EDAD <=9 AND TIPO_EDAD='A' THEN '3'
		WHEN EDAD >=10 AND EDAD <=19 AND TIPO_EDAD='A' THEN '4'
		WHEN EDAD >=20 AND EDAD <=49 AND TIPO_EDAD='A' THEN '5'
		WHEN EDAD >=50 AND EDAD <=59 AND TIPO_EDAD='A' THEN '6'
		WHEN EDAD >=60 AND EDAD <=64 AND TIPO_EDAD='A' THEN '7' 
		WHEN EDAD >=65 AND EDAD <=120 AND TIPO_EDAD='A' THEN '8'
		END AS ORDEN,
		dbo.FN_GRUPOH_RAYOSX(EDAD,TIPO_EDAD) AS CLASIFICACION,COUNT(RAYOSX) AS ORDENES,UPS FROM RAYOSX 
		WHERE FECHA BETWEEN @inicio AND @fin
		GROUP BY EDAD,TIPO_EDAD,UPS) AS O

		PIVOT(
			SUM(ORDENES) FOR UPS IN (C,H,E,PE,PA)
		) AS PIVOTABLE) AS OO GROUP BY ORDEN,CLASIFICACION,C,H,E,PE,PA) AS A 

	FULL JOIN

	(SELECT
	CLASIFICACION,
	SUM(C+H+E+PE+PA) AS EXAMENES,C AS EXAMENES_CO,H AS EXAMENES_HO,
	E AS EXAMENES_EM,PE AS EXAMENES_PE,PA AS EXAMENES_PA FROM (
	SELECT 
	CLASIFICACION,
	ISNULL(C,0) AS C,ISNULL(H,0) AS H,ISNULL(E,0) AS E,
	ISNULL(PE,0) AS PE,ISNULL(PA,0) AS PA
	FROM(
		SELECT dbo.FN_GRUPOH_RAYOSX(EDAD,TIPO_EDAD) AS CLASIFICACION,SUM(CANTIDAD) AS EXAMENES,UPS FROM RAYOSX A
		INNER JOIN RAYOSX_DETALLE B ON (A.RAYOSX=B.RAYOSX) WHERE FECHA BETWEEN @inicio AND @fin GROUP BY EDAD,TIPO_EDAD,UPS) AS E
		
		PIVOT(
			SUM(EXAMENES) FOR UPS IN (C,H,E,PE,PA)
		) AS PIVOTABLE) AS EE GROUP BY CLASIFICACION,C,H,E,PE,PA ) AS B ON (A.CLASIFICACION=B.CLASIFICACION)

	FULL JOIN

	(SELECT 
	CLASIFICACION,
	SUM(PLACAS_CO+PLACAS_EM+PLACAS_HO+PLACAS_PE+PLACAS_PA) AS PLACAS,
	PLACAS_CO,PLACAS_HO,PLACAS_EM,PLACAS_PE,PLACAS_PA FROM (
	SELECT 
	CLASIFICACION,
	ISNULL(C,0) AS PLACAS_CO,ISNULL(E,0) AS PLACAS_EM,
	ISNULL(H,0) AS PLACAS_HO,ISNULL(PE,0) AS PLACAS_PE,
	ISNULL(PA,0) AS PLACAS_PA
	FROM (
		SELECT dbo.FN_GRUPOH_RAYOSX(EDAD,TIPO_EDAD) AS CLASIFICACION,
		SUM(B18_24+B24_30+B30_40+B14_14+B14_17+M18_24+M24_30+M30_40+M14_14+M14_17+B8_10+B10_12+M8_10+M10_12) AS PLACAS,UPS 
		FROM RAYOSX WHERE FECHA BETWEEN @inicio AND @fin GROUP BY EDAD,TIPO_EDAD,UPS ) AS P
		
		PIVOT (
			SUM(PLACAS) FOR UPS IN (C,E,H,PA,PE)
		) AS PIVOTABLE) AS PP 
		GROUP BY CLASIFICACION,PLACAS_CO,PLACAS_EM,PLACAS_HO,PLACAS_PE,PLACAS_PA) AS C ON (B.CLASIFICACION=C.CLASIFICACION)
		

	) AS CUADRO1 ORDER BY ORDEN ASC
END





GO


