/*  SELECCIONAR LOS USUARIOS DEL SISTEMA DE RAYOS X */

declare @lmodulo varchar(10) = 'APOYODX'

SELECT * FROM USUARIO where MODULO = @lmodulo ORDER BY NOMBRE ASC
UPDATE USUARIO SET NOMBRE = UPPER(NOMBRE), USUNOMBRE = UPPER(USUNOMBRE), USUMATERNO = UPPER(USUMATERNO),   USUPATERNO = UPPER(USUPATERNO), FECHAULTIMOINGRESO = GETDATE(), FECHA_EXPIRACION = GETDATE() + 17900  WHERE MODULO = @lmodulo
DELETE FROM USUARIO WHERE USUARIO = 'MLEVANO' AND MODULO = @lmodulo
SELECT * FROM USUARIO where MODULO = @lmodulo ORDER BY NOMBRE ASC
