USE BDPERSONAL
SELECT CODIGO, NOMBRE, SITUACION, CODHORA, HORAS FROM MAESTRO WHERE CODIGO = '084218'
UNION ALL
SELECT CODIGO, NOMBRE, SITUACION, CODHORA, HORAS FROM MAESTRO WHERE CODIGO = '084254'
UNION ALL
SELECT CODIGO, NOMBRE, SITUACION, CODHORA, HORAS FROM MAESTRO WHERE CODIGO = '084036'
UNION ALL
SELECT CODIGO, NOMBRE, SITUACION, CODHORA, HORAS FROM MAESTRO WHERE CODIGO = '084381'
/* UPDATE MAESTRO SET CODHORA = 'R', HORAS = '6' WHERE CODIGO = '084254' */