/* LUNASCO */
SELECT * FROM [BDPERSONAL].[dbo].[ASISTENCIA] WHERE CODIGO = '084433' AND MES = 12 AND AÑO = 2017 AND IdServDepartUnid = 81
ORDER BY CONVERT(INT, DIA) ASC


/* CONDORI */
SELECT * FROM [BDPERSONAL].[dbo].[ASISTENCIA] WHERE CODIGO = '084613' AND MES = 12 AND AÑO = 2017 AND IdServDepartUnid = 83
ORDER BY CONVERT(INT, DIA) ASC



/* LUNASCO -- CONDORI*/
update [BDPERSONAL].[dbo].[ASISTENCIA] set codigo = '084613'  WHERE CODIGO = '084433' AND MES = 12 AND AÑO = 2017 AND IdServDepartUnid = 81
/* CONDORI A LUNASCO */
update [BDPERSONAL].[dbo].[ASISTENCIA] set codigo =  '084433'   WHERE CODIGO = '084613' AND MES = 12 AND AÑO = 2017 AND IdServDepartUnid = 83


ORDER BY CONVERT(INT, DIA) ASC