USE BDPERSONAL
SELECT * FROM V_MAESTRO WHERE NOMBRE LIKE 'MONTERO%'

/* ESTABA */
SELECT * FROM V_MAESTRO WHERE CODIGO = '084442'
UNION ALL
/* DEBE ESTAR */
SELECT * FROM V_MAESTRO WHERE CODIGO = '084612'