 SELECT CODSIAF  FROM MAESTRO WHERE NOMBRE LIKE '%MUÑOZ FIGUEROA FERNANDO%'
  SELECT CODSIAF  FROM MAESTRO WHERE NOMBRE LIKE '%ORTIZ TALAVERANO JUANA%'
   SELECT CODSIAF  FROM MAESTRO WHERE NOMBRE LIKE '%JAUREGUI MARCOS MERCEDES%'
  SELECT CODSIAF  FROM MAESTRO WHERE NOMBRE LIKE '%CALAGUA FIGUEREDO PATRICIA%'
  
  SELECT *   FROM MAESTRO WHERE NOMBRE LIKE '%HARO VELIZ EDGARDO MAURICIO%'
   SELECT *   FROM MAESTRO WHERE NOMBRE LIKE '%ORTIZ TALAVERANO JUANA%'
  
  SELECT * FROM GUARDIA_EFE WHERE NOMBRE LIKE '%GAMARRA POVIS MARIBEL TRINIDAD%'