USE BDPERSONAL
SELECT * FROM ASISTENCIA WHERE Año = 2016 AND MES = 2 AND  IDSERVDEPARTUNID = '89'

USE BDPERSONAL
SELECT CODIGO  FROM ASISTENCIA WHERE Año = 2016 AND MES = 2 AND IDSERVDEPARTUNID = '89' GROUP BY CODIGO 

USE BDPERSONAL
SELECT *  FROM ASISTENCIA WHERE Año = 2016 AND MES = 2 AND IDSERVDEPARTUNID = '89'  AND CODIGO = ''

/* DELETE FROM ASISTENCIA WHERE Año = 2016 AND MES = 2 AND IDSERVDEPARTUNID = '89'  AND CODIGO = '' */
