USE [BDPERSONAL]
GO

/****** Object:  Table [dbo].[LGJ_PARAMETRO_OTROS]    Script Date: 04/11/2018 11:48:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LGJ_PARAMETRO_OTROS](
	[IDOTROS] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NULL,
	[FECHAREGISTRO] [datetime] NULL,
	[USUARIO] [varchar](50) NULL,
 CONSTRAINT [PK_LGJ_PARAMETRO_OTROS] PRIMARY KEY CLUSTERED 
(
	[IDOTROS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


