TRUNCATE TABLE dbo.TMPASISTENCIA
TRUNCATE TABLE dbo.TMPHISTORICOPERSONAL
TRUNCATE TABLE dbo.TMPPERSONAL



TRUNCATE TABLE dbo.TMPASISTENCIACAS
TRUNCATE TABLE dbo.TMPHISTORICOPERSONALCAS
TRUNCATE TABLE dbo.TMPPERSONALCAS