/* REPORTE PARA MARILU SOBRE HUELGA MEDICA */

select * from CITA where FECHA = CONVERT(DATETIME, '2017-07-04', 101)  and MEDICO = 'MTA'

select * from CITA where FECHA = CONVERT(DATETIME, '2017-07-04', 101)  and MEDICO = 'MTA' AND ESTADO IN ('2', '3', '4', '5')

USE SIGSALUD

SOLO - MEDICAS 

MEDICINA
TRAUMA
PEDIARRIA
CIRUGIA
GINECO
OFTALMOLOGIA

SIS

select * from V_CITA 

select NOMBRE_CONSULTORIO,  NOMBRE_MEDICO, COUNT(NOMBRE_MEDICO) AS CITAS from V_CITA where FECHA = CONVERT(DATETIME, '2017-07-04', 101)  and  ESTADO IN ('2', '3', '4', '5')
AND CONSULTORIO IN (
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '10%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '20%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '30%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO IN ('4041', '4043') AND TIPO = 'C') and SEGURO = '01' and
 TURNO_CONSULTA = 'M' GROUP BY NOMBRE_MEDICO, NOMBRE_CONSULTORIO   ORDER BY NOMBRE_MEDICO ASC





SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '10%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '20%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '30%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO IN ('4041', '4043') AND TIPO = 'C'



select COUNT(*)/30 from CITA where FECHA between CONVERT(DATETIME, '2017-06-01', 101)  and CONVERT(DATETIME, '2017-06-30', 101)  and  ESTADO IN ('3', '4', '5')
AND CONSULTORIO IN (
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '10%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '20%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '30%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO IN ('4041', '4043') AND TIPO = 'C')  and  TURNO_CONSULTA = 'T' 




select COUNT(*) from CITA where FECHA between CONVERT(DATETIME, '2017-07-06', 101)  and CONVERT(DATETIME, '2017-07-06', 101)  and  ESTADO IN ('2', '3', '4', '5')
AND CONSULTORIO IN (
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '10%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '20%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO LIKE '30%' AND TIPO = 'C'
UNION ALL
SELECT CONSULTORIO FROM CONSULTORIO WHERE CONSULTORIO IN ('4041', '4043') AND TIPO = 'C')  and  TURNO_CONSULTA = 'T' 


