USE BDPERSONAL
SELECT NOMBRE, UNIDAD_ORGANICA, CARGO_FUNCIONAL FROM V_MAESTRO WHERE SITUACION = '01' 
SELECT NOMBRE, UNIDAD_ORGANICA, CARGO_FUNCIONAL FROM V_MAESTRO WHERE SITUACION = '02' 
SELECT NOMBRE, UNIDAD_ORGANICA, CARGO_FUNCIONAL FROM V_MAESTRO WHERE SITUACION = '03' ORDER BY NOMBRE ASC
SELECT NOMBRE, UNIDAD_ORGANICA, CARGO_FUNCIONAL FROM V_MAESTRO WHERE SITUACION = '06' ORDER BY NOMBRE ASC




SELECT * FROM MAESTRO WHERE SITUACION = '02' 
SELECT * FROM MAESTRO WHERE SITUACION = '03' 
SELECT * FROM MAESTRO WHERE SITUACION = '06' 


SELECT [CODIGO]
      ,[NOMBRE]
      ,[ESTADO]
  FROM [BDPERSONAL].[dbo].[T_TipoSituacion]
GO


