USE BDPERSONAL
SELECT ROW_NUMBER() OVER (ORDER BY CONVERT(DATETIME,SUBSTRING(FECHA, 1,6) + CONVERT(VARCHAR(4), year(CONVERT(datetime, FECHANACIMIENTO, 103)) + convert(int, c.edad)), 103)) as FILA, APELLIDOSNOMBRES, FECHANACIMIENTO, A.SEXO,  DNI, REPLACE(NOMBRE, 'FECHA DE ', '') AS  NOMBRE, FECHA,
 year(GETDATE()) - year(CONVERT(datetime, FECHA, 103)) as ANIOS_SERVICIO,  convert(int, c.edad)  - (year(GETDATE()) - year(CONVERT(datetime, FECHANACIMIENTO, 103))) as FALTA, SUBSTRING(FECHA, 1,6) + CONVERT(VARCHAR(4), year(CONVERT(datetime, FECHANACIMIENTO, 103)) + convert(int, c.edad)) 
as  ANIO_QUE_DEBE_TERMINAR  FROM dbo.LGJ_MASTER A LEFT JOIN  LGJ_REGISTRARFECHAS B ON B.IDMASTER = A.IDMASTER  left join  [BDPERSONAL].[dbo].[LGJ_EDAD_CESE] C on c.SEXO = a.SEXO
 WHERE B.IDFECHA  = '2' ORDER BY year(GETDATE()) - year(CONVERT(datetime, FECHA, 103))  DESC
 
 
USE BDPERSONAL
DECLARE @lmax INT = 25
DECLARE @lmin INT = 22
declare @lcondi varchar(2) = '01' 
SELECT ROW_NUMBER() OVER (ORDER BY CONVERT(DATETIME,SUBSTRING(FECHA, 1,6) + CONVERT(VARCHAR(4), year(CONVERT(datetime, FECHANACIMIENTO, 103)) + convert(int, c.edad)), 103)) as FILA, APELLIDOSNOMBRES, FECHANACIMIENTO, A.SEXO,  DNI, REPLACE(NOMBRE, 'FECHA DE ', '') AS  NOMBRE, FECHA,
 year(GETDATE()) - year(CONVERT(datetime, FECHA, 103)) as ANIOS_SERVICIO,  year(GETDATE()) - year(CONVERT(datetime, FECHANACIMIENTO, 103)) as EDAD, convert(int, c.edad)  - (year(GETDATE()) - year(CONVERT(datetime, FECHANACIMIENTO, 103))) as FALTA, SUBSTRING(FECHA, 1,6) + CONVERT(VARCHAR(4), year(CONVERT(datetime, FECHANACIMIENTO, 103)) + convert(int, c.edad)) 
as  ANIO_QUE_DEBE_TERMINAR  FROM dbo.LGJ_MASTER A LEFT JOIN  LGJ_REGISTRARFECHAS B ON B.IDMASTER = A.IDMASTER  left join  [BDPERSONAL].[dbo].[LGJ_EDAD_CESE] C on c.SEXO = a.SEXO
 WHERE B.IDFECHA  = '2' and  a.CONDICIONLABORAL = @lcondi AND year(GETDATE()) - year(CONVERT(datetime, FECHA, 103)) BETWEEN @lmin AND @lmax ORDER BY year(GETDATE()) - year(CONVERT(datetime, FECHA, 103))  DESC
 
 
 SELECT * FROM LGJ_MASTER