USE BDPERSONAL
SELECT * FROM MAESTRO WHERE NOMBRE LIKE '%SOSA%'

SELECT * FROM RELOGDIGI WHERE CODIGO = '7675049' ORDER BY FECHA DESC

SELECT * FROM RELOGDIGI WHERE CODIGO = '7475049' ORDER BY FECHA DESC


select * from MAESTRO where NOMBRE like '%magali%'

select * from MAESTRO where CODIGO = '084346'
/* DNI-RELOG : 40054267 */
/* QUISPE RICALDI MITKA MAGALI */

SELECT * FROM RELOGDIGI WHERE CODIGO = 40054267 ORDER BY FECHA DESC

select * from MAESTRO WHERE NOMBRE LIKE 'PEREZ%'
/* 084092 -- 6777907 */

SELECT * FROM RELOGDIGI WHERE CODIGO = 6777907 ORDER BY FECHA DESC