USE BDPERSONAL

SELECT * FROM MAESTRO WHERE NOMBRE LIKE 'ASMAT%'

SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1

SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODIGO = '084286'

SELECT CODIGO, COUNT(CODIGO) AS DIAS FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 GROUP BY CODIGO ORDER BY DIAS DESC

SELECT * FROM MAESTRO WHERE CODIGO = '084269'


SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODIGO = '084269' ORDER BY DIA ASC

/*  */

SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODACT IS NULL

SELECT CODIGO, COUNT(CODIGO) AS DIAS FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODACT IS NULL GROUP BY CODIGO ORDER BY DIAS DESC

SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODIGO = '' 

SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND CODACT IS NULL
SELECT * FROM ASISTENCIA WHERE AÑO = 2016 AND MES = 1 AND TIPO IS NULL

  

