USE BDPERSONAL
declare @lcdni varchar(13) = '73351268'
select DNI, CODIGO, NOMBRE, DNI_RELOG, UNIDAD_ORGANICA  into TMP_ASISMARCAS FROM 
 V_MAESTRO WHERE CODIGO IN 
  (SELECT CODIGO FROM dbo.ServicioMaestro WHERE IdDepartUnid IN (SELECT IdDepartUnid FROM dbo.ServicioDepartUnidad WHERE DNIACCESO = @lcdni))
and DNI_RELOG is not null  
UNION ALL   
SELECT DNI, CODIGO, NOMBRE, DNI_RELOG, UNIDAD_ORGANICA  FROM V_MAESTRO WHERE CODUNIDADORG IN (SELECT CODIGO FROM [BDPERSONAL].[dbo].[DepartamentoUnidad] WHERE IdDepartUnid = (SELECT DISTINCT  IdDepartUnid FROM dbo.ServicioDepartUnidad WHERE DNIACCESO = @lcdni))
and DNI_RELOG is not null order by NOMBRE asc
SELECT DISTINCT DNI, CODIGO, NOMBRE, DNI_RELOG, UNIDAD_ORGANICA  FROM TMP_ASISMARCAS ORDER BY NOMBRE ASC
DROP TABLE TMP_ASISMARCAS

/* SELECT *  FROM V_MAESTRO */

