USE BDPERSONAL	
declare @lidmaster varchar(20 ) = 19
TRUNCATE TABLE [BDPERSONAL].[dbo].[TMP_INSTRUCCION]
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'E' AS INDICADOR, IDMASTER, ESTUDIO, CONDICION, DESDE, HASTA, CE, CARRERA, GRADO, ESPECIALIDAD, NRO_CARRERA_PROFESIONAL
 from [BDPERSONAL].[dbo].[LGJ_ESTUDIOS] where IDMASTER = @lidmaster ORDER BY CONVERT(DATETIME, DESDE, 101) ASC 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'T' AS INDICADOR, '' AS IDMASTER, '' AS ESTUDIO, '' AS CONDICION, '' AS DESDE, '' AS HASTA, '' AS CE, '' AS CARRERA, '' AS GRADO, '' AS ESPECIALIDAD, '' NRO_CARRERA_PROFESIONAL 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'T' AS INDICADOR, '' AS IDMASTER, 'CURSOS ' AS ESTUDIO, 'CAPACITACION' AS CONDICION, '' AS DESDE, '' AS HASTA, '' AS CE, '' AS CARRERA, '' AS GRADO, '' AS ESPECIALIDAD, '' NRO_CARRERA_PROFESIONAL 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'T' AS INDICADOR, '' AS IDMASTER, '-----------------------' AS ESTUDIO, '-------------' AS CONDICION, '------------' AS DESDE, '------------' AS HASTA, '----------' AS CE, '-----------' AS CARRERA, '---------------' AS GRADO, '--------------' AS ESPECIALIDAD, '-----------' NRO_CARRERA_PROFESIONAL 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'T' AS INDICADOR, '' AS IDMASTER, 'CONDICION ' AS ESTUDIO, 'EVENTO' AS CONDICION, 'INICIO' AS DESDE, 'FIN' AS HASTA, 'ENTIDAD ORGANIZADORA' AS CE, 'DESCRIPCION ' AS CARRERA, 'HORAS ACADEMICAS' AS GRADO, 'LUGAR' AS ESPECIALIDAD, '' NRO_CARRERA_PROFESIONAL 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
select 'T' AS INDICADOR, '' AS IDMASTER, '-----------------------' AS ESTUDIO, '-------------' AS CONDICION, '------------' AS DESDE, '------------' AS HASTA, '----------' AS CE, '-----------' AS CARRERA, '---------------' AS GRADO, '--------------' AS ESPECIALIDAD, '-----------' NRO_CARRERA_PROFESIONAL 
INSERT INTO [BDPERSONAL].[dbo].[TMP_INSTRUCCION]([INDICADOR],[IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD],[NRO_CARRERA_PROFESIONAL])
SELECT 'C' AS INDICADOR, IDMASTER, NOMBREEVENTO AS ESTUDIO,  NOMBREPARTICIPACION AS CONDICION, FECHAINICIO AS DESDE, FECHAFIN AS HASTA, ENTIDAD AS CE, DESCRIPCION AS CARRERA, HORASACADEMICAS  AS GRADO, LUGAR AS ESPECIALIDAD,
'' AS NRO_CARRERA_PROFESIONAL FROM [BDPERSONAL].[dbo].[LGJ_CAPACITACION] where idmaster = @lidmaster order by CONVERT(datetime, FECHAINICIO, 103)  desc
SELECT [INDICADOR], [IDMASTER],[ESTUDIO],[CONDICION],[DESDE],[HASTA],[CE],[CARRERA],[GRADO],[ESPECIALIDAD], [NRO_CARRERA_PROFESIONAL]  FROM [BDPERSONAL].[dbo].[TMP_INSTRUCCION]

