/* VER CLAVES DE USUARIO DE PERSONAL O ROL DE GUARDIAS */

USE SIGSALUD
SELECT DNI, NOMBRES, CLAVE FROM  USUARIO_WEB WHERE DNI IN (SELECT DISTINCT DNI FROM [SIGSALUD].[dbo].[ACCESO_MODULO] WHERE NOMBRE  = 'CONTROL DE ASISTENCIA')
 ORDER BY NOMBRES ASC