
     
     
SELECT MAESTRO.CODIGO, MAESTRO.PLAZA, MAESTRO.NOMBRE, MAESTRO.HABER, MAESTRO.CODHORA, T_Horarios.HORING, T_Horarios.HORSAL, T_Grupo.CODIGO AS GRUPO, T_Grupo.NOMBRE AS GRUPODES, 
 MAESTRO.NIVELGRD, MAESTRO.CODUNIDADORG, T_UnidadOrganica.NOMBRE AS UNIDAD, MAESTRO.CODFUNCION, T_CargoFuncional.NOMBRE AS FUNCION, MAESTRO.HORAS, MAESTRO.CODCARGO, T_CargoPresupuestal.NOMBRE AS CARGO, 
  MAESTRO.SITUACION, T_TipoSituacion.NOMBRE AS SITUACIONDES, MAESTRO.DNI, MAESTRO.CADENA,.MAESTRO.DNI_RELOG, MAESTRO.CODNIVEL,T_GuardiaNiv.Nombre AS GUARDIADES FROM T_CargoFuncional INNER JOIN 
   T_Grupo ON dbo.T_CargoFuncional.CODGRP = T_Grupo.CODIGO INNER JOIN T_TipoSituacion INNER JOIN T_TipoPlaza INNER JOIN T_UnidadOrganica INNER JOIN MAESTRO ON dbo.T_UnidadOrganica.CODIGO = dbo.MAESTRO.CODUNIDADORG ON dbo.T_TipoPlaza.CODIGO = dbo.MAESTRO.T_PLAZA ON 
    T_TipoSituacion.CODIGO = MAESTRO.SITUACION INNER JOIN T_Horarios ON MAESTRO.CODHORA = T_Horarios.CODHOR ON T_CargoFuncional.CODIGO = MAESTRO.CODFUNCION INNER JOIN T_CargoPresupuestal ON MAESTRO.CODCARGO = T_CargoPresupuestal.CODIGO INNER JOIN T_GuardiaNiv ON MAESTRO.NIVELGRD = T_GuardiaNiv.Codigo
     WHERE MAESTRO.CODIGO = '054172'     
     
          
     
SELECT MAESTRO.CODIGO, MAESTRO.PLAZA, MAESTRO.NOMBRE, MAESTRO.HABER, MAESTRO.CODHORA, T_Horarios.HORING, T_Horarios.HORSAL, T_Grupo.CODIGO AS GRUPO, T_Grupo.NOMBRE AS GRUPODES, 
 MAESTRO.NIVELGRD, MAESTRO.CODUNIDADORG, T_UnidadOrganica.NOMBRE AS UNIDAD, MAESTRO.CODFUNCION, T_CargoFuncional.NOMBRE AS FUNCION, MAESTRO.HORAS, MAESTRO.CODCARGO,
  T_CargoPresupuestal.NOMBRE AS CARGO, 
  MAESTRO.SITUACION, T_TipoSituacion.NOMBRE AS SITUACIONDES, MAESTRO.DNI, MAESTRO.CADENA,.MAESTRO.DNI_RELOG, MAESTRO.CODNIVEL,T_GuardiaNiv.Nombre AS GUARDIADES
  
   FROM T_CargoFuncional INNER JOIN 
   T_Grupo ON dbo.T_CargoFuncional.CODGRP = T_Grupo.CODIGO INNER JOIN T_TipoSituacion INNER JOIN T_TipoPlaza INNER JOIN T_UnidadOrganica INNER JOIN MAESTRO ON dbo.T_UnidadOrganica.CODIGO = dbo.MAESTRO.CODUNIDADORG ON dbo.T_TipoPlaza.CODIGO = dbo.MAESTRO.T_PLAZA ON 
    T_TipoSituacion.CODIGO = MAESTRO.SITUACION INNER JOIN T_Horarios ON MAESTRO.CODHORA = T_Horarios.CODHOR ON T_CargoFuncional.CODIGO = MAESTRO.CODFUNCION INNER JOIN T_CargoPresupuestal ON MAESTRO.CODCARGO = T_CargoPresupuestal.CODIGO INNER JOIN T_GuardiaNiv ON MAESTRO.NIVELGRD = T_GuardiaNiv.Codigo
     WHERE MAESTRO.CODIGO = '054172'     