use BDPERSONAL
		 SELECT MAESTRO.CODIGO, MAESTRO.NOMBRE, DNI, UPPER((SELECT T_CargoFuncional.NOMBRE FROM T_CARGOFUNCIONAL WHERE MAESTRO.CODFUNCION= T_CARGOFUNCIONAL.CODIGO)) AS CARGO1,
		    (SELECT TIPO FROM T_GRUPO WHERE CODIGO = (SELECT CODGRP FROM T_CargoFuncional WHERE CODIGO = CODFUNCION)) AS TIPO_TRABAJADOR,
		   CODHORA, CODTAR, HABER, HORAS, DNI_RELOG, (CASE WHEN ((SELECT TIPO FROM T_GRUPO WHERE CODIGO = (SELECT CODGRP FROM T_CargoFuncional WHERE CODIGO = CODFUNCION)))= 'S' THEN HABER/180 ELSE HABER/240 END) AS COSTO_HORA, CODNIVEL
		        FROM MAESTRO WHERE LEN(CODFUNCION) = 4 AND SITUACION IN ('01','03','04') and  codigo = '084008'


select * from maestro where codigo = '084008'

(SELECT TIPO FROM T_GRUPO WHERE CODIGO = (SELECT CODGRP FROM T_CargoFuncional WHERE CODIGO = CODFUNCION)) AS TIPO_TRABAJADOR


select 0038

SELECT * FROM T_CargoFuncional WHERE CODIGO =  '0038'
SELECT * FROM T_GRUPO where codigo = '06'
SELECT TIPO FROM T_GRUPO WHERE CODIGO = '0038'
