INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO]([CONSULTORIO],[NOMBRE],[ABREVIATURA],[ESPECIALIDAD],[TIPO],[ROL],[MUESTRAROL],[CC1],[CC2],[CC3],[ACTIVO],[ORDEN],[NUMERO],[CUPO],[CODESPE],[NOMESPE],[HIS_ESPECIALIDAD],
   [ACTIVO_WEB],[COD_RENAES],[DESC_RENAES],[HIS_CODSERVICIO],[HIS_NOMSERVICIO],[SCONSULTORIO],[SCCONSULTORIO],[ECONSULTORIO],[ECCONSULTORIO],[DEPARTAMENTO],[TIPOSERVICIO],[CODUPSSEEM])
SELECT '9066' AS CONSULTORIO, 'NST-MONITOREO FETAL' AS NOMBRE, 'NST' AS ABREVIATURA,[ESPECIALIDAD],[TIPO],[ROL],[MUESTRAROL],[CC1],[CC2],[CC3],[ACTIVO],[ORDEN],[NUMERO],[CUPO],[CODESPE],[NOMESPE],[HIS_ESPECIALIDAD],[ACTIVO_WEB],[COD_RENAES],[DESC_RENAES],[HIS_CODSERVICIO],
   [HIS_NOMSERVICIO],[SCONSULTORIO],[SCCONSULTORIO],[ECONSULTORIO],[ECCONSULTORIO],[DEPARTAMENTO],[TIPOSERVICIO],[CODUPSSEEM] FROM [SIGSALUD].[dbo].[CONSULTORIO] where CONSULTORIO = '9060'
   
USE SIGSALUD
update CONSULTORIO set tipo = '9' where CONSULTORIO = '9030'