SELECT * FROM  [SIGSALUD].[dbo].[ROLACTIVIDAD] WHERE PERIODO = '201605' AND CONSULTORIO = '2025'
SELECT * FROM dbo.ROLACTIVIDAD  WHERE PERIODO = '201605' AND CONSULTORIO = '2025'
SELECT * FROM dbo.ROLACTIVIDADC WHERE PERIODO = '201605' AND SERVICIO = '20' 
SELECT * FROM dbo.ROLACTIVIDAD WHERE PERIODO = '201605' AND SERVICIO = '20' AND CONSULTORIO = '2025'
SELECT * FROM dbo.ROLREPROGRAMACION WHERE CONSULTORIO = '2025'



SELECT * FROM CONSULTORIO

  SELECT * FROM ROLACTIVIDAD WHERE PERIODO='201507' AND CONSULTORIO='1028' AND TURNO_CONSULTA='T'