USE SIGSALUD
declare @lcnombre varchar(200) = 'GARCIA MACHUCA YVAN'
TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN ADMISION, TABLA PACIENTE' AS UBICACION, PACIENTE, HISTORIA, NOMBRES FROM PACIENTE  WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN CITAS, TABLA CITA' AS UBICACION, PACIENTE, '' as HISTORIA, NOMBRE AS NOMBRES FROM CITA WHERE NOMBRE LIKE  '%' + @lcnombre + '%' 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN EMERGENCIA, TABLA EMERGENCIA' AS UBICACION, PACIENTE, HISTORIA, NOMBRES FROM EMERGENCIA  WHERE NOMBRES LIKE '%' + @lcnombre + '%'   

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN ATENCION SIS,  TABLA ATENCION_SEGURO' AS UBICACION, PACIENTE, HISTORIA, NOMBRES  FROM ATENCION_SEGURO  WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN ATENCION ARCHIVOS, TABLA ARCHIVO_MOV' AS UBICACION, PACIENTE, HISTORIA, NOMBRES  FROM ARCHIVO_MOV   WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN ATENCION CAJA, TABLA PAGOC' AS UBICACION, PACIENTE, '' AS HISTORIA, NOMBRE AS NOMBRES  FROM PAGOC   WHERE NOMBRE LIKE  '%' + @lcnombre + '%' 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 

INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
SELECT 'EN CONSULTORIO, TABLA ATENCIONC' AS UBICACION, PACIENTE, '' AS HISTORIA, NOMBRES  FROM ATENCIONC   WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 

SELECT UBICACION, PACIENTE, HISTORIA, NOMBRES FROM  [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]

