USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_BUSCAR_HISTORIA]    Script Date: 10/10/2016 16:11:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_BUSCAR_HISTORIA](
	[UBICACION] [varchar](150) NULL,
	[PACIENTE] [varchar](150) NULL,
	[HISTORIA] [varchar](150) NULL,
	[NOMBRES] [varchar](150) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


