
  -- declare @lcnombre varchar(200) = ?lcpaciente
  
  declare @lcnombre varchar(200) = 'SOTO SANCHEZ '
  
  
  TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN ADMISION, TABLA PACIENTE' AS UBICACION, PACIENTE, HISTORIA, NOMBRES FROM [SIGSALUD].[dbo].[PACIENTE]  WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN CITAS, TABLA CITA' AS UBICACION, PACIENTE, '' as HISTORIA, NOMBRE AS NOMBRES FROM [SIGSALUD].[dbo].[CITA] WHERE NOMBRE LIKE  '%' + @lcnombre + '%' 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN EMERGENCIA, TABLA EMERGENCIA' AS UBICACION, PACIENTE, HISTORIA, NOMBRES FROM [SIGSALUD].[dbo].[EMERGENCIA]  WHERE NOMBRES LIKE '%' + @lcnombre + '%'   
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN ATENCION SIS,  TABLA ATENCION_SEGURO' AS UBICACION, PACIENTE, HISTORIA, NOMBRES  FROM [SIGSALUD].[dbo].[ATENCION_SEGURO]  WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN ATENCION ARCHIVOS, TABLA ARCHIVO_MOV' AS UBICACION, PACIENTE, HISTORIA, NOMBRES  FROM [SIGSALUD].[dbo].[ARCHIVO_MOV]   WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN ATENCION CAJA, TABLA PAGOC' AS UBICACION, PACIENTE, '' AS HISTORIA, NOMBRE AS NOMBRES  FROM [SIGSALUD].[dbo].[PAGOC]  WHERE NOMBRE LIKE  '%' + @lcnombre + '%' 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT '-----------------------------' AS UBICACION, '---------------' PACIENTE, '------------------------' as HISTORIA, '---------------------' AS NOMBRES 
  INSERT INTO [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]([UBICACION],[PACIENTE],[HISTORIA],[NOMBRES])
  SELECT 'EN CONSULTORIO, TABLA ATENCIONC' AS UBICACION, PACIENTE, '' AS HISTORIA, NOMBRES  FROM [SIGSALUD].[dbo].[ATENCIONC]   WHERE NOMBRES LIKE  '%' + @lcnombre + '%' 
  SELECT UBICACION, PACIENTE, HISTORIA, NOMBRES FROM  [SIGSALUD].[dbo].[TMP_BUSCAR_HISTORIA]