SELECT PACIENTE, HISTORIA, PATERNO, MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, HORA_APERTURA, PADRE, MADRE, HIJOS, DIRECCION, DISTRITO, LOCALIDAD,
TELEFONO1, TELEFONO2, EMAIL, LUGAR_NACIMIENTO, EDAD, TIPO_DOCUMENTO, DOCUMENTO, PAIS, OCUPACION, GRADO_INSTRUCCION, CONYUGE_NOMBRE, CONYUGE_OCUPACION,
RESPONSABLE_NOMBRE, RESPONSABLE_DIRECCION, RESPONSABLE_PARENTESCO, RESPONSABLE_TRABAJO, RESPONSABLE_OCUPACION, RESPONSABLE_OCUPACION, 
RESPONSABLE_TELEFONO, SEGURO, MEDICO, CONSULTORIO, CONSULTORIO_OLD, ENTIDAD, CIEX, CIEX_DESCRIPCION, RH, GRUPO_SANGUINEO, SYSINSERT, SYSUPDATE,
SYSDELETE, TURNO_CONSULTA  FROM PACIENTE WHERE NOMBRES LIKE 'PEREZ RUI%'



SELECT PACIENTE, HISTORIA, PATERNO, MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, HORA_APERTURA, PADRE, MADRE, HIJOS, DIRECCION, DISTRITO, LOCALIDAD,
TELEFONO1, TELEFONO2, EMAIL, LUGAR_NACIMIENTO, EDAD, TIPO_DOCUMENTO, DOCUMENTO, PAIS, OCUPACION, GRADO_INSTRUCCION, CONYUGE_NOMBRE, CONYUGE_OCUPACION,
RESPONSABLE_NOMBRE, RESPONSABLE_DIRECCION, RESPONSABLE_PARENTESCO, RESPONSABLE_TRABAJO, RESPONSABLE_OCUPACION, RESPONSABLE_OCUPACION, 
RESPONSABLE_TELEFONO, SEGURO, MEDICO, CONSULTORIO, CONSULTORIO_OLD, ENTIDAD, CIEX, CIEX_DESCRIPCION, RH, GRUPO_SANGUINEO, SYSINSERT, SYSUPDATE,
SYSDELETE, TURNO_CONSULTA  FROM PACIENTE WHERE PACIENTE = '2016261447'


SELECT PACIENTE, HISTORIA, PATERNO, MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, HORA_APERTURA, PADRE, MADRE, HIJOS, DIRECCION, DISTRITO, LOCALIDAD,
TELEFONO1, TELEFONO2, EMAIL, LUGAR_NACIMIENTO, EDAD, TIPO_DOCUMENTO, DOCUMENTO, PAIS, OCUPACION, GRADO_INSTRUCCION, CONYUGE_NOMBRE, CONYUGE_OCUPACION,
RESPONSABLE_NOMBRE, RESPONSABLE_DIRECCION, RESPONSABLE_PARENTESCO, RESPONSABLE_TRABAJO, RESPONSABLE_OCUPACION, RESPONSABLE_OCUPACION, 
RESPONSABLE_TELEFONO, SEGURO, MEDICO, CONSULTORIO, CONSULTORIO_OLD, ENTIDAD, CIEX, CIEX_DESCRIPCION, RH, GRUPO_SANGUINEO, SYSINSERT, SYSUPDATE,
SYSDELETE, TURNO_CONSULTA  FROM PACIENTE WHERE PACIENTE = '2016261447'


/*
use SIGSALUD
Declare @lultimo int
declare @lpaciente char(10)
declare @lhistoria  char(20)
select @lultimo = MAX(paciente) from paciente
set @lpaciente = (select CONVERT(int, paciente) + 1 as paci from PACIENTE where paciente = @lultimo)
set @lhistoria = (select CONVERT(int, historia) + 1 as histo from PACIENTE where paciente = @lultimo)

INSERT INTO [SIGSALUD].[dbo].[PACIENTE]([PACIENTE], [HISTORIA], [PATERNO], [MATERNO], [NOMBRE], [NOMBRES], [SEXO], [ESTADO_CIVIL], [FECHA_APERTURA], [HORA_APERTURA], [PADRE], 
  [MADRE], [HIJOS], [DIRECCION], [DISTRITO], [LOCALIDAD], [TELEFONO1],[TELEFONO2],[EMAIL],[LUGAR_NACIMIENTO],[FECHA_NACIMIENTO],[EDAD],[TIPO_DOCUMENTO],[DOCUMENTO],[PAIS],[OCUPACION],
  [GRADO_INSTRUCCION],[CONYUGE_NOMBRE],[CONYUGE_OCUPACION],[RESPONSABLE_NOMBRE],[RESPONSABLE_DIRECCION],[RESPONSABLE_PARENTESCO],[RESPONSABLE_TRABAJO],[RESPONSABLE_OCUPACION],
  [RESPONSABLE_TELEFONO],[SEGURO],[MEDICO],[CONSULTORIO],[CONSULTORIO_OLD],[ENTIDAD],[CIEX],[CIEX_DESCRIPCION],[RH],[GRUPO_SANGUINEO],[ANIO],[SYSINSERT],[SYSUPDATE],
  [SYSDELETE],[TURNO_CONSULTA],[FECHA_CONSULTA],[fecharegistro])
  
VALUES (@lpaciente, @lhistoria, 'PATERNO', 'MATERNO', 'NOMBRE', 'PATERNO MATERNO NOMBRES', 'M','S', convert(datetime,CONVERT(varchar(10), GETDATE(), 103),103), convert(char(8), CONVERT(TIME, GETDATE())),
 'PADRES', 'MADRES', 1, 'AV. DIRECCION', '150118', 'L01', '999999999', '999999999', 'personal@empresa.com.pe', '150101', CONVERT(datetime, GETDATE(),103), '034a09m16d', 'D', '99999999', '146', '01',
 '05', 'NOMBRE CONYUGUE', '05', 'RESPONSABLE NOMBRE', 'RESPONSABLE DIRECCION', 'RESPONSABLE PARENTESCO', 'RESPONSABLE TRABAJO', 'RESPONSABLE OCUPACION', 'RESPONSABLE TELEFONO', '0', '0', '0', '0', '210',
'0', ' ', '0', '00000', '2016', CONVERT(VARCHAR(50), GETDATE()), CONVERT(VARCHAR(50), GETDATE()), CONVERT(VARCHAR(50), GETDATE()), 'T', GETDATE(), GETDATE())
*/



use SIGSALUD
Declare @lultimo int
declare @lpaciente char(10)
declare @lhistoria  char(20)
select @lultimo = MAX(paciente) from paciente
set @lpaciente = (select CONVERT(int, paciente) + 1 as paci from PACIENTE where paciente = @lultimo)
set @lhistoria = (select CONVERT(int, historia) + 1 as histo from PACIENTE where paciente = @lultimo)

INSERT INTO [SIGSALUD].[dbo].[PACIENTE]([PACIENTE], [HISTORIA], [PATERNO], [MATERNO], [NOMBRE], [NOMBRES], [SEXO], [ESTADO_CIVIL], [FECHA_APERTURA], [HORA_APERTURA], [PADRE], 
  [MADRE], [HIJOS], [DIRECCION], [DISTRITO], [LOCALIDAD], [TELEFONO1],[TELEFONO2],[EMAIL],[LUGAR_NACIMIENTO],[FECHA_NACIMIENTO],[EDAD],[TIPO_DOCUMENTO],[DOCUMENTO],[PAIS],[OCUPACION],
  [GRADO_INSTRUCCION],[CONYUGE_NOMBRE],[CONYUGE_OCUPACION],[RESPONSABLE_NOMBRE],[RESPONSABLE_DIRECCION],[RESPONSABLE_PARENTESCO],[RESPONSABLE_TRABAJO],[RESPONSABLE_OCUPACION],
  [RESPONSABLE_TELEFONO],[SEGURO],[MEDICO],[CONSULTORIO],[CONSULTORIO_OLD],[ENTIDAD],[CIEX],[CIEX_DESCRIPCION],[RH],[GRUPO_SANGUINEO],[ANIO],[SYSINSERT],[SYSUPDATE],
  [SYSDELETE],[TURNO_CONSULTA],[FECHA_CONSULTA],[fecharegistro])
  
VALUES (@lpaciente, @lhistoria, 'PATERNO', 'MATERNO', 'NOMBRE', 'PATERNO MATERNO NOMBRES', 'M','S', GETDATE(), convert(char(8), CONVERT(TIME, GETDATE())),

 'PADRES', 'MADRES', 1, 'AV. DIRECCION', '150118', 'L01', '999999999', '999999999', 'personal@empresa.com.pe', '150101', CONVERT(datetime, GETDATE(),103), '034a09m16d', 'D', '99999999', '146', '01',
 '05', 'NOMBRE CONYUGUE', '05', 'RESPONSABLE NOMBRE', 'RESPONSABLE DIRECCION', 'RESPONSABLE PARENTESCO', 'RESPONSABLE TRABAJO', 'RESPONSABLE OCUPACION', 'RESPONSABLE TELEFONO', '0', '0', '0', '0', '210',
'0', ' ', '0', '00000', '2016', CONVERT(VARCHAR(50), GETDATE()), CONVERT(VARCHAR(50), GETDATE()), CONVERT(VARCHAR(50), GETDATE()), 'T', GETDATE(), GETDATE())




use SIGSALUD
Declare @lultimo int
declare @lpaciente char(10)
declare @lhistoria  char(20)
select @lultimo = MAX(paciente) from paciente
set @lpaciente = (select CONVERT(int, paciente) + 1 as paci from PACIENTE where paciente = @lultimo)
set @lhistoria = (select CONVERT(int, historia) + 1 as histo from PACIENTE where paciente = @lultimo)

/* select @lpaciente, @lhistoria */
 /* select * from PACIENTE where PACIENTE = '2016262120'  */
/* delete from PACIENTE where PACIENTE = '2016262120' */

INSERT INTO [SIGSALUD].[dbo].[PACIENTE]([PACIENTE], [HISTORIA], [PATERNO], [MATERNO], [NOMBRE], [NOMBRES], [SEXO], [ESTADO_CIVIL], [FECHA_APERTURA], [HORA_APERTURA], 
[PADRE], [MADRE], [HIJOS], [DIRECCION], [DISTRITO], [LOCALIDAD], [TELEFONO1],[TELEFONO2],[EMAIL],[LUGAR_NACIMIENTO],[FECHA_NACIMIENTO],[EDAD],[TIPO_DOCUMENTO],[DOCUMENTO],[PAIS],[OCUPACION],
  [GRADO_INSTRUCCION], [CONYUGE_NOMBRE],[CONYUGE_OCUPACION], [RESPONSABLE_NOMBRE],[RESPONSABLE_DIRECCION],[RESPONSABLE_PARENTESCO],[RESPONSABLE_TRABAJO],[RESPONSABLE_OCUPACION], [RESPONSABLE_TELEFONO],
   [SEGURO],[MEDICO],[CONSULTORIO],[CONSULTORIO_OLD],[ENTIDAD],[CIEX],[CIEX_DESCRIPCION],[RH],[GRUPO_SANGUINEO],[ANIO],
   [SYSINSERT],[SYSUPDATE],[SYSDELETE],[TURNO_CONSULTA],[FECHA_CONSULTA],[fecharegistro])  
VALUES (@lpaciente, @lhistoria, 'PATERNO', 'MATERNO', 'NOMBRE', 'PATERNO MATERNO NOMBRES', 'M','S', GETDATE(), convert(char(8), CONVERT(TIME, GETDATE())),
'PADRES', 'MADRES', 1, 'AV. DIRECCION', '150118', 'L01', '999999999', '999999999', 'personal@empresa.com.pe', '150101', CONVERT(datetime, GETDATE(),103), '034a09m16d', 'D', '99999999', '146', '01',
'99', 'NOMBRE CONYUGUE', '05', 'RESPONSABLE NOMBRE', 'RESPONSABLE DIRECCION', 'RESPONSABLE PARENTESCO', 'RESPONSABLE TRABAJO', 'RESPONSABLE OCUPACION', '999999999',
 '0', 'CLE', '2052', '2052', '210', '000', ' ', '0', '00000', '2016',
 CONVERT(VARCHAR(100), GETDATE()), CONVERT(VARCHAR(100), GETDATE()), CONVERT(VARCHAR(100), GETDATE()), 'M', GETDATE(), GETDATE())



SELECT * FROM PACIENTE WHERE PACIENTE = '2015254320'
SELECT PACIENTE FROM PACIENTE WHERE fecharegistro IS NOT NULL AND PACIENTE NOT IN ('2016261447', '2016258646') ORDER BY PATERNO, MATERNO ASC
SELECT * FROM PACIENTE WHERE fecharegistro IS NOT NULL ORDER BY PATERNO, MATERNO ASC



USE SIGSALUD
UPDATE PACIENTE SET ESTADO_CIVIL = 'S', HIJOS = 0, DIRECCION = 'MODIFICAR', TELEFONO1 = '999999999', TELEFONO2 = '999999999', EMAIL = 'personal@empresa.com.pe',
   LUGAR_NACIMIENTO = '150101', DOCUMENTO = '99999999', OCUPACION = '01', GRADO_INSTRUCCION = '01', CONYUGE_NOMBRE = 'MODIFICAR', CONYUGE_OCUPACION = '05', RESPONSABLE_NOMBRE = 'MODIFICAR',
   RESPONSABLE_DIRECCION = 'MODIFICAR', RESPONSABLE_PARENTESCO = 'MODIFICAR', RESPONSABLE_TRABAJO = 'MODIFICAR', RESPONSABLE_OCUPACION = 'MODIFICAR', RESPONSABLE_TELEFONO = '99999999',
   SEGURO = '06', MEDICO = 'MED', ENTIDAD = '210', CIEX = '000', CIEX_DESCRIPCION = '', RH = '0', GRUPO_SANGUINEO = '0000', ANIO = '2016', SYSUPDATE = CONVERT(VARCHAR(100), GETDATE(),103),
   SYSDELETE =  '', TURNO_CONSULTA = 'M', FECHA_CONSULTA = '', USUARIO = 'AJARA', DISTRITON = '1253', LNACIMIENTON = '197'  WHERE PACIENTE = '2015254320'


/* FINAL
USE SIGSALUD
  UPDATE PACIENTE SET ESTADO_CIVIL = 'S', HIJOS = 0, DIRECCION = 'MODIFICAR', TELEFONO1 = '999999999', TELEFONO2 = '999999999', EMAIL = 'personal@empresa.com.pe',
   LUGAR_NACIMIENTO = '150101', DOCUMENTO = '99999999', OCUPACION = '01', GRADO_INSTRUCCION = '01', CONYUGE_NOMBRE = 'MODIFICAR', CONYUGE_OCUPACION = '05', RESPONSABLE_NOMBRE = 'MODIFICAR',
   RESPONSABLE_DIRECCION = 'MODIFICAR', RESPONSABLE_PARENTESCO = 'MODIFICAR', RESPONSABLE_TRABAJO = 'MODIFICAR', RESPONSABLE_OCUPACION = 'MODIFICAR', RESPONSABLE_TELEFONO = '99999999',
   SEGURO = '06', MEDICO = 'CLE', ENTIDAD = '210', CIEX = '000', CIEX_DESCRIPCION = '', RH = '0', GRUPO_SANGUINEO = '0000', ANIO = '2016', SYSUPDATE = CONVERT(VARCHAR(100), GETDATE(),103),
   SYSDELETE =  '', TURNO_CONSULTA = 'M', FECHA_CONSULTA = '', USUARIO = 'MMOSCOSO', DISTRITON = '1253', LNACIMIENTON = '197'  WHERE PACIENTE IN (SELECT PACIENTE FROM PACIENTE WHERE fecharegistro IS NOT NULL AND PACIENTE NOT IN ('2016261447', '2016258646')) 

FINAL */

   

 
select PACIENTE, HISTORIA, NOMBRES, [SEGURO],[MEDICO],[CONSULTORIO],[CONSULTORIO_OLD],[ENTIDAD],[CIEX],[CIEX_DESCRIPCION],[RH],[GRUPO_SANGUINEO],[ANIO]
 from PACIENTE
where NOMBRES like 'OBESO CAMO%'


SELECT * FROM USUARIO WHERE USUARIO = 'CESPINOZA'