/* REPORTE ALEXANDRA ESTADISTICA */
/* **************************** */

use sigsalud
DECLARE @lcfecha1 DATETIME = CONVERT(DATETIME, '2016-12-01', 101)
DECLARE @lcfecha2 DATETIME = CONVERT(DATETIME, '2016-12-31', 101)

SELECT 'MEDICINA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('01', '15', '03')  GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA SIS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('01', '15', '03') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
/** PARA SOAT **/
SELECT 'MEDICINA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA SOAT' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('02') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL 

/** PARA ESSALUD **/
SELECT 'MEDICINA ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  ESSALUD' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('06') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL
/** PARA MILITAR **/
SELECT 'MEDICINA MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  MILITAR' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('07', '10', '11','12') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 

UNION ALL
/** OTROS  **/
SELECT 'MEDICINA OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '1050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'CIRUGIA OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'TRAUMATOLOGIA  OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '2051'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'PEDIATRIA  OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '3050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'GINECOLOGIA  OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4050'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
UNION ALL
SELECT 'OBSTETRICIA  OTROS' AS descripcion, COUNT(EMERGENCIA_ID) AS cantidad FROM EMERGENCIA 
WHERE FECHA BETWEEN  @lcfecha1 AND @lcfecha2 AND CONSULTORIO = '4060'
AND SEGURO IN ('09', '05', '14', '16', '04', '13', '0', '08') AND ESTADO > 0 AND CIEX1 > '0' GROUP BY CONSULTORIO 
 