USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TRANGO]    Script Date: 09/04/2015 08:40:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TRANGO](
	[idrango] [int] IDENTITY(1,1) NOT NULL,
	[csexo] [varchar](2) NULL,
	[crango] [varchar](2) NULL,
	[ntotal] [int] NULL,
	[FECHAREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TRANGO] PRIMARY KEY CLUSTERED 
(
	[idrango] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


