USE SIGSALUD

/* ITEM POR HOSPITALIZACION */
/* INGRESAR FECHA INICIO, FINAL */
/* ITEM */
/* CONSULTORIO HOSPITALIZACION */

DECLARE @litem varchar(13) = '170753'
declare @lfechainicio datetime = convert(datetime, '2016-11-01', 101)
declare @lfechafin datetime = convert(datetime, '2016-11-30', 101)

declare @lfechainicio2 VARCHAR(10) = '01/11/2016'
declare @lfechafin2 VARCHAR(10) = '30/11/2016'



/* SELECT item, upper(nombre) FROM ITEM WHERE NOMBRE LIKE '%ACICLO%' and substring(item,1,2) = '17' */
/*  PRIMER ITEM : AMPICILINA : 170175 */

/* SEHGUNDO ITEM, TIENE DOS CODIGOS: 170201, 170202 */       

/* CEFOPTAXIMA : 170083 */

/* Ciprofloxacino 200mg/100ml : 170232     */

/* CILASTATINA + IMIPENEM 500MG + 500MG INY : 170753     */

/* MEROPENEM 500 MG INY  : 171178 */

/* METRONIDAZOL  : 170277    */

/* VANCOMICINA   : 170239        */
INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_PACIENTES]([FECHA_INICIO], [FECHA_FIN], [ORDENID], [ITEM], [NOMBRE], [PRESENTACION], [CANTIDAD], [PRECIO], [DESCUENTO], [IMPORTE], [NOMBRE_PACIENTE], [NOMBRE_MEDICO], [NOMBRE_CONSULTORIO], [TIPO_CONSULTORIO], FECHA)
SELECT @lfechainicio2, @lfechafin2, ORDENID, ITEM, NOMBRE, PRESENTACION, CANTIDAD, PRECIO, DESCUENTO, IMPORTE, NOMBRE_PACIENTE, NOMBRE_MEDICO, NOMBRE_CONSULTORIO, TIPO_CONSULTORIO FROM V_ORDEND 
WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN @lfechainicio  AND @lfechafin)
   AND  TIPO_CONSULTORIO = 'H'  AND ESTADO = '3' AND ITEM = @litem ORDER BY NOMBRE_PACIENTE  ASC

INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_PACIENTES]([FECHA_INICIO], [FECHA_FIN], [ORDENID], [ITEM], [NOMBRE], [PRESENTACION], [CANTIDAD], [PRECIO], [DESCUENTO], [IMPORTE], [NOMBRE_PACIENTE], [NOMBRE_MEDICO], [NOMBRE_CONSULTORIO], [TIPO_CONSULTORIO])
SELECT @lfechainicio2, @lfechafin2, ORDENID, ITEM, NOMBRE, PRESENTACION, CANTIDAD, PRECIO, DESCUENTO, IMPORTE, NOMBRE_PACIENTE, NOMBRE_MEDICO, NOMBRE_CONSULTORIO, TIPO_CONSULTORIO  FROM V_ORDEND 
WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN @lfechainicio  AND @lfechafin)
   AND  TIPO_CONSULTORIO = 'C'  AND ESTADO = '3' AND ITEM = @litem ORDER BY NOMBRE_PACIENTE  ASC

INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_PACIENTES]([FECHA_INICIO], [FECHA_FIN], [ORDENID], [ITEM], [NOMBRE], [PRESENTACION], [CANTIDAD], [PRECIO], [DESCUENTO], [IMPORTE], [NOMBRE_PACIENTE], [NOMBRE_MEDICO], [NOMBRE_CONSULTORIO], [TIPO_CONSULTORIO])
SELECT @lfechainicio2, @lfechafin2, ORDENID, ITEM, NOMBRE, PRESENTACION, CANTIDAD, PRECIO, DESCUENTO, IMPORTE, NOMBRE_PACIENTE, NOMBRE_MEDICO, NOMBRE_CONSULTORIO, TIPO_CONSULTORIO  FROM V_ORDEND 
WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN @lfechainicio  AND @lfechafin)
   AND  TIPO_CONSULTORIO = 'E'  AND ESTADO = '3' AND ITEM = @litem ORDER BY NOMBRE_PACIENTE  ASC


INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_RESUMEN]([ITEM],[NOMBRE],[TIPO],[SERVICIO],[TOTAL],[IMPORTE_TOTAL])
SELECT @litem , 'PRIMERO', 'H', 'HOSPITALIZACION ' AS SERVICIO, SUM(CANTIDAD) AS TOTAL, SUM(IMPORTE) AS IMPORTE_TOTAL FROM V_ORDEND
 WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN  @lfechainicio  AND @lfechafin) 
      AND  TIPO_CONSULTORIO = 'H'  AND ESTADO = '3' AND ITEM = @litem GROUP BY ITEM 

INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_RESUMEN]([ITEM],[NOMBRE],[TIPO],[SERVICIO],[TOTAL],[IMPORTE_TOTAL])
SELECT @litem , 'PRIMERO', 'C', ' CONSULTORIO ' AS SERVICIO, SUM(CANTIDAD) AS TOTAL, SUM(IMPORTE) AS IMPORTE_TOTAL FROM V_ORDEND
 WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN  @lfechainicio  AND @lfechafin) 
      AND  TIPO_CONSULTORIO = 'C'  AND ESTADO = '3' AND ITEM = @litem GROUP BY ITEM 

INSERT INTO [SIGSALUD].[dbo].[TMP_ATM_RESUMEN]([ITEM],[NOMBRE],[TIPO],[SERVICIO],[TOTAL],[IMPORTE_TOTAL])
SELECT @litem, 'PRIMERO', 'E', ' EMERGENCIA ' AS SERVICIO, SUM(CANTIDAD) AS TOTAL, SUM(IMPORTE) AS IMPORTE_TOTAL FROM V_ORDEND
 WHERE ORDENID IN (SELECT ORDENID FROM V_ORDENC WHERE FECHA BETWEEN  @lfechainicio  AND @lfechafin) 
      AND  TIPO_CONSULTORIO = 'E'  AND ESTADO = '3' AND ITEM = @litem GROUP BY ITEM 

 /***************************************************************************************************************************************/
 
SELECT * FROM dbo.TMP_ATM_PACIENTES
SELECT * FROM dbo.TMP_ATM_RESUMEN group by nombre
 
 
 /* ver relacion de pacientes */
 
 SELECT FECHA, UPPER(nombre) AS NOMBRE, cantidad, PRECIO, DESCUENTO, importe, nombre_paciente, nombre_medico, nombre_consultorio FROM dbo.TMP_ATM_PACIENTES order by FECHA asc
 
 SELECT FECHA, UPPER(nombre) AS NOMBRE, cantidad, PRECIO, DESCUENTO, importe, nombre_paciente, nombre_medico, nombre_consultorio FROM dbo.TMP_ATM_PACIENTES order by NOMBRE_MEDICO asc
 
 select * from v_ORDEND
 
 
 
 /* reporte 1 */
 SELECT ITEM, nombre, SUM(TOTAL) AS CANTIDAD_TOTAL FROM dbo.TMP_ATM_RESUMEN GROUP BY ITEM, nombre   ORDER BY SUM(TOTAL)  DESC
 
 
 /* reporte 2 */
  SELECT SUM(importe_total) AS importe FROM dbo.TMP_ATM_RESUMEN GROUP BY ITEM
  
  /* reportre 3 */

SELECT count(tipo_consultorio) as CONTAR  FROM dbo.TMP_ATM_PACIENTES where tipo_consultorio = 'C' group by tipo_consultorio 


  /* reportre 4 */
SELECT * FROM dbo.TMP_ATM_PACIENTES where tipo_consultorio = 'H'



SELECT nombre_paciente FROM dbo.TMP_ATM_PACIENTES where tipo_consultorio = 'H' group by nombre_paciente
 
 
 
 