INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'TCASTRO' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'YNIEBUHR' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'


INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'RRIOS' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

DELETE FROM USUARIOD where USUARIO = 'MCALDERON' and MODULO = 'farmacia'

INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'MCALDERON' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'


INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'JALIAGA' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'JANYACO' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'NMARTINEZ' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

INSERT INTO [SIGSALUD].[dbo].[USUARIOD]([MODULO],[USUARIO],[MENU],[BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12])
select MODULO, 'KTAFUR' AS USUARIO, MENU, [BOTON1],[BOTON2],[BOTON3],[BOTON4],[BOTON5],[BOTON6],[BOTON7],[BOTON8],[BOTON9],[BOTON10],[BOTON11],[BOTON12] from USUARIOD where USUARIO = 'mchau' and MODULO = 'farmacia'

select * from USUARIOD where USUARIO = 'KTAFUR' and MODULO = 'farmacia'

DELETE FROM USUARIOD where USUARIO = 'KTAFUR' and MODULO = 'farmacia'

