USE SIGSALUD
/* fecha 16/10/2017 */


SELECT * FROM [SIGSALUD].[dbo].[TRANSFERENCIAC] WHERE TRANSFERENCIAID = '17000858'
SELECT * FROM [SIGSALUD].[dbo].[TRANSFERENCIAD] WHERE TRANSFERENCIAID = '17000858' ORDER BY ITEM DESC

SELECT * FROM [SIGSALUD].[dbo].[KARDEX] WHERE IDTRANSACCION = '17000858' AND ALMACEN = 'F' AND
TIPO_TRANSACCION = 'ITR'


declare @lcidtransferencia varchar(13) = '17000858'
declare @lcalmacen_origen varchar(2) = 'F'
declare @lcalmacen_destino varchar(2) = 'C'

SELECT * FROM [SIGSALUD].[dbo].[KARDEX] WHERE IDTRANSACCION = @lcidtransferencia AND ALMACEN = @lcalmacen_origen AND TIPO_TRANSACCION = 'ITR'


SELECT * FROM [SIGSALUD].[dbo].[KARDEX] WHERE IDTRANSACCION = '17000858' AND ALMACEN = 'F' AND
TIPO_TRANSACCION = 'ITR' AND ITEM = '170087'

SELECT * FROM STOCK WHERE ITEM = '171222' AND ALMACEN = 'F'
