/* PROCEDMIENTO PARA ELIMINAR LOS INGRESOS POR EQWUIVOCCION D EL DRA. ANGELICA */

use sigsalud	
declare @lidtransaccion varchar(13) = '17000048'

SELECT * FROM INGRESOC WHERE INGRESOID = @lidtransaccion
SELECT * FROM INGRESOD WHERE INGRESOID = @lidtransaccion

DELETE FROM INGRESOD WHERE INGRESOID = @lidtransaccion
DELETE FROM INGRESOC WHERE INGRESOID = @lidtransaccion


