USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_ATM_RESUMEN]    Script Date: 12/14/2016 19:39:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_ATM_RESUMEN](
	[IDATMRESUMEN] [int] IDENTITY(1,1) NOT NULL,
	[ITEM] [varchar](13) NULL,
	[NOMBRE] [varchar](150) NULL,
	[TIPO] [varchar](1) NULL,
	[SERVICIO] [varchar](17) NOT NULL,
	[TOTAL] [numeric](38, 2) NULL,
	[IMPORTE_TOTAL] [numeric](38, 3) NULL,
 CONSTRAINT [PK_TMP_ATM_RESUMEN] PRIMARY KEY CLUSTERED 
(
	[IDATMRESUMEN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


