USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_PREPEDIDO_FARMACIA]    Script Date: 11/14/2017 12:31:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_PREPEDIDO_FARMACIA](
	[ALMACEN] [varchar](150) NULL,
	[NOMBRE] [varchar](250) NULL,
	[INICIO] [int] NULL,
	[SALIDA] [int] NULL,
	[STOCK_FINAL_DIA] [int] NULL,
	[STOCK_ACTUAL] [int] NULL,
	[STOCK_ALMACEN] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


