USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_ATM_PACIENTES]    Script Date: 12/14/2016 19:38:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_ATM_PACIENTES](
	[IDATM] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_INICIO] [varchar](10) NULL,
	[FECHA_FIN] [varchar](10) NULL,
	[ORDENID] [char](10) NOT NULL,
	[ITEM] [char](10) NOT NULL,
	[NOMBRE] [varchar](250) NULL,
	[PRESENTACION] [char](10) NULL,
	[CANTIDAD] [numeric](10, 2) NOT NULL,
	[PRECIO] [numeric](18, 5) NOT NULL,
	[DESCUENTO] [numeric](18, 3) NOT NULL,
	[IMPORTE] [numeric](18, 3) NOT NULL,
	[NOMBRE_PACIENTE] [varchar](80) NOT NULL,
	[NOMBRE_MEDICO] [varchar](50) NOT NULL,
	[NOMBRE_CONSULTORIO] [varchar](50) NOT NULL,
	[TIPO_CONSULTORIO] [char](2) NOT NULL,
	[FECHA] [datetime] NULL,
 CONSTRAINT [PK_TMP_ATM_PACIENTES] PRIMARY KEY CLUSTERED 
(
	[IDATM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


