/* FARMACIA PROBLEMA D EPRECIO */


select * from STOCK where ITEM = '171262 '

select * from item where ITEM = '171262 '

select * from kardex  where ITEM = '171262 ' and almacen = 'A' order by OPERACION desc

select * from kardex  where ITEM = '171262 ' and almacen = 'F' order by OPERACION desc


SELECT PRECIO FROM PRECIO WHERE  ITEM = '171262' ORDER BY IDRECORD DESC

SELECT PRECIO FROM PRECIO WHERE  ITEM = '171215' ORDER BY IDRECORD DESC

SELECT PRECIO FROM PRECIO WHERE  ITEM = '170977' ORDER BY IDRECORD DESC

SELECT PRECIO FROM PRECIO WHERE  ITEM = '171180' ORDER BY IDRECORD DESC
