 SELECT * FROM Information_Schema.Columns WHERE TABLE_NAME = 'KARDEX' ORDER BY COLUMN_NAME
 
 SELECT  TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM Information_Schema.Columns WHERE TABLE_NAME = 'KARDEX' ORDER BY COLUMN_NAME