use SIGSALUD
DECLARE @lc_usuario varchar(13) = 'OVILLAGARY'
declare @lcfecha1 varchar(10) = '2017-08-01'
declare @lcfecha2 varchar(10) = '2017-08-31'
DECLARE @lcmes VARCHAR(13) = 'AGOSTO'
select @lcmes as MES, @lc_usuario USUARIO, UPPER(NOMBRE_TRANSACCION) NOMBRE_TRANSACCION, COUNT(NOMBRE_TRANSACCION) AS CANTI from V_ORDENC 
where USUARIO = @lc_usuario AND FECHA BETWEEN CONVERT(DATETIME, @lcfecha1, 101) AND CONVERT(DATETIME, @lcfecha2, 101)
GROUP BY NOMBRE_TRANSACCION 
UNION ALL
SELECT  @lcmes as MES, @lc_usuario USUARIO, UPPER(NOMBRE) NOMBRE_TRANSACCION, COUNT(NOMBRE) AS CANTI   FROM V_INGRESOC 
WHERE USUARIO = @lc_usuario AND FECHA BETWEEN CONVERT(DATETIME, @lcfecha1, 101) AND CONVERT(DATETIME, @lcfecha2, 101)
GROUP BY NOMBRE
UNION ALL
SELECT  @lcmes as MES, @lc_usuario USUARIO, ('ALMACEN : ' + DEALMACEN + ' -- > ' + AALMACEN) NOMBRE_TRANSACCION, COUNT('ALMACEN : ' + DEALMACEN + ' -- > ' + AALMACEN) AS CANTI   FROM V_TRANSFERENCIAC
WHERE USUARIO = @lc_usuario AND FECHA BETWEEN CONVERT(DATETIME, @lcfecha1, 101) AND CONVERT(DATETIME, @lcfecha2, 101)
GROUP BY ('ALMACEN : ' + DEALMACEN + ' -- > ' + AALMACEN)
UNION ALL
SELECT  @lcmes as MES, @lc_usuario USUARIO, UPPER(NOMBRE) AS  NOMBRE_TRANSACCION, COUNT(NOMBRE) AS CANTI   FROM V_INGRESODEVC
WHERE USUARIO = @lc_usuario AND FECHA BETWEEN CONVERT(DATETIME, @lcfecha1, 101) AND CONVERT(DATETIME, @lcfecha2, 101)
GROUP BY NOMBRE

