use SIGSALUD
select * from V_STOCKPRECIO
select * from V_STOCK

select SISMED, UPPER(NOMBRE) AS NOMBRE, COSTO AS PRECIO_COSTO, PRECIO AS PRECIO_VENTA  from V_RPT_PRECIOS_FARMACIA WHERE STOCK <> 0 
ORDER BY NOMBRE ASC

/* MEDICAMENTO */
select SISMED, UPPER(NOMBRE) AS NOMBRE, COSTO AS PRECIO_COSTO, PRECIO AS PRECIO_VENTA  from V_RPT_PRECIOS_FARMACIA WHERE STOCK <> 0 AND CLASE = 'A'
   AND SUBSTRING(NOMBRE,1,8) <> 'DONACION' AND  SUBSTRING(NOMBRE,1,3) <> 'COE' ORDER BY NOMBRE ASC


/* INZUMOS  */
select SISMED, UPPER(NOMBRE) AS NOMBRE, COSTO AS PRECIO_COSTO, PRECIO AS PRECIO_VENTA  from V_RPT_PRECIOS_FARMACIA WHERE STOCK <> 0 AND CLASE = 'F'
AND SUBSTRING(NOMBRE,1,8) <> 'DONACION' AND  SUBSTRING(NOMBRE,1,3) <> 'COE' ORDER BY NOMBRE ASC

/* GALENICOS  */
select SISMED, UPPER(NOMBRE) AS NOMBRE, COSTO AS PRECIO_COSTO, PRECIO AS PRECIO_VENTA  from V_RPT_PRECIOS_FARMACIA WHERE STOCK <> 0 AND CLASE = 'G'
AND SUBSTRING(NOMBRE,1,8) <> 'DONACION' AND  SUBSTRING(NOMBRE,1,3) <> 'COE' ORDER BY NOMBRE ASC


/* PRODUCTOS DE HIGIENE PERSONAL   */
select SISMED, UPPER(NOMBRE) AS NOMBRE, COSTO AS PRECIO_COSTO, PRECIO AS PRECIO_VENTA  from V_RPT_PRECIOS_FARMACIA WHERE STOCK <> 0 AND CLASE = 'I'
AND SUBSTRING(NOMBRE,1,8) <> 'DONACION' AND  SUBSTRING(NOMBRE,1,3) <> 'COE' ORDER BY NOMBRE ASC





SELECT * FROM  V_RPT_PRECIOS_FARMACIA
SELECT * FROM dbo.CLASE