USE [BDPERSONAL]
GO

/****** Object:  Table [dbo].[TMP_TRAMAJ]    Script Date: 10/22/2015 11:32:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_TRAMAJ](
	[IDTRAMAJ] [int] IDENTITY(1,1) NOT NULL,
	[PERIODO] [varchar](6) NULL,
	[IPRESS] [varchar](10) NULL,
	[UGIPRESS] [varchar](10) NULL,
	[CODIGOCOLEGIO] [varchar](2) NULL,
	[TOTALPROFESIONALES] [int] NULL,
	[HORASCE] [int] NULL,
	[HORASEME] [int] NULL,
	[HORASHOS] [int] NULL,
	[HORASADM] [int] NULL,
	[HORASCAP] [int] NULL,
	[FECHAREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TMP_TRAMAJ_1] PRIMARY KEY CLUSTERED 
(
	[IDTRAMAJ] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


