USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_MOR_ATN_TOTAL_F]    Script Date: 09/15/2017 00:09:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_MOR_ATN_TOTAL_F](
	[SEXO_PAC] [varchar](1) NOT NULL,
	[GRUPO_EDAD] [varchar](2) NULL,
	[DIAGNOSTICO_DEFINITIVO] [varchar](5) NULL,
	[TOTAL_ATENDIDOS] [varchar](1) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


