USE SIGSALUD
SELECT     EM.ESTADO, EM.EMERGENCIA_ID, EM.FECHA, EM.HORA, EM.ORDEN, EM.PACIENTE, PA.HISTORIA, EM.NOMBRES, OCU.NOMBRE AS OCUPACION, 
                      EM.FECHA_NACIMIENTO, EM.SEXO, SEG.NOMBRE AS NOMBRE_SEGURO, EM.CIEX1, CX.NOMBRE AS NOMBRE_DIAGNOSTICO1, EM.CIEX2, 
                      CX2.NOMBRE AS NOMBRE_DIAGNOSTICO2, EM.CIEX3, CX3.NOMBRE AS NOMBRE_DIAGNOSTICO3, EM.CIEX4, CX4.NOMBRE AS NOMBRE_DIAGNOSTICO4, 
                      EM.CIEX5, CX5.NOMBRE AS NOMBRE_DIAGNOSTICO5, EM.CIEX6, CX6.NOMBRE AS NOMBRE_DIAGNOSTICO6, EM.CONSULTORIO, 
                      CON.NOMBRE AS NOMBRE_CONSULTORIO, EM.CUENTAID, EM.MOTIVO_EMERGENCIA, EM.USUARIO AS USUARIO_ADMISION, ME.NOMBRE AS NOMBRE_MOTIVO, 
                      MED3.MEDICO, MED3.NOMBRE AS NOMBRE_MEDICO, EM.DIRECCION, EM.ESTADO_CIVIL, EC.NOMBRE AS NOMBRE_ESTADOCIVIL, EM.DISTRITO, 
                      EM.DOCUMENTO, EM.DOCUMENTOA, EM.TELEFONO1, EM.TELEFONO2, EM.ACOMPANANTE, EM.PATERNO, EM.MATERNO, EM.NOMBRE AS NOMBRE_PACIENTE, 
                      EM.EDAD, SEX.NOMBRE AS NOMBRE_SEXO, EM.SEGURO, EM.PRE_AFILIACION, EM.OBSERVACION1, EM.OBSERVACION2, EM.LOCALIDAD, 
                      LOC.Nombre AS NOMBRE_LOCALIDAD, EM.CONSULTORIO1, EM.TIPOATENCION, EM.PRIORIDAD, EM.TEMPERATURA, EM.PRESION, EM.PULSO, EM.FR, EM.FC, 
                      EM.SAT_OX, MED.ABREVIATURA + '.' + UW.NOMBRES AS USUARIO_FN_VITALES, EM.EXAMEN_FISICO, EM.RELATO, EM.EVOLUCION, EM.SINTOMAS, 
                      EM.TRATAMIENTO, EM.TIPO_CIEX1, EM.TIPO_CIEX2, EM.TIPO_CIEX3, EM.TIPO_CIEX4, EM.TIPO_CIEX5, EM.TIPO_CIEX6, EM.HORA_ATEN, EM.PESO, EM.HORA_SAL, 
                      EM.FECHA_SAL, DS.NOMBRE AS DESTINO, EM.MEDICO AS MEDICO_SALIDA, MED2.NOMBRE AS NOMBRE_MEDICO_SALIDA, 
                      MED4.ABREVIATURA + ' ' + MED4.NOMBRE AS USUARIO_ALTA_ENF, EM.FECHA_HORA_ALTA_ENF, EM.PRESIOND, EL.DESCRIPCION AS ESTADO_PACIENTE, 
                      EM.FECHA_ATENCION, EM.ESTABLECIMIENTO, R.NOMBRE AS DESRELIGION, EM.QUIEN_ATIENDE, EM.HORAINICIOATENCION
FROM         dbo.EMERGENCIA AS EM LEFT OUTER JOIN
                      dbo.MEDICO AS MEDX ON EM.USUARIO_FN_VITALES = MEDX.MEDICO LEFT OUTER JOIN
                      dbo.USUARIO_WEB AS UW ON MEDX.DNI = UW.DNI LEFT OUTER JOIN
                      dbo.MEDICO AS MED ON UW.DNI = MED.DNI INNER JOIN
                      dbo.SEGURO AS SEG ON EM.SEGURO = SEG.SEGURO INNER JOIN
                      dbo.CIEX AS CX ON EM.CIEX1 = CX.CIEX INNER JOIN
                      dbo.CONSULTORIO AS CON ON EM.CONSULTORIO = CON.CONSULTORIO INNER JOIN
                      dbo.MOTIVO_EMERGENCIA AS ME ON EM.MOTIVO_EMERGENCIA = ME.MOTIVO_EMERGENCIA INNER JOIN
                      dbo.MEDICO AS MED2 ON EM.MEDICO = MED2.MEDICO INNER JOIN
                      dbo.ESTADO_CIVIL AS EC ON EM.ESTADO_CIVIL = EC.ESTADO_CIVIL INNER JOIN
                      dbo.SEXO AS SEX ON EM.SEXO = SEX.SEXO INNER JOIN
                      dbo.LOCALIDAD AS LOC ON EM.LOCALIDAD = LOC.Localidad LEFT OUTER JOIN
                      dbo.PACIENTE AS PA ON EM.PACIENTE = PA.PACIENTE INNER JOIN
                      dbo.CIEX AS CX2 ON EM.CIEX2 = CX2.CIEX INNER JOIN
                      dbo.CIEX AS CX3 ON EM.CIEX3 = CX3.CIEX INNER JOIN
                      dbo.CIEX AS CX4 ON EM.CIEX4 = CX4.CIEX INNER JOIN
                      dbo.CIEX AS CX5 ON EM.CIEX5 = CX5.CIEX INNER JOIN
                      dbo.CIEX AS CX6 ON EM.CIEX6 = CX6.CIEX INNER JOIN
                      dbo.DESTINO AS DS ON EM.DESTINO = DS.DESTINO INNER JOIN
                      dbo.MEDICO AS MED3 ON EM.MEDICO1 = MED3.MEDICO LEFT OUTER JOIN
                      dbo.MEDICO AS MED4 ON EM.USUARIO_ALTA_ENF = MED4.DNI LEFT OUTER JOIN
                      dbo.EMERGENCIA_LUGAR_WEB AS EL ON EM.ESTADO_PACIENTE = EL.LUGAR INNER JOIN
                      dbo.RELIGION AS R ON R.RELIGION = EM.RELIGION INNER JOIN
                      dbo.OCUPACION AS OCU ON PA.OCUPACION = OCU.OCUPACION
                      
SELECT * FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17043565'                      

SELECT USUARIO_FN_VITALES, SEGURO, CIEX1, CONSULTORIO, MOTIVO_EMERGENCIA, MEDICO, ESTADO_CIVIL,
SEXO  FROM [SIGSALUD].[dbo].[EMERGENCIA] WHERE EMERGENCIA_ID = '17043565'                      

UPDATE [SIGSALUD].[dbo].[EMERGENCIA] SET MEDICO = 'GAE' WHERE EMERGENCIA_ID = '17043565'  

