/* OPERACION DE LA TRAMA CE */
use SIGSALUD
DECLARE @lcfecha1 datetime = convert(datetime, '2015-05-01', 101)
DECLARE @lcfecha2 datetime = convert(datetime, '2015-05-31', 101)
/* DROP TABLE TRAMA_CE1    */
   SELECT '005947' AS RENIPRESS,   MT AS TURNO, A.ANIO + RIGHT('00' + Ltrim(Rtrim(A.MES)),2) + RIGHT('00' + Ltrim(Rtrim(A.DIA)),2) as FECHA_ATE, A.ESTABLEC AS COND_ESTABL, A.ETNIA, A.FICHAFAM AS HISCLI,
  A.FINANCIA, case TIPO_DOC when 'A' then '0' when 'D' then '1'  when 'PN' then '1' when 'CI' then '1' WHEN '' THEN '0' WHEN 'CE' THEN '2' WHEN '0' THEN '0'  else '0' end AS TIPDOC, A.DNI AS DOCID,
  SUBSTRING(CONVERT(VARCHAR(10), B.FECHA_NACIMIENTO, 105), 7, 4) + SUBSTRING(CONVERT(VARCHAR(10), B.FECHA_NACIMIENTO, 105), 4, 2) +
     SUBSTRING(CONVERT(VARCHAR(10), B.FECHA_NACIMIENTO, 105), 1, 2)   AS FEC_NAC, CASE A.SEXO WHEN 'M' THEN '1' ELSE '2' END AS SEXO, B.NOMBRES, B.PATERNO AS APPATERNO, B.MATERNO AS APMATERNO, B.DIRECCION,
     A.PROCEDE AS UBI_PROC, A.COD_SERVSA AS  UPS, A.SERVICIO AS COND_SERV, D.semprofesion AS TIPO_PS, '1' TIPO_DOC_PS, SUBSTRING(A.CODHIS,2,8) AS DNI_PS, UPPER(PROF_CITA) AS PS_ATIENDE,
     CODIGO1 AS DIAG_1, DIAGNOST1 AS TIPDIAG_1, LABCONF1 AUXILIAR_1, CODIGO2 AS DIAG_2, DIAGNOST2 AS TIPDIAG_2, LABCONF2 AUXILIAR_2, CODIGO3 AS DIAG_3, DIAGNOST3 AS TIPDIAG_3, LABCONF3 AUXILIAR_3,
     CODIGO4 AS DIAG_4, DIAGNOST4 AS TIPDIAG_4, '' AUXILIAR_4, CODIGO5 AS DIAG_5, DIAGNOST5 AS TIPDIAG_5, '' AUXILIAR_5, CODIGO6 AS DIAG_6, DIAGNOST6 AS TIPDIAG_6, '' AUXILIAR_6
     INTO TRAMA_CE1
     FROM HIS A 
     INNER JOIN PACIENTE B ON B.HISTORIA = A.FICHAFAM
      INNER JOIN MEDICO C ON C.CODHIS = A.CODHIS 
      inner JOIN ESPECIALIDAD D ON D.ESPECIALIDAD = C.ESPECIALIDAD
           WHERE A.PERIODO = '052016'  ORDER BY TIPO_PS DESC
   

SELECT * FROM TRAMA_CE1   WHERE DOCID = ''
UPDATE TRAMA_CE1 SET TIPDOC = '0', DOCID = ''  WHERE DOCID IN ('R.N', 'R.N.', '', '0000000000', '00000000', '0')
UPDATE TRAMA_CE1 SET TIPDOC = '2'  WHERE DOCID IN ('E-27512355', 'L361R9W6F')
DROP TABLE TRAMA_CE1 

SELECT DOCID FROM TRAMA_CE1  GROUP BY    DOCID ORDER BY DOCID ASC
SELECT * FROM TRAMA_CE1 where docid = 'E-27512355' 

E-27512355  
   
/*
SELECT *  FROM HIS WHERE PERIODO = '052016'

select * from CONSULTORIO WHERE HIS_CODSERVICIO = '300301'

SELECT *  FROM MEDICO  WHERE CODHIS = '11022464101'
SELECT *  FROM MEDICO  WHERE NOMBRE LIKE '%VENEGA%'
SELECT *  FROM ESPECIALIDAD WHERE ESPECIALIDAD = '0043'
UPDATE ESPECIALIDAD SET SEMPROFESION = '22' WHERE ESPECIALIDAD = '0043'

SELECT * FROM PACIENTE WHERE PACIENTE = '2008044646'


*/

 
 