/* Trama Consolidada de produccion Asistencial en Consulta Ambulatoria */
/*
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
SELECT PACIENTE, COUNT(PACIENTE) AS ATENCIONES FROM ATENCIONC WHERE FECHA BETWEEN @lcfecha1  AND @lcfecha2 AND ESTADO = '0' GROUP BY PACIENTE ORDER BY  COUNT(PACIENTE)

*/


/* PARA UN PACIENTE QUE SE ATENDIO UNA VEZ */
/*
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lidpaciente varchar(13) = '2008046960'
declare @lnatencion int = 1
SELECT CASE WHEN B.ABREVIATURA = 'MED' THEN 1 ELSE 0 END ATENCION_MEDICO, CASE WHEN A.SEXO = 'M' THEN '1' WHEN A.SEXO = 'F' THEN '2' ELSE 'N' END AS SEXO_PACIENTE, CASE WHEN A.EDAD < 1 THEN '1' WHEN A.EDAD BETWEEN 1 AND 4 THEN '2' WHEN A.EDAD BETWEEN 5 AND 9 THEN '3' WHEN A.EDAD BETWEEN 10 AND 14 THEN '4' WHEN A.EDAD BETWEEN 15 AND 19 THEN '5'
 WHEN A.EDAD BETWEEN 20 AND 24 THEN '6' WHEN A.EDAD BETWEEN 25 AND 29 THEN '7' WHEN A.EDAD BETWEEN 30 AND 34 THEN '8' WHEN A.EDAD BETWEEN 35 AND 39 THEN '9' WHEN A.EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN A.EDAD BETWEEN 45 AND 49 THEN '11' WHEN A.EDAD BETWEEN 50 AND 54 THEN '12' WHEN A.EDAD BETWEEN 55 AND 59 THEN '13' WHEN A.EDAD BETWEEN 60 AND 64 THEN '14' WHEN A.EDAD >=65  THEN '15'
   ELSE  'ND' END AS GRUPO_EDAD, CASE WHEN B.ABREVIATURA <> 'MED' THEN 1 ELSE 0 END ATENCION_NO_MEDICO, @lnatencion as ATENDIDO_POR_MES FROM ATENCIONC A LEFT JOIN MEDICO B ON B.MEDICO = A.MEDICO
     WHERE A.PACIENTE = @lidpaciente AND A.FECHA BETWEEN @lcfecha1  AND @lcfecha2
  */ 
   TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_TR_ATEN]
   
select * from [SIGSALUD].[dbo].[TMP_TR_ATEN]   

/* PACIENTE QUE SE ATENDIO 2 VECES */
/*
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lidpaciente varchar(13) = '2008115272'
declare @lnatencion int = 1
declare @lc_sexo varchar(1) = (select top 1 case WHEN SEXO = 'M' THEN '1' WHEN SEXO = 'F' THEN '2' ELSE 'N' END FROM [SIGSALUD].[dbo].[ATENCIONC] where PACIENTE = @lidpaciente AND FECHA BETWEEN @lcfecha1  AND @lcfecha2)
declare @ln_atm int = (SELECT COUNT(*)  FROM [SIGSALUD].[dbo].[ATENCIONC] A LEFT JOIN [SIGSALUD].[dbo].[MEDICO] B ON B.MEDICO = A.MEDICO  WHERE A.PACIENTE = @lidpaciente AND A.FECHA BETWEEN @lcfecha1  AND @lcfecha2 AND ABREVIATURA = 'MED')
declare @ln_atnm int = (SELECT COUNT(*)  FROM [SIGSALUD].[dbo].[ATENCIONC] A LEFT JOIN [SIGSALUD].[dbo].[MEDICO] B ON B.MEDICO = A.MEDICO  WHERE A.PACIENTE = @lidpaciente AND A.FECHA BETWEEN @lcfecha1  AND @lcfecha2 AND ABREVIATURA <> 'MED')
declare @lc_grupo_edad varchar(2) = (SELECT top 1 CASE WHEN EDAD < 1 THEN '1' WHEN EDAD BETWEEN 1 AND 4 THEN '2' WHEN EDAD BETWEEN 5 AND 9 THEN '3' WHEN EDAD BETWEEN 10 AND 14 THEN '4' WHEN EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN EDAD BETWEEN 20 AND 24 THEN '6' WHEN EDAD BETWEEN 25 AND 29 THEN '7' WHEN EDAD BETWEEN 30 AND 34 THEN '8' WHEN EDAD BETWEEN 35 AND 39 THEN '9' WHEN EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN EDAD BETWEEN 45 AND 49 THEN '11' WHEN EDAD BETWEEN 50 AND 54 THEN '12' WHEN EDAD BETWEEN 55 AND 59 THEN '13' WHEN EDAD BETWEEN 60 AND 64 THEN '14' WHEN EDAD >=65  THEN '15'
   ELSE  'ND' END FROM [SIGSALUD].[dbo].[ATENCIONC] WHERE PACIENTE = @lidpaciente AND FECHA BETWEEN @lcfecha1  AND @lcfecha2)
select @lc_sexo as sexo_paciente, @lc_grupo_edad as grupo_edad, @ln_atm as atencion_medico, @ln_atnm as atencion_no_medico, 1 as atendido_por_mes

*/
select sexo_paciente, grupo_edad, atencion_medico, atencion_no_medico, atendido_por_mes from [SIGSALUD].[dbo].[TMP_TR_ATEN]
  order by sexo_paciente, grupo_edad
  
  
   
     
     
 SELECT * FROM [SIGSALUD].[dbo].[ATENCIONC] WHERE FECHA BETWEEN convert(datetime, '2017-08-01', 101) AND convert(datetime, '2017-08-31', 101) AND PACIENTE = '2008115272'
 
 
 SELECT CASE WHEN A.EDAD < 1 THEN '1' WHEN A.EDAD BETWEEN 1 AND 4 THEN '2' WHEN A.EDAD BETWEEN 5 AND 9 THEN '3' WHEN A.EDAD BETWEEN 10 AND 14 THEN '4' WHEN A.EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN A.EDAD BETWEEN 20 AND 24 THEN '6' WHEN A.EDAD BETWEEN 25 AND 29 THEN '7' WHEN A.EDAD BETWEEN 30 AND 34 THEN '8' WHEN A.EDAD BETWEEN 35 AND 39 THEN '9' WHEN A.EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN A.EDAD BETWEEN 45 AND 49 THEN '11' WHEN A.EDAD BETWEEN 50 AND 54 THEN '12' WHEN A.EDAD BETWEEN 55 AND 59 THEN '13' WHEN A.EDAD BETWEEN 60 AND 64 THEN '14' WHEN A.EDAD >=65  THEN '15'
   ELSE  'ND' END AS GRUPO_EDAD, CASE WHEN B.ABREVIATURA <> 'MED' THEN 1 ELSE 0 END ATENCION_NO_MEDICO, @lnatencion as ATENDIDO_POR_MES  FROM [SIGSALUD].[dbo].[ATENCIONC] A LEFT JOIN [SIGSALUD].[dbo].[MEDICO] B ON B.MEDICO = A.MEDICO
     WHERE A.PACIENTE = @lidpaciente AND A.FECHA BETWEEN @lcfecha1  AND @lcfecha2
  


 
 
 
 SELECT CASE WHEN B.ABREVIATURA = 'MED' THEN 1 ELSE 0 END ATENCION_MEDICO, CASE WHEN A.SEXO = 'M' THEN '1' WHEN A.SEXO = 'F' THEN '2' ELSE 'N' END AS SEXO_PACIENTE, CASE WHEN A.EDAD < 1 THEN '1' WHEN A.EDAD BETWEEN 1 AND 4 THEN '2' WHEN A.EDAD BETWEEN 5 AND 9 THEN '3' WHEN A.EDAD BETWEEN 10 AND 14 THEN '4' WHEN A.EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN A.EDAD BETWEEN 20 AND 24 THEN '6' WHEN A.EDAD BETWEEN 25 AND 29 THEN '7' WHEN A.EDAD BETWEEN 30 AND 34 THEN '8' WHEN A.EDAD BETWEEN 35 AND 39 THEN '9' WHEN A.EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN A.EDAD BETWEEN 45 AND 49 THEN '11' WHEN A.EDAD BETWEEN 50 AND 54 THEN '12' WHEN A.EDAD BETWEEN 55 AND 59 THEN '13' WHEN A.EDAD BETWEEN 60 AND 64 THEN '14' WHEN A.EDAD >=65  THEN '15'
   ELSE  'ND' END AS GRUPO_EDAD, CASE WHEN B.ABREVIATURA <> 'MED' THEN 1 ELSE 0 END ATENCION_NO_MEDICO, @lnatencion as ATENDIDO_POR_MES  FROM [SIGSALUD].[dbo].[ATENCIONC] A LEFT JOIN [SIGSALUD].[dbo].[MEDICO] B ON B.MEDICO = A.MEDICO
     WHERE A.PACIENTE = @lidpaciente AND A.FECHA BETWEEN @lcfecha1  AND @lcfecha2
  


SELECT * FROM ATENCIONC WHERE  FECHA BETWEEN convert(datetime, '2017-08-01', 101) AND convert(datetime, '2017-08-31', 101) AND PACIENTE = '2008115272'

SELECT * FROM ATENCIONC WHERE  FECHA BETWEEN convert(datetime, '2017-08-01', 101) AND convert(datetime, '2017-08-31', 101) AND PACIENTE = '2008115272'

2008115272



SELECT * FROM ATENCIONC WHERE MEDICO = 'CVM'   AND PACIENTE = '2008115272'
     

SELECT CASE WHEN B.ABREVIATURA = 'MED' THEN 1 ELSE 0 END ATENCION_MEDICO FROM MEDICO    WHERE MEDICO = 'PCJ'


SELECT * FROM MEDICO WHERE NOMBRE LIKE 'CACERES%'


SELECT ABREVIATURA FROM MEDICO GROUP BY ABREVIATURA


SELECT * FROM MEDICO WHERE MEDICO = 'IBL'

SELECT * FROM MEDICO WHERE ABREVIATURA = 'MED' ORDER BY NOMBRE ASC






SELECT PACIENTE, COUNT(PACIENTE) AS ATENCIONES FROM ATENCIONC WHERE FECHA BETWEEN @lcfecha1  AND @lcfecha2 AND ESTADO = '0' GROUP BY PACIENTE ORDER BY  COUNT(PACIENTE)






SELECT * FROM ATENCIONC WHERE FECHA BETWEEN @lcfecha1  AND @lcfecha2 ORDER BY FECHA 



SELECT * FROM ATENCIONC ORDER BY FECHA DESC






/*
declare @lcanio_mes varchar(6) = (select substring(convert(varchar(10), @lcfecha1, 103),7,4)) + (select substring(convert(varchar(10), @lcfecha1, 103),4,2))
declare @lccodigo_ipress varchar(8) = '00005947'
select @lcanio_mes as PERIODO, @lccodigo_ipress as IPRESS, @lccodigo_ipress as UGIPRESS
*/


/* para total */
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lt_tmp_at_ged table (grupo_edad varchar(2))
insert @lt_tmp_at_ged
SELECT CASE WHEN EDAD < 1 THEN '1' WHEN EDAD BETWEEN 1 AND 4 THEN '2' WHEN EDAD BETWEEN 5 AND 9 THEN '3' WHEN EDAD BETWEEN 10 AND 14 THEN '4' WHEN EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN EDAD BETWEEN 20 AND 24 THEN '6' WHEN EDAD BETWEEN 25 AND 29 THEN '7' WHEN EDAD BETWEEN 30 AND 34 THEN '8' WHEN EDAD BETWEEN 35 AND 39 THEN '9' WHEN EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN EDAD BETWEEN 45 AND 49 THEN '11' WHEN EDAD BETWEEN 50 AND 54 THEN '12' WHEN EDAD BETWEEN 55 AND 59 THEN '13' WHEN EDAD BETWEEN 60 AND 64 THEN '14' WHEN EDAD >=65  THEN '15'
   ELSE  'ND' END as grupo_edad  FROM [SIGSALUD].[dbo].[ATENCIONC] where  FECHA BETWEEN @lcfecha1  AND @lcfecha2   order by edad
SELECT grupo_edad, COUNT(grupo_edad) as atencion_mes from @lt_tmp_at_ged group by grupo_edad order by convert(int, grupo_edad)


 
/* para masculino */
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lt_tmp_at_ged table (grupo_edad varchar(2))
insert @lt_tmp_at_ged
SELECT CASE WHEN EDAD < 1 THEN '1' WHEN EDAD BETWEEN 1 AND 4 THEN '2' WHEN EDAD BETWEEN 5 AND 9 THEN '3' WHEN EDAD BETWEEN 10 AND 14 THEN '4' WHEN EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN EDAD BETWEEN 20 AND 24 THEN '6' WHEN EDAD BETWEEN 25 AND 29 THEN '7' WHEN EDAD BETWEEN 30 AND 34 THEN '8' WHEN EDAD BETWEEN 35 AND 39 THEN '9' WHEN EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN EDAD BETWEEN 45 AND 49 THEN '11' WHEN EDAD BETWEEN 50 AND 54 THEN '12' WHEN EDAD BETWEEN 55 AND 59 THEN '13' WHEN EDAD BETWEEN 60 AND 64 THEN '14' WHEN EDAD >=65  THEN '15'
   ELSE  'ND' END as grupo_edad  FROM [SIGSALUD].[dbo].[ATENCIONC] where  FECHA BETWEEN @lcfecha1  AND @lcfecha2  and SEXO = 'M' order by edad
SELECT grupo_edad, COUNT(grupo_edad) as atencion_mes from @lt_tmp_at_ged group by grupo_edad order by convert(int, grupo_edad)


/* para femenino */
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lt_tmp_at_ged table (grupo_edad varchar(2))
insert @lt_tmp_at_ged
SELECT CASE WHEN EDAD < 1 THEN '1' WHEN EDAD BETWEEN 1 AND 4 THEN '2' WHEN EDAD BETWEEN 5 AND 9 THEN '3' WHEN EDAD BETWEEN 10 AND 14 THEN '4' WHEN EDAD BETWEEN 15 AND 19 THEN '5' 
 WHEN EDAD BETWEEN 20 AND 24 THEN '6' WHEN EDAD BETWEEN 25 AND 29 THEN '7' WHEN EDAD BETWEEN 30 AND 34 THEN '8' WHEN EDAD BETWEEN 35 AND 39 THEN '9' WHEN EDAD BETWEEN 40 AND 44 THEN '10'
  WHEN EDAD BETWEEN 45 AND 49 THEN '11' WHEN EDAD BETWEEN 50 AND 54 THEN '12' WHEN EDAD BETWEEN 55 AND 59 THEN '13' WHEN EDAD BETWEEN 60 AND 64 THEN '14' WHEN EDAD >=65  THEN '15'
   ELSE  'ND' END as grupo_edad  FROM [SIGSALUD].[dbo].[ATENCIONC] where  FECHA BETWEEN @lcfecha1  AND @lcfecha2  and SEXO = 'F' order by edad
SELECT grupo_edad, COUNT(grupo_edad) as atencion_mes from @lt_tmp_at_ged group by grupo_edad order by convert(int, grupo_edad)