USE SIGSALUD
DECLARE @lcfecha1 datetime = convert(datetime, '2016-08-01', 101)
DECLARE @lcfecha2 datetime = convert(datetime, '2016-08-31', 101)

SELECT '005947' AS RENIPRESS, CITA_ID AS CITA_ID, REPLACE(CONVERT(varchar(10), FECHA_PROGRAMACION, 102),'.', '') AS FECHA_TK, convert(varchar(5), CONVERT(TIME,FECHA_PROGRAMACION)) AS HORA_TK,
 REPLACE(CONVERT(varchar(10), FECHA_OTORGA, 102),'.', '') AS FECHA_CITA, HORA AS HORA_CITA, A.HISTORIA AS HISCLI,  CASE A.SEGURO   WHEN '0'  THEN '01' WHEN '01'  THEN '02'  WHEN '02'  THEN '04'   WHEN '03'  THEN '02'  WHEN '04'  THEN '10'   WHEN '05'  THEN '01'    WHEN '06'  THEN '03'
    WHEN '07'  THEN '07'  WHEN '08'  THEN '09'  WHEN '09'  THEN '10'  WHEN '10'  THEN '05'  WHEN '11'  THEN '06' WHEN '12'  THEN '08' WHEN '13'  THEN '11'  WHEN '14'  THEN '11'  WHEN '15'  THEN '02' WHEN '16'  THEN '10' END AS FINANCIA,  case B.TIPO_DOCUMENTO  when 'D' then '1'  when 'CE' then '2'  when  '0' then '1' end  as TIPDOC,
    B.DOCUMENTO, B.NOMBRE, B.PATERNO AS APPATERNO, B.MATERNO AS APMATERNO, HIS_CODSERVICIO AS UPS, SEMPROFESION AS TIPO_PS, '1' AS TIPO_DOC_PS, C.DNI AS DNI_PS,
    NOMBRE_MEDICO AS PS_ATIENDE  FROM V_CITA A INNER JOIN PACIENTE B ON B.PACIENTE = A.PACIENTE LEFT JOIN MEDICO C ON C.MEDICO = A.MEDICO LEFT JOIN ESPECIALIDAD D ON D.ESPECIALIDAD = A.ESPECIALIDAD 
LEFT JOIN CONSULTORIO E ON E.CONSULTORIO = A.CONSULTORIO where A.FECHA_PROGRAMACION between @lcfecha1 and @lcfecha2 order by FECHA_PROGRAMACION asc

