SELECT [IDTEVDFEBTEMP]
      ,[IDDISTRITO]
      ,[CDISTRITO]
      ,[IDLOCALIDAD]
      ,[CLOCALIDAD]
      ,[EDAD]
  FROM [SIGSALUD].[dbo].[TEVDFEBTEMP]
GO

  SELECT IDTEVDFEBTEMP, IDDISTRITO, CDISTRITO, IDLOCALIDAD, CLOCALIDAD, COUNT(EDAD) AS CEDADMENOR1  FROM TEVDFEBTEMP GROUP BY IDDISTRITO



SELECT IDDISTRITO, CDISTRITO, IDLOCALIDAD, CLOCALIDAD, COUNT(EDAD) AS CEDADMENOR1  FROM TEVDFEBTEMP GROUP BY CDISTRITO

SELECT IDDISTRITO, CDISTRITO, IDLOCALIDAD, CLOCALIDAD, EDAD  FROM TEVDFEBTEMP ORDER BY CDISTRITO ASC
  UPDATE TEVDFEBTEMP SET cdistrito = 'CHOSICA' WHERE cdistrito = 'LURIGANCHO'