USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_EPIDEMIO_EDAS]    Script Date: 10/20/2017 17:04:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_EPIDEMIO_EDAS](
	[TITULO] [varchar](150) NULL,
	[CDISTRITO] [varchar](150) NULL,
	[CLOCALIDAD] [varchar](150) NULL,
	[MENOR1] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


