USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TEVDFFINAL]    Script Date: 10/13/2015 11:50:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TEVDFFINAL](
	[IDTEFFINAL] [int] IDENTITY(1,1) NOT NULL,
	[CDISTRITO] [nvarchar](150) NULL,
	[CLOCALIDAD] [varchar](150) NULL,
	[SUB_TOTAL] [nvarchar](50) NULL,
 CONSTRAINT [PK_TEVDFFINAL] PRIMARY KEY CLUSTERED 
(
	[IDTEFFINAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


