USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TEVDFEBTEMP0]    Script Date: 04/27/2017 14:56:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TEVDFEBTEMP0](
	[IDTEVDFEBTEMP] [int] IDENTITY(1,1) NOT NULL,
	[IDDISTRITO] [varchar](10) NULL,
	[CDISTRITO] [varchar](150) NULL,
	[IDLOCALIDAD] [varchar](10) NULL,
	[CLOCALIDAD] [varchar](150) NULL,
	[EDAD] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


