USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TEVDFEBTEMP]    Script Date: 10/07/2015 12:50:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TEVDFEBTEMP](
	[IDTEVDFEBTEMP] [int] IDENTITY(1,1) NOT NULL,
	[IDDISTRITO] [varchar](10) NULL,
	[CDISTRITO] [varchar](150) NULL,
	[IDLOCALIDAD] [varchar](10) NULL,
	[CLOCALIDAD] [varchar](150) NULL,
	[EDAD] [varchar](50) NULL,
 CONSTRAINT [PK_TEVDFEBTEMP] PRIMARY KEY CLUSTERED 
(
	[IDTEVDFEBTEMP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


