USE SIGSALUD
ALTER TABLE EMERGENCIA ADD GPOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD FUROBS VARCHAR(10);
ALTER TABLE EMERGENCIA ADD FPPOBS VARCHAR(10);
ALTER TABLE EMERGENCIA ADD EGUMOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD EGECOOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD USUARIO_ANT_OBSTETRICIA VARCHAR(50);
ALTER TABLE EMERGENCIA ADD ALTURA_UTERINA VARCHAR(3);
ALTER TABLE EMERGENCIA ADD PRESENTACION VARCHAR(2);
ALTER TABLE EMERGENCIA ADD LCF VARCHAR(5);
ALTER TABLE EMERGENCIA ADD DILATACION VARCHAR(3);
ALTER TABLE EMERGENCIA ADD INCORPORACION VARCHAR(4);
ALTER TABLE EMERGENCIA ADD ALTURA_PRESENTACION VARCHAR(2);
ALTER TABLE EMERGENCIA ADD MEMBRANAS VARCHAR(2);
ALTER TABLE EMERGENCIA ADD USUARIO_EXAMEN_OBSTETRICO VARCHAR(50);

USE SIGSALUD
ALTER TABLE EMERGENCIA ADD PRESENTACION2 VARCHAR(3);
ALTER TABLE EMERGENCIA ADD LCF2 VARCHAR(3);
ALTER TABLE EMERGENCIA ADD TV VARCHAR(3);
ALTER TABLE EMERGENCIA ADD MEDICO_CODIGO_GINE VARCHAR(3);



/* SELECT * FROM EMERGENCIA  */

/* Agregar Columna en la Vista : v_emergencia */
/* GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA */
