USE SIGSALUD
  INSERT INTO [SIGSALUD].[dbo].[EMERGENCIA_TIPO_PROCESO_WEB]([TIPO_PROCESO], [DESCRIPCION], [ESTADO])
      VALUES ('P12', 'REGISTRO EXAMEN FISICO (FUNCIONES VITALES)', 1)
  INSERT INTO [SIGSALUD].[dbo].[EMERGENCIA_TIPO_PROCESO_WEB]([TIPO_PROCESO], [DESCRIPCION], [ESTADO])
      VALUES ('P13', 'REGISTRO DE ANTECEDENTE OBSTETRICIA', 1)      
  INSERT INTO [SIGSALUD].[dbo].[EMERGENCIA_TIPO_PROCESO_WEB]([TIPO_PROCESO], [DESCRIPCION], [ESTADO])
      VALUES ('P14', 'REGISTRO DE EXAMEN OBSTETRICO', 1) 
      
      