USE SIGSALUD
ALTER TABLE EMERGENCIA ADD GPOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD FUROBS VARCHAR(10);
ALTER TABLE EMERGENCIA ADD FPPOBS VARCHAR(10);
ALTER TABLE EMERGENCIA ADD EGUMOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD EGECOOBS VARCHAR(50);
ALTER TABLE EMERGENCIA ADD USUARIO_ANT_OBSTETRICIA VARCHAR(50);

/* Agregar Columna en la Vista : v_emergencia */
/* directamente de la tabla EMERGENCIA */
/* GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA */

/* select * from v_emergencia where emergencia_id = '16024587' */
