/* COMPRUEBA LA GRABACION DE DATOS */
USE SIGSALUD
DECLARE @lidemergencia VARCHAR(13) = '16025232'
/* Grbacion de Antecedentes Obstetricia */
/* Tabla Emergencia */
SELECT EMERGENCIA_ID, ESTADO, MEDICO, MEDICO1, QUIEN_ATIENDE, fecha_salida, HORA, NOMBRES, GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia
SELECT TEMPERATURA,PRESION,PRESIOND,PULSO,FR,PESO,FC,SAT_OX,USUARIO_FN_VITALES, ESTADO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE  FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia
SELECT ALTURA_UTERINA, PRESENTACION, LCF, DILATACION, INCORPORACION, ALTURA_PRESENTACION, MEMBRANAS, USUARIO_EXAMEN_OBSTETRICO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE  FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia
/* Tabla Emergencia - DETALLE */
/* select * from EMERGENCIA_DET_WEB where EMERGENCIA_ID = @lidemergencia ORDER BY FECHA_HORA_REG ASC */
select * from v_EMERGENCIA_DET_WEB where EMERGENCIA_ID = @lidemergencia ORDER BY FECHA_HORA_REG ASC

/* REVISAR ATENCION */
SELECT * FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia


/* ELIMINAR LO QUE SE INGRESO */
/* UPDATE EMERGENCIA SET ESTADO = '2', GPOBS = '', FUROBS = '', FPPOBS = '', EGUMOBS = '', EGECOOBS = '', USUARIO_ANT_OBSTETRICIA = '', TEMPERATURA = '0', PRESION = '0',
PRESIOND = '', PULSO = '0', FR = '0', FC = '', USUARIO_FN_VITALES = '', PESO = 0, SAT_OX = 0, MEDICO = '0', MEDICO1 = '0', QUIEN_ATIENDE = '0',
ALTURA_UTERINA = '', PRESENTACION = '', LCF = '', DILATACION = '', INCORPORACION = '',  ALTURA_PRESENTACION = '', MEMBRANAS = '', USUARIO_EXAMEN_OBSTETRICO = '', PRESENTACION2 = '', LCF2 = '', TV = '', MEDICO_CODIGO_GINE = ''   WHERE EMERGENCIA_ID = @lidemergencia
DELETE FROM EMERGENCIA_DET_WEB where EMERGENCIA_ID = @lidemergencia       */
/*
select * from medico where dni = '41595637'
select * from medico where nombre like 'rosal%'
select * from medico where colegio = '20573'
update medico set dni = '41595637' where colegio = '20573' */

/* CON ESTE DATO MUESTRA PARA REGISTRAR ATENCION */

select * from V_UTILIZAR_HC_EMER_WEB where emergencia_id='16025232'

/* UPDATE EMERGENCIA SET USUARIO_FN_VITALES = 'SAY' WHERE emergencia_id='16025232' */

 

