/* VERIFICAR_DATOS_EMERGENCIA OBSTETRICIA */
/*
use sigsalud
alter table EMERGENCIA ADD HORAINICIOATENCION VARCHAR(15)
SELECT * FROM EMERGENCIA 
*/

USE SIGSALUD
DECLARE @lidemergencia VARCHAR(13) = '16031563'
EXEC dbo.SP_GET_EMERGENCIA_15 @lidemergencia


SELECT HORAINICIOATENCION, EMERGENCIA_ID, GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA, ALTURA_UTERINA, PRESENTACION, LCF, DILATACION, INCORPORACION, ALTURA_PRESENTACION,
MEMBRANAS, USUARIO_EXAMEN_OBSTETRICO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE, CIEX4, CIEX5, CIEX6, CIEX1, CIEX2, CIEX3, TEMPERATURA, FC, FR, SAT_OX, PULSO FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia 
select HORAINICIOATENCION,* from V_UTILIZAR_HC_EMER_WEB where emergencia_id= @lidemergencia

EXEC dbo.SP_GET_EMERGENCIA_15 @lidemergencia



SELECT ESTADO, FECHA, NOMBRES, HORAINICIOATENCION, EMERGENCIA_ID, GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA, ALTURA_UTERINA, PRESENTACION, LCF, DILATACION, INCORPORACION, ALTURA_PRESENTACION,
MEMBRANAS, USUARIO_EXAMEN_OBSTETRICO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE, CIEX4, CIEX5, CIEX6, CIEX1, CIEX2, CIEX3, TEMPERATURA, FC, FR, SAT_OX, PULSO FROM EMERGENCIA  ORDER BY EGUMOBS asc
