USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[BIENESTAR_FETAL]    Script Date: 09/04/2017 10:11:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BIENESTAR_FETAL](
	[IDBIENESTARFETAL] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [varchar](10) NULL,
	[HORA] [varchar](10) NULL,
	[PACIENTE] [varchar](10) NULL,
	[HISTORIA] [varchar](10) NULL,
	[NOMBRES] [varchar](250) NULL,
	[OBSTETRA] [varchar](10) NULL,
	[MEDICO] [varchar](10) NULL,
	[FECHAREGISTRO] [datetime] NULL,
	[USUARIO] [varchar](20) NULL,
 CONSTRAINT [PK_BIENESTAR_FETAL] PRIMARY KEY CLUSTERED 
(
	[IDBIENESTARFETAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


