USE SIGSALUD
SELECT * FROM ATENCIONC WHERE NOMBRES LIKE 'ALVARADO LLAN%' ORDE RBY 

SELECT * FROM ATENCIONC WHERE NOMBRES LIKE 'HUAMANI MALL%' 

SELECT * FROM CONSULTORIO WHERE CONSULTORIO = '5010'

SELECT * FROM CONSULTORIO WHERE CONSULTORIO LIKE '50%'

SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'ODONTO%'
UNION ALL
SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'RADIOL%'

SELECT * FROM ATENCIONC WHERE ID_CITA = '170162794'

