     INSERT INTO PACIENTE (PACIENTE, hISTORIA, pATERNO, MATERNO, NOMBRE, NOMBRES, SEXO, ESTADO_CIVIL, FECHA_APERTURA, HORA_APERTURA,
       PADRE, MADRE, HIJOS, DIRECCION, DISTRITO, LOCALIDAD, TELEFONO1, TELEFONO2, EMAIL, LUGAR_NACIMIENTO,
              EDAD, TIPO_DOCUMENTO, DOCUMENTO, PAIS, OCUPACION, GRADO_INSTRUCCION, CONYUGE_NOMBRE, CONYUGE_OCUPACION, RESPONSABLE_NOMBRE, RESPONSABLE_DIRECCION,
              RESPONSABLE_PARENTESCO, RESPONSABLE_TRABAJO, RESPONSABLE_OCUPACION, RESPONSABLE_TELEFONO, SEGURO, MEDICO, CONSULTORIO, CONSULTORIO_OLD, ENTIDAD)

    values ('2015253991', '228786', 'OBESO', 'CAMONES', 'JOSE CARLOS', 'OBESO CAMONES, JOSE', 'M', '0', getdate(), convert(char(8), CONVERT (TIME, GETDATE())),
      '', '', 0, '', '0','', '', '', '', '0', '45a', 'D', '32921099', '', '0', '00','','0','', '','','','','','0','','2052','2052','0')              