USE SIGSALUD
GO
SELECT * FROM USUARIO WHERE MODULO = 'ADMISION' ORDER BY NOMBRE ASC

USE SIGSALUD
GO
SELECT * FROM USUARIO WHERE USUARIO = 'ICHINCHAY'
SELECT * FROM USUARIOD WHERE USUARIO = 'ICHINCHAY'

