

(SELECT top 1 MEDICO FROM [SIGSALUD].[dbo].[MEDICO] WHERE DNI in (SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '084030'))




SELECT * FROM [SIGSALUD].[dbo].[MEDICO] WHERE NOMBRE LIKE '%CARO%'




SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '054031'


UPDATE [SIGSALUD].[dbo].[MEDICO] SET DNI = '29461431' WHERE MEDICO = 'RCJ'
UPDATE [BDPERSONAL].[dbo].[MAESTRO] SET DNI = '29415615' WHERE CODIGO =  '084703  '

SELECT * FROM [SIGSALUD].[dbo].[MEDICO] WHERE NOMBRE like 'herrera%'

herrera

41161063 

SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '084667'
union all
SELECT DNI FROM [SIGSALUD].[dbo].[MEDICO] WHERE NOMBRE like 'espinoza ori%'
43885905

SELECT * FROM [SIGSALUD].[dbo].[USUARIO_WEB]  WHERE NOMBREs like 'espinoza ori%'


43885901
084667


29415615

SELECT CONSULTORIO, NOMBRE, ABREVIATURA FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE  TIPO = 'C'
    AND NOMBRE LIKE (SELECT TOP 1 SUBSTRING(NOMBRE_CONSULTORIO,1,4) + '%' 
    FROM [SIGSALUD].[dbo].[V_CITA] WHERE MEDICO = ?lc_codigo_medico ORDER BY CITA_ID DESC)   ORDER BY NOMBRE
      
      
UPDATE [BDPERSONAL].[dbo].[MAESTRO] SET DNI = '43885905' WHERE CODIGO = '084667'


declare @lccodigo_medico varchar(10) = 084139
	declare @lnmes int = 2
	declare @lnanio int = 2018
	declare @ln_actividad int = 4
	select ('DIA' + RIGHT('00' + Ltrim(Rtrim(CONVERT(VARCHAR(2), DIA))),2) ) AS DIA, CONVERT(DATE, (CONVERT(VARCHAR(4), ANIO)  + '-' + CONVERT(VARCHAR(2), MES) + '-' + CONVERT(VARCHAR(2), DIA))) AS FECHA, TURNO, HORAS  
	from [BDPERSONAL].[dbo].[ACTIVIDAD_DETALLE] where CODIGO = @lccodigo_medico and ANIO =  @lnanio and MES = @lnmes and ID_ACTIVIDAD = @ln_actividad
	order by CONVERT(int, dia)
	
	
	SELECT CONSULTORIO, NOMBRE, ABREVIATURA FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE  TIPO = 'C'
      AND NOMBRE LIKE (SELECT TOP 1 SUBSTRING(NOMBRE_CONSULTORIO,1,4) + '%' FROM [SIGSALUD].[dbo].[V_CITA] 
      WHERE MEDICO = 'CGJ' ORDER BY CITA_ID DESC)
         ORDER BY NOMBRE
    
    
    
    SELECT CONSULTORIO, NOMBRE, ABREVIATURA FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE  TIPO = 'C'
      AND NOMBRE LIKE (SELECT TOP 1 SUBSTRING(NOMBRE_CONSULTORIO,1,4) + '%' FROM [SIGSALUD].[dbo].[V_CITA] 
      WHERE MEDICO = 'CGJ' ORDER BY CITA_ID DESC)
         ORDER BY NOMBRE
    
    
    
    SELECT  SUBSTRING(NOMBRE_CONSULTORIO,1,4) + '%' FROM [SIGSALUD].[dbo].[V_CITA] 
      WHERE MEDICO = 'CGJ' GROUP BY NOMBRE_CONSULTORIO ORDER BY CITA_ID DESC
      
    
    
    SELECT  NOMBRE_CONSULTORIO FROM [SIGSALUD].[dbo].[V_CITA] 
      WHERE MEDICO = 'CGJ' GROUP BY NOMBRE_CONSULTORIO 
      
    
    
SELECT CONSULTORIO, NOMBRE, ABREVIATURA FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE  TIPO = 'C'
      AND NOMBRE IN (SELECT  NOMBRE_CONSULTORIO FROM [SIGSALUD].[dbo].[V_CITA] 
      WHERE MEDICO = ?lc_codigo_medico GROUP BY NOMBRE_CONSULTORIO )        ORDER BY NOMBRE
    
  SELECT CONSULTORIO, NOMBRE, ABREVIATURA FROM [SIGSALUD].[dbo].[CONSULTORIO] WHERE  TIPO = 'C'
      AND NOMBRE LIKE (SELECT TOP 1 SUBSTRING(NOMBRE_CONSULTORIO,1,4) + '%' FROM [SIGSALUD].[dbo].[V_CITA] WHERE MEDICO = ?lc_codigo_medico ORDER BY CITA_ID DESC)   ORDER BY NOMBRE

    
    
        
    
      
      084030  
      CGJ
      
SELECT CONSULTORIO,  SUBSTRING(CONSULTORIO,1,2) + '%' FROM [SIGSALUD].[dbo].[CITA] WHERE MEDICO = 'VRH'      

SELECT TOP 1 SUBSTRING(NOMBRE_CONSULTORIO,1,3) FROM [SIGSALUD].[dbo].[V_CITA] WHERE MEDICO = 'VRH' ORDER BY CITA_ID DESC       