use  sigsalud

/* INSERTARLO EN TABLA CONSULTORIO */
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO]([CONSULTORIO],[NOMBRE],[ABREVIATURA],[ESPECIALIDAD],[TIPO],[ROL],[MUESTRAROL],[CC1],[CC2],[CC3],[ACTIVO],
   [ORDEN],[NUMERO],[CUPO],[CODESPE],[NOMESPE],[HIS_ESPECIALIDAD],[ACTIVO_WEB],[COD_RENAES],[DESC_RENAES],[HIS_CODSERVICIO],[HIS_NOMSERVICIO],
   [SCONSULTORIO],[SCCONSULTORIO],[ECONSULTORIO],[ECCONSULTORIO],[DEPARTAMENTO],[TIPOSERVICIO],[CODUPSSEEM],[upstrama])
select '1060' AS consultorio, 'DERMATOLOGIA 2 ' as nombre, 'DERMA' AS ABREVIATURA, '0018' AS ESPECIALIDAD, TIPO, ROL, MUESTRAROL,
CC1, CC2, CC3, ACTIVO, ORDEN, '58' NUMERO, '25' CUPO, '10' CODESPE, NOMESPE, HIS_ESPECIALIDAD, ACTIVO_WEB, COD_RENAES, DESC_RENAES, '300901' HIS_CODSERVICIO, HIS_NOMSERVICIO,
SCONSULTORIO, SCCONSULTORIO, ECONSULTORIO, ECCONSULTORIO, DEPARTAMENTO, TIPOSERVICIO, CODUPSSEEM, upstrama FROM CONSULTORIO where CONSULTORIO = '1017'




/* AGREGARLO EN CONSULTORIO_PARAMETRO */
delete from [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] where CONSULTORIO = '1060'
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] ([CONSULTORIO],[TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO],[ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO])
SELECT '1060' AS CONSULTORIO, [TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO], [ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO] FROM [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] WHERE CONSULTORIO = '1017' AND TURNO_CONSULTA IN ('M', 'T')


select * from [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] where CONSULTORIO = '1060'
delete from [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] where CONSULTORIO = '1060'

    
/* INSERTARLO EN TABLA CONSULTORIO */
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO]([CONSULTORIO],[NOMBRE],[ABREVIATURA],[ESPECIALIDAD],[TIPO],[ROL],[MUESTRAROL],[CC1],[CC2],[CC3],[ACTIVO],
   [ORDEN],[NUMERO],[CUPO],[CODESPE],[NOMESPE],[HIS_ESPECIALIDAD],[ACTIVO_WEB],[COD_RENAES],[DESC_RENAES],[HIS_CODSERVICIO],[HIS_NOMSERVICIO],
   [SCONSULTORIO],[SCCONSULTORIO],[ECONSULTORIO],[ECCONSULTORIO],[DEPARTAMENTO],[TIPOSERVICIO],[CODUPSSEEM],[upstrama])
select '1099' AS consultorio, 'ENDOCOSPIA DIGESTIVA' as nombre, 'ENDOCOS' AS ABREVIATURA, '0017' AS ESPECIALIDAD, TIPO, ROL, MUESTRAROL,
CC1, CC2, CC3, ACTIVO, ORDEN, '54' NUMERO, '10' CUPO, '10' CODESPE, NOMESPE, HIS_ESPECIALIDAD, ACTIVO_WEB, COD_RENAES, DESC_RENAES, '301301' HIS_CODSERVICIO, HIS_NOMSERVICIO,
SCONSULTORIO, SCCONSULTORIO, 'ENDOCOSPIA' ECONSULTORIO, ECCONSULTORIO, DEPARTAMENTO, TIPOSERVICIO, '301301' CODUPSSEEM, upstrama FROM CONSULTORIO where CONSULTORIO = '1016'

/* AGREGARLO EN CONSULTORIO_PARAMETRO */
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] ([CONSULTORIO],[TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO],[ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO])
    
SELECT '1099' AS CONSULTORIO, [TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO], '61356' [ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO] FROM CONSULTORIO_PARAMETRO WHERE CONSULTORIO = '1016' AND TURNO_CONSULTA NOT IN ('I', 'N')

    
    

USE SIGSALUD
SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'DERMAT%'



SELECT * FROM CONSULTORIO WHERE CONSULTORIO LIKE '1%' ORDER BY CONSULTORIO ASC

SELECT * FROM CONSULTORIO WHERE CONSULTORIO = '1060'