use SIGSALUD
/*
select * from ATENCIONC 
*/

alter table [SIGSALUD].[dbo].[ATENCIONC] add PERIMETRO_ABDOMINAL NUMERIC(13,2)  DEFAULT ((0))
alter table [SIGSALUD].[dbo].[ATENCIONC] add PERIMETRO_CEFALICO NUMERIC(13,2) DEFAULT ((0))
alter table [SIGSALUD].[dbo].[ATENCIONC] add PESO_PACIENTE NUMERIC(13,2)  DEFAULT ((0))
alter table [SIGSALUD].[dbo].[ATENCIONC] add TALLA_PACIENTE NUMERIC(13,2)  DEFAULT ((0))
alter table [SIGSALUD].[dbo].[ATENCIONC] add HEMOGLOBINA NUMERIC(13,2) DEFAULT ((0))
alter table [SIGSALUD].[dbo].[ATENCIONC] add FECHA_RESULTADO_HEMOGLOBINA VARCHAR(10)  DEFAULT ((''))


/*
UPDATE [SIGSALUD].[dbo].[ATENCIONC] SET PERIMETRO_ABDOMINAL = 0, PERIMETRO_CEFALICO = 0, HEMOGLOBINA = 0,FECHA_RESULTADO_HEMOGLOBINA = '', PESO_PACIENTE = 0, TALLA_PACIENTE = 0 
*/
