USE SIGSALUD
SELECT * FROM ARCHIVO_MOV WHERE NOMBRES LIKE 'PANEZ PRA%' ORDER BY FECHA DESC



SELECT * FROM ITEM WHERE CODCPT = 'D0150'
SELECT * FROM ITEM WHERE CODCPT = 'D0120'
SELECT * FROM ITEM WHERE CODCPT = 'D0160'
SELECT * FROM ITEM WHERE CODCPT = 'D0140'
D0120
SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE CODCPT = 'D0150')
SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE CODCPT = 'D0120')
SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE CODCPT = 'D0160')

SELECT * FROM ATENCIOND WHERE DX = 'D0150'
UPDATE ATENCIOND SET DX = 'D0120' WHERE DX = 'D0150'

SELECT * FROM ARCHIVO_MOV WHERE HISTORIA = '0207963'  ORDER BY FECHA DESC

SELECT * FROM ARCHIVO_MOV WHERE ID_CITA = '170118082'

0207963             


USE SIGSALUD

SELECT * FROM ARCHIVO_MOV WHERE NOMBRES LIKE 'MEZA OSOR%' ORDER BY FECHA DESC

SELECT * FROM ARCHIVO_MOV WHERE ID_CITA = '170118082'
UPDATE ARCHIVO_MOV SET USUARIOS = 'AGOYA' WHERE ID_CITA = '170118082'
UPDATE ARCHIVO_MOV SET USUARIOS = 'AGOYA' WHERE ID_CITA = '170118081'


SELECT * FROM V_ARCHIVOMOV WHERE ID_CITA = '170118082'
UNION ALL
SELECT * FROM V_ARCHIVOMOV WHERE ID_CITA = '170118081'
UNION ALL
SELECT * FROM V_ARCHIVOMOV WHERE ID_CITA = '170120545'

