USE SIGSALUD
SELECT * FROM CITA where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'CMP'  AND CONSULTORIO = '1034' AND TURNO_CONSULTA = 'M' AND ESTADO <> '1'

SELECT * FROM CITA where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'BOP'  AND CONSULTORIO = '1034' AND TURNO_CONSULTA = 'M' AND ESTADO <> '1'

SELECT * FROM CITA where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'CMP'  AND CONSULTORIO = '1034' AND TURNO_CONSULTA = 'M' AND ESTADO <> '1'




SELECT CITA_ID FROM CITA where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'CMP'  AND CONSULTORIO = '1034' AND TURNO_CONSULTA = 'M'



SELECT * FROM ARCHIVO_MOV where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'CMP'  AND CONSULTORIO = '1034'


UPDATE CITA SET MEDICO = 'CMP' where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'BOP'  AND CONSULTORIO = '1034'
UPDATE ARCHIVO_MOV SET MEDICO = 'CMP' where ID_CITA IN (SELECT CITA_ID FROM CITA 
where FECHA = convert(datetime, '2017-08-05', 101) and MEDICO = 'CMP'  AND CONSULTORIO = '1034' AND TURNO_CONSULTA = 'M' AND ESTADO <> '1')




