USE SIGSALUD 
GO

SET LANGUAGE Spanish;
	DECLARE @fecha_hoy VARCHAR(15);
	SET @fecha_hoy = CONVERT(VARCHAR(2),DAY(GETDATE())) + '/' + CONVERT(VARCHAR(2),MONTH(GETDATE())) + '/' + CONVERT(VARCHAR(4),YEAR(GETDATE()));		
	DECLARE @hora TIME(7);
	DECLARE @h_hora varchar(5);
	DECLARE @turno char(1);
	SET @hora=GETDATE();
	SET @h_hora = CONVERT(nvarchar(5), @hora, 108);
	if(@h_hora<'09:00')
		SET @turno='M';
	else if(@h_hora>='13:00' and @h_hora<'15:00')
		SET @turno='T';


INSERT INTO [SIGSALUD].[dbo].[TMP_CITASLIBERADAS] (CITA_ID, FECHA, FECHA_OTORGA, TIPO_PACIENTE, TIPO_CITA, PACIENTE, NOMBRE, SEGURO, ESTADO, HORA_OTORGA, TURNO_CONSULTA, CONSULTORIO, NOMBRE_CONSULTORIO, FECHAREGISTRO)
  	SELECT CITA_ID, FECHA, FECHA_OTORGA, TIPO_PACIENTE, TIPO_CITA, PACIENTE, NOMBRE, SEGURO, ESTADO, HORA_OTORGA,TURNO_CONSULTA, CONSULTORIO, NOMBRE_CONSULTORIO, GETDATE()
	FROM V_CITA WHERE ESTADO='2' AND FECHA=@fecha_hoy AND FECHA_OTORGA!=@fecha_hoy AND TURNO_CONSULTA=@turno;


/* TRUNCATE TABLE [SIGSALUD].[dbo].[TMP_CITASLIBERADAS] */

SELECT * FROM [SIGSALUD].[dbo].[TMP_CITASLIBERADAS]

SELECT * FROM [SIGSALUD].[dbo].[V_CITA]
 