select CONVERT(varchar(10), fecha, 103) as FECHA_OTORGADA, upper(NOMBRE_CONSULTORIO) as CONSULTORIO, upper(NOMBRE_ESPECIALIDAD) as ESPECIALIDAD
FROM [SIGSALUD].[dbo].[HIS] where fecha >= convert(datetime, '2017-02-01',101) and ESTADO in ('3', '4') 
group by CONVERT(varchar(10), fecha, 103), NOMBRE_CONSULTORIO, NOMBRE_ESPECIALIDAD   order by Fecha_Otorgada 



select DIA, HSERVICIO, PROF_CITA, COUNT(prof_cita) as CANTIDAD  from [SIGSALUD].[dbo].[HIS] where PERIODO = '022018'
group by DIA, HSERVICIO, PROF_CITA 
order by CONVERT(int, dia), HSERVICIO, PROF_CITA 


select CONVERT(VARCHAR(10), FECHA, 103) AS FECHA, NOMBRE_CONSULTORIO, NOMBRE_MEDICO, UPPER(NOMBRE_ESPECIALIDAD) AS ESPECIALIDAD from [SIGSALUD].[dbo].[V_CITA] where FECHA >= convert(datetime, '2018-02-23',101)
group by FECHA, NOMBRE_CONSULTORIO, NOMBRE_MEDICO, NOMBRE_ESPECIALIDAD
ORDER BY FECHA 

