use  sigsalud

/* INSERTARLO EN TABLA CONSULTORIO */
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO]([CONSULTORIO],[NOMBRE],[ABREVIATURA],[ESPECIALIDAD],[TIPO],[ROL],[MUESTRAROL],[CC1],[CC2],[CC3],[ACTIVO],
   [ORDEN],[NUMERO],[CUPO],[CODESPE],[NOMESPE],[HIS_ESPECIALIDAD],[ACTIVO_WEB],[COD_RENAES],[DESC_RENAES],[HIS_CODSERVICIO],[HIS_NOMSERVICIO],
   [SCONSULTORIO],[SCCONSULTORIO],[ECONSULTORIO],[ECCONSULTORIO],[DEPARTAMENTO],[TIPOSERVICIO],[CODUPSSEEM],[upstrama])
select '1099' AS consultorio, 'ENDOCOSPIA DIGESTIVA' as nombre, 'ENDOCOS' AS ABREVIATURA, '0017' AS ESPECIALIDAD, TIPO, ROL, MUESTRAROL,
CC1, CC2, CC3, ACTIVO, ORDEN, '54' NUMERO, '10' CUPO, '10' CODESPE, NOMESPE, HIS_ESPECIALIDAD, ACTIVO_WEB, COD_RENAES, DESC_RENAES, '301301' HIS_CODSERVICIO, HIS_NOMSERVICIO,
SCONSULTORIO, SCCONSULTORIO, 'ENDOCOSPIA' ECONSULTORIO, ECCONSULTORIO, DEPARTAMENTO, TIPOSERVICIO, '301301' CODUPSSEEM, upstrama FROM CONSULTORIO where CONSULTORIO = '1016'





/* AGREGARLO EN CONSULTORIO_PARAMETRO */
INSERT INTO [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] ([CONSULTORIO],[TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO],[ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO])
    
SELECT '1099' AS CONSULTORIO, [TURNO_CONSULTA],[OLD],[HORARIO_DE],[HORARIO_A],[ATENCIONES_DIA],[CITADOS_N],
   [CITADOS_C],[CITADOS_P],[CITADOS_O],[TIEMPO_N],[TIEMPO_C],[TIEMPO_P],[TIEMPO_O],[HORAS],[PRECIO_C],[PRECIO_N],[TIPO_PAGO], '64021' [ITEM_C],[ITEM_N],[PRINT_HORA],
    [CUPO_WEB],[NO_MOSTRAR_HORA_NUMERO] FROM CONSULTORIO_PARAMETRO WHERE CONSULTORIO = '5012'
    

SELECT * FROM ITEM WHERE NOMBRE LIKE '%DIGESTIVA%'

SELECT * FROM PRECIO WHERE ITEM = '63921'

SELECT * FROM PRECIO WHERE PRECIOA = 100 ORDER BY ITEM DESC

SELECT A.ITEM, B.NOMBRE, A.PRECIOA FROM PRECIO A LEFT JOIN ITEM B ON A.ITEM = B.ITEM 
 WHERE A.PRECIOA = 100 ORDER BY B.NOMBRE ASC






SELECT * FROM CONSULTORIO WHERE CONSULTORIO = '1016'

SELECT * FROM CONSULTORIO_PARAMETRO WHERE CONSULTORIO = '1016'


SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'ENDO%'

SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'GASTRO%'

SELECT * FROM CONSULTORIO ORDER BY CONSULTORIO ASC

SELECT * FROM CONSULTORIO WHERE CONSULTORIO = '1099'


SELECT * FROM CONSULTORIO WHERE NUMERO = '54'









