USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_CITASLIBERADAS]    Script Date: 10/23/2015 08:52:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_CITASLIBERADAS](
	[IDCITASLIBERADAS] [int] IDENTITY(1,1) NOT NULL,
	[CITA_ID] [char](9) NULL,
	[FECHA] [datetime] NULL,
	[FECHA_OTORGA] [datetime] NULL,
	[TIPO_PACIENTE] [char](10) NULL,
	[TIPO_CITA] [char](11) NULL,
	[PACIENTE] [char](10) NULL,
	[NOMBRE] [varchar](60) NULL,
	[SEGURO] [varchar](5) NULL,
	[ESTADO] [char](1) NULL,
	[HORA_OTORGA] [char](5) NULL,
	[TURNO_CONSULTA] [varchar](2) NULL,
	[CONSULTORIO] [char](10) NULL,
	[NOMBRE_CONSULTORIO] [varchar](50) NULL,
	[FECHAREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TMP_CITASLIBERADAS] PRIMARY KEY CLUSTERED 
(
	[IDCITASLIBERADAS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


