use SIGSALUD
select * from CONSULTORIO_PARAMETRO where TURNO_CONSULTA in ('M', 'T') and CONSULTORIO <> '0' order by TURNO_CONSULTA 

select a.CONSULTORIO, a.TURNO_CONSULTA, a.HORARIO_DE, a.HORARIO_A
 from CONSULTORIO_PARAMETRO a where a.TURNO_CONSULTA in ('M', 'T') and a.CONSULTORIO <> '0' order by a.TURNO_CONSULTA 
 
 
select a.CONSULTORIO, b.nombre, a.TURNO_CONSULTA, a.HORARIO_DE, a.HORARIO_A, a.ATENCIONES_DIA, a.CITADOS_N
 from CONSULTORIO_PARAMETRO a left join CONSULTORIO b on a.CONSULTORIO = b.CONSULTORIO
 -- where a.TURNO_CONSULTA in ('M', 'T') and a.CONSULTORIO <> '0' order by  b.CONSULTORIO
    
  where a.TURNO_CONSULTA in ('M', 'T') and a.CONSULTORIO <> '0' order by b.nombre, a.TURNO_CONSULTA 
  
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '8', CITADOS_N = '30' WHERE CONSULTORIO = '2027'
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '10', CITADOS_N = '30', HORARIO_DE = '08:00', HORARIO_A = '12:00'   WHERE CONSULTORIO = '4045'
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1014', '1026') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('2021', '2026', '2028') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '12', CITADOS_N = '30' WHERE CONSULTORIO IN ('4092') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '12', CITADOS_N = '30' WHERE CONSULTORIO IN ('5030', '5040', '5020') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('6082') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1017', '1060') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1020') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1020') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '5', CITADOS_N = '30' WHERE CONSULTORIO IN ('1099') and TURNO_CONSULTA in ('M')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '4', CITADOS_N = '30' WHERE CONSULTORIO IN ('1099') and TURNO_CONSULTA in ('T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('1016', '1021') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('4041', '4043') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1095', '1030') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('6083', '6089') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '12', CITADOS_N = '30' WHERE CONSULTORIO IN ('1027', '1034') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1011', '1012', '1022') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1013', '1024') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1015', '1098') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('5070', '5071') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('5070', '5071') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('4042') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '8', CITADOS_N = '30' WHERE CONSULTORIO IN ('5050', '5010', '5011', '5012') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '12', CITADOS_N = '30' WHERE CONSULTORIO IN ('2024') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('3031', '3032', '3033') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('6081') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('9095') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '8', CITADOS_N = '30' WHERE CONSULTORIO IN ('5080', '5090', '5060', '5061') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '18', CITADOS_N = '30' WHERE CONSULTORIO IN ('1028', '1031', '1032', '1029', '1033') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '16', CITADOS_N = '30' WHERE CONSULTORIO IN ('2022', '2029') and TURNO_CONSULTA in ('M', 'T')
update [SIGSALUD].[dbo].[CONSULTORIO_PARAMETRO] set ATENCIONES_DIA = '5', CITADOS_N = '30' WHERE CONSULTORIO IN ('4044') 




piscoprofilaxis --> 5

---


SELECT * FROM CONSULTORIO  ORDER BY NOMBRE 

SELECT * FROM CONSULTORIO_PARAMETRO WHERE CONSULTORIO = '4044'











