INSERT INTO PACIENTE (PACIENTE, hISTORIA, pATERNO, MATERNO, NOMBRE, NOMBRES, SEXO, ESTADO_CIVIL, FECHA_APERTURA, HORA_APERTURA,
               PADRE, MADRE, HIJOS, DIRECCION, DISTRITO, LOCALIDAD, TELEFONO1, TELEFONO2, EMAIL, LUGAR_NACIMIENTO,
                      EDAD, TIPO_DOCUMENTO, DOCUMENTO, PAIS, OCUPACION, GRADO_INSTRUCCION, CONYUGE_NOMBRE, CONYUGE_OCUPACION, RESPONSABLE_NOMBRE, RESPONSABLE_DIRECCION,
                      RESPONSABLE_PARENTESCO, RESPONSABLE_TRABAJO, RESPONSABLE_OCUPACION, RESPONSABLE_TELEFONO, SEGURO, MEDICO, CONSULTORIO, CONSULTORIO_OLD, ENTIDAD, fecharegistro, FECHA_NACIMIENTO,  SYSINSERT, USUARIO)
          values ('2017271741', '0246538', 'YUPANQUI', 'ANGELES', 'RN', 'YUPANQUI ANGELES RN', 'M', '0', convert(datetime,CONVERT(varchar(10), GETDATE(), 103),103), convert(char(8), CONVERT (TIME, GETDATE())),
              'YUPANQUI', 'ANGELES', 0, '', '150118','L01', '', '', '', '0',
               '00a00m00d', 'D', 'D' , '146', '00', '00','','0','',
               '','','','','','0','','2052', '2052','0', getdate(), CONVERT(datetime, '',103), '2017-03-05' + convert(varchar(100), GETDATE(),103) + ' ' + convert(char(8), CONVERT (TIME, GETDATE())), '99999999')
 
             UPDATE PACIENTE SET ESTADO_CIVIL = 'S', HIJOS = 0, DIRECCION = 'MODIFICAR', TELEFONO1 = '999999999', TELEFONO2 = '999999999', EMAIL = 'personal@empresa.com.pe',
              LUGAR_NACIMIENTO = '150101', DOCUMENTO = '99999999', OCUPACION = '01', GRADO_INSTRUCCION = '01', CONYUGE_NOMBRE = 'MODIFICAR', CONYUGE_OCUPACION = '05', RESPONSABLE_NOMBRE = 'MODIFICAR',
                 RESPONSABLE_DIRECCION = 'MODIFICAR', RESPONSABLE_PARENTESCO = 'MODIFICAR', RESPONSABLE_TRABAJO = 'MODIFICAR', RESPONSABLE_OCUPACION = 'MODIFICAR', RESPONSABLE_TELEFONO = '99999999',
                    SEGURO = '06', MEDICO = 'CLE', ENTIDAD = '210', CIEX = '000', CIEX_DESCRIPCION = '', RH = '0', GRUPO_SANGUINEO = '0000', ANIO = '2016', SYSUPDATE = CONVERT(VARCHAR(100), GETDATE(),103),
                       SYSDELETE =  '', TURNO_CONSULTA = 'M', FECHA_CONSULTA = '', DISTRITON = '1253', LNACIMIENTON = '197'  WHERE PACIENTE = '2017271741'

