/* PACIENTE, NO SE PRESENTO A LA  CITA CON EL MEDICO Y DEBE SER REPROGAMADO HACIA OTRA FECHA */

/* PRIMERO UBICAR POR APELLIDO EL PACIENTE EN LA CITA POR APELLIDOS Y NOMBRES */
/* SEGUNDA SOLUCION  : CAMBIAR EL PACIENTE A ESTADO 5, PARA QUE SE PUEDA DESBLOQUEAR */

/* PARA LIBERRAR UNA CITA, EL ESTDO DEBE ESTAR EN 2 */



USE SIGSALUD 
GO

declare @lnombre varchar(100) = 'menendez castillo'
DECLARE @lestado varchar(1) = '2'
declare @lcita_id varchar(50) = '150136627'  /* AQUI PONER LA CITA_ID */
declare @lcita_idn varchar(50) = '150136627'  /* AQUI PONER LA CITA_ID */

SELECT CITA_ID, CONSULTORIO, MEDICO, FECHA_PROGRAMACION, FECHA_OTORGA, FECHA_PAGO, FECHA_LIBRE, FECHA, HORA, TURNO_CONSULTA, PACIENTE, NOMBRE, PAGOID, SEGURO, ESTADO, HORA_OTORGA, NUMERO, USUARIO FROM CITA WHERE NOMBRE LIKE '%' +  @lnombre + '%' ORDER BY FECHA DESC
SELECT CITA_ID, CONSULTORIO, MEDICO, FECHA_PROGRAMACION, FECHA_OTORGA, FECHA_PAGO, FECHA_LIBRE, FECHA, HORA, TURNO_CONSULTA, PACIENTE, NOMBRE, PAGOID, SEGURO, ESTADO, HORA_OTORGA, NUMERO, USUARIO FROM CITA WHERE CITA_ID = @lcita_id

/* UNA VEZ IDENTIFICADO EL PACIENTE, OBTENER LA CITA_ID, PARA PODER CAMBIAR EL ESTADO  */
    UPDATE CITA SET estado = @lestado  where cita_id = @lcita_id       
    
SELECT CITA_ID, CONSULTORIO, MEDICO, FECHA_PROGRAMACION, FECHA_OTORGA, FECHA_PAGO, FECHA_LIBRE, FECHA, HORA, TURNO_CONSULTA, PACIENTE, NOMBRE, PAGOID, SEGURO, ESTADO, HORA_OTORGA, NUMERO, USUARIO FROM CITA WHERE CITA_ID = @lcita_idn
SELECT CITA_ID, CONSULTORIO, MEDICO, FECHA_PROGRAMACION, FECHA_OTORGA, FECHA_PAGO, FECHA_LIBRE, FECHA, HORA, TURNO_CONSULTA, PACIENTE, NOMBRE, PAGOID, SEGURO, ESTADO, HORA_OTORGA, NUMERO, USUARIO FROM CITA WHERE CITA_ID = @lcita_id

