/* dado el nombre del medico - ver todos sus atenciones */

declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
 
select A.CODIGO, A.IdServDepartUnid, B.Nombre, C.DNI_ACTUAL, D.DNI, D.MEDICO, C.NOMBRE AS NOMBRE_MEDICO  from [BDPERSONAL].[dbo].[ASISTENCIA]  A 
LEFT JOIN [BDPERSONAL].[dbo].[ServicioDepartUnidad] B ON A.IdServDepartUnid = B.IdServDepartUnid 
LEFT JOIN [BDPERSONAL].[dbo].[MAESTRO] C ON C.CODIGO = A.CODIGO LEFT JOIN [SIGSALUD].[dbo].[MEDICO] D ON D.DNI = C.DNI_ACTUAL
 where A.AÑO = YEAR(@lcfecha1) AND A.MES = MONTH(@lcfecha1) AND A.IdServDepartUnid NOT IN (2, 3, 4, 8, 11, 12, 13, 15, 21, 22, 23, 24, 25, 26, 27, 28, 42, 51, 52, 58, 59, 60, 61, 65, 66, 67,
68, 69, 70, 71, 72, 74, 75, 76, 78, 80, 81, 82, 83, 86, 87, 88, 93, 109, 110, 111, 113, 118) AND A.IdServDepartUnid IS NOT NULL AND  D.DNI IS NOT NULL 
GROUP BY A.CODIGO, A.IdServDepartUnid, B.Nombre, C.DNI_ACTUAL, C.NOMBRE, D.DNI, D.MEDICO, C.NOMBRE  ORDER BY C.NOMBRE   ASC
 
declare @lcfecha1 datetime = convert(datetime, '2017-08-01', 101)
declare @lcfecha2 datetime = convert(datetime, '2017-08-31', 101)
DECLARE @lcmedico varchar(3) = 'PCD' 
declare @lcnombre_medico varchar(250) =  'PALOMINO CALLE DICK RODRIGO' 
declare @lc_servicio varchar(200) = 'SERVICIO DE OFTALMOLOGIA'
/*
INSERT INTO [SIGSALUD].[dbo].[TMP_SERVICIOS_ATENCIONES]([SERVICIO],[MEDICO],[TIPO_ATENCION],[ATENCIONES])
*/
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO, 'CONSULTORIOS' AS TIPO_ATENCION,  COUNT(FECHA) AS ATENCIONES from 
[SIGSALUD].[dbo].[ATENCIONC] where FECHA between @lcfecha1 and @lcfecha2 and medico = @lcmedico
UNION ALL
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'EMERGENCIA - ATENCION' AS TIPO_ATENCION, COUNT(EMERGENCIA_ID) AS ATENCIONES    from [SIGSALUD].[dbo].[EMERGENCIA]
 where FECHA between @lcfecha1 and @lcfecha2  AND QUIEN_ATIENDE = @lcmedico
UNION ALL
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'EMERGENCIA - EVOLUCION' AS TIPO_ATENCION, COUNT(EMERGENCIA_ID) AS ATENCIONES
 FROM [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB]  where FECHA between @lcfecha1 and @lcfecha2 AND  PROFESIONAL = @lcmedico
UNION ALL 
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'HOSPITALIZACION - RECIBE' AS TIPO_ATENCION, COUNT(HOSPITALIZACION_ID) AS ATENCIONES from [SIGSALUD].[dbo].[HOSPITALIZACION]  where FECHA1 between @lcfecha1 and @lcfecha2 and RESPONSABLE1 = @lcmedico 
union all
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'HOSPITALIZACION - ATIENDE' AS TIPO_ATENCION, COUNT(HOSPITALIZACION_ID) AS ATENCIONES from [SIGSALUD].[dbo].[HOSPITALIZACION] where FECHA3 between @lcfecha1 and @lcfecha2 and RESPONSABLE3 = @lcmedico 
union all
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'HOSPITALIZACION - ATIENDE' AS TIPO_ATENCION, COUNT(HOSPITALIZACION_ID) AS ATENCIONES from [SIGSALUD].[dbo].[HOSPITALIZACION] where FECHA4 between @lcfecha1 and @lcfecha2 and RESPONSABLE4 = @lcmedico 
union all 
select @lc_servicio as SERVICIO, @lcnombre_medico  AS MEDICO,  'HOSPITALIZACION - DE ALTA' AS TIPO_ATENCION, COUNT(HOSPITALIZACION_ID) AS ATENCIONES from [SIGSALUD].[dbo].[HOSPITALIZACION] where FECHA1 between @lcfecha1 and @lcfecha2 and RESPONSABLE51 = @lcmedico  


SELECT * FROM [SIGSALUD].[dbo].[HOSPITALIZACION]







 



DECLARE @lcnombre VARCHAR(200) = 'CALDERON'
SELECT * FROM [SIGSALUD].[dbo].[MEDICO] WHERE NOMBRE LIKE '%' + @lcnombre + '%'
SELECT NOMBRE, DNI, DNI_ACTUAL, DNI_RELOG, codigo FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE NOMBRE LIKE '%' + @lcnombre + '%'
SELECT * FROM [SIGSALUD].[dbo].[USUARIO_WEB] WHERE NOMBRES LIKE '%' + @lcnombre + '%'
 
 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '42094073' WHERE CODIGO = '054012' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '42139649' WHERE CODIGO = '054015' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '08010224' WHERE CODIGO = '054002' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '15699210' WHERE CODIGO = '054032' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '09368322' WHERE CODIGO = '054035' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '23248752' WHERE CODIGO = '054044' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '06965298' WHERE CODIGO = '054168' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '09333533' WHERE CODIGO = '054169' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '06775153' WHERE CODIGO = '054005' 
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '41033453' WHERE CODIGO = '054031' 
 UPDATE [SIGSALUD].[dbo].[MEDICO]  SET DNI = '08010224' WHERE MEDICO = 'MCA'
 UPDATE [SIGSALUD].[dbo].[MEDICO]  SET DNI = '09137316' WHERE MEDICO = 'GGJ'
 UPDATE [SIGSALUD].[dbo].[MEDICO]  SET DNI = '10245143' WHERE MEDICO = 'TLM'
 UPDATE [SIGSALUD].[dbo].[MEDICO]  SET DNI = '40106449' WHERE MEDICO = 'VTC'
 UPDATE [SIGSALUD].[dbo].[MEDICO]  SET DNI = '29415615' WHERE MEDICO = 'AME'
 UPDATE [BDPERSONAL].[dbo].[MAESTRO]  SET DNI_ACTUAL = '29415615' WHERE CODIGO = '084703' 
 DELETE FROM [BDPERSONAL].[dbo].[ServicioMaestro]  WHERE CODIGO = '054023'
 DELETE FROM [BDPERSONAL].[dbo].[MAESTRO]  WHERE CODIGO = '054023'
 UPDATE [BDPERSONAL].[dbo].[MAESTRO] SET DNI = '41249255', DNI_ACTUAL = '41249255', DNI_RELOG = '41249255'  WHERE CODIGO = '054174'
 
 
 
 
 
 
 
 
 
 