use BDPERSONAL

SELECT DNI, CODIGO, CODACT, CONVERT(VARCHAR(2), DIA) AS DD, CONVERT(VARCHAR(2), MES) AS MM, convert(varchar(4), AÑO) as anio, HORAI, HORAS, IdServDepartUnid, INDICADOR, case when INDICADOR = '4'  then 'CERRADO' ELSE 'NO TIENE CIERRE' END AS INDICA
   FROM ASISTENCIA WHERE CODIGO = '084619' AND MES = 6 AND AÑO = 2017 ORDER BY DIA ASC
   
   
SELECT CODIGO, DNI, DNI_ACTUAL FROM MAESTRO WHERE CODIGO = '084619'

SELECT MEDICO, NOMBRE FROM [SIGSALUD].[dbo].[MEDICO] WHERE DNI IN (SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '084619')

SELECT * FROM [SIGSALUD].[dbo].[CITA] WHERE MONTH(FECHA) = 6 AND YEAR(FECHA) = 2017 AND    MEDICO IN (SELECT MEDICO
FROM [SIGSALUD].[dbo].[MEDICO] WHERE DNI IN (SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '084619'))
      
      
SELECT * FROM [SIGSALUD].[dbo].[V_CITA] WHERE DAY(FECHA) = 13 AND MONTH(FECHA) = 6 AND YEAR(FECHA) = 2017 AND    MEDICO IN (SELECT MEDICO
FROM [SIGSALUD].[dbo].[MEDICO] WHERE DNI IN (SELECT DNI FROM [BDPERSONAL].[dbo].[MAESTRO] WHERE CODIGO = '084619'))
ORDER BY TURNO_CONSULTA, NUMERO ASC
      