/* VER LAS ELIMINACIONES DE LOS FORMATOS DE SEGUOR */

use SIGSALUD
/* VER LOS REGISTROS DE ATENCION EN SEGURO ELIMINADOS */
select USER_ELIMINACION, FECHA_HORA_ELIMINACION, CITA_ID,  * from ATENCION_SEGURO WHERE USER_ELIMINACION IS NOT NULL order by FECHA_ATENCION desc

/* LA FECHA DE PROGRAMACION, ES LA FECHA EN DONDE SE GENERA LA CITA */
select USER_ELIMINACION, FECHA_HORA_ELIMINACION, * from cita  WHERE USER_ELIMINACION IS NOT NULL order by FECHA_PROGRAMACION  desc