

DECLARE @lcfecha1 varchar(10) = '2018-04-01'
DECLARE @lcfecha2 varchar(10) = '2018-04-04'

SELECT @lcfecha1 as DESDE, @lcfecha2 AS HASTA, NOMBRE_CONSULTORIO, TURNO_CONSULTA, COUNT(TURNO_CONSULTA) AS EMITIDA 
FROM [SIGSALUD].[dbo].[V_CITA] WHERE FECHA BETWEEN CONVERT(DATETIME, @lcfecha1, 101) AND CONVERT(DATETIME, @lcfecha2, 101)
AND ESTADO >= 2 
GROUP BY NOMBRE_CONSULTORIO, TURNO_CONSULTA ORDER BY NOMBRE_CONSULTORIO