use SIGSALUD

select * from PACIENTE where HISTORIA = '0247030'

select * from CUENTA where CUENTAID = '1719224'


declare @lidcuenta varchar(7) = (SELECT top 1 convert(int, cuentaid)   FROM CUENTA ORDER BY CUENTAID DESC) + 1
declare @lidcuentanuevo char(7) = convert(char(7), @lidcuenta)
INSERT INTO [SIGSALUD].[dbo].[CUENTA]([CUENTAID],[PACIENTE],[SEGURO],[EMPRESASEGURO],[OBSERVACION],[FECHA_APERTURA],[PAGOID],[AUTORIZA_NUMERO],
  [ESTADO],[HORA_APERTURA],[HORA_CIERRE],[HORA_PAGO],[NOMBRE],[ORIGEN],[USUARIO_APERTURA])
 values (@lidcuentanuevo,'2017272233', '0', '0', '',convert(datetime, '2017-03-25', 101), '', '', '1', '14:57', '', '', 'JARAMILLO GONZALES ROSA', 'EM', 'MCALIXTO')
 

SELECT *  FROM CUENTA ORDER BY CUENTAID DESC


SELECT *  FROM CUENTA WHERE SEGURO = '0' AND ESTADO = '1' ORDER BY CUENTAID DESC


SELECT *  FROM CUENTA WHERE CUENTAID = '1719501'

SELECT *  FROM V_CUENTA WHERE CUENTAID = '1719501'
UNION ALL
SELECT *  FROM CUENTA WHERE CUENTAID = '1718895'

UPDATE CUENTA SET ORIGEN = 'HO', CONSULTORIO = '1090' WHERE CUENTAID = '1719501'


SELECT * FROM EMERGENCIA WHERE EMERGENCIA_ID = '17012119'



SELECT *  FROM CUENTA WHERE CUENTAID = '1719501'
UNION ALL
SELECT *  FROM CUENTA WHERE CUENTAID = '1719501'
UNION ALL
SELECT *  FROM CUENTA WHERE CUENTAID = '1719224'