declare @lcnombre varchar(250) = '1633609'
  SELECT CUENTAID, PACIENTE, case when SEGURO = '0' then 'PAGANTE' WHEN SEGURO = '01' THEN 'SIS' WHEN SEGURO = '02' THEN 'SOAT' WHEN SEGURO = '03' THEN 'SEMI SUBSIDIADO' 
   WHEN SEGURO = '04' THEN 'OTROS SEGUROS' WHEN SEGURO = '05' THEN 'CREDITO PACIENTE' WHEN SEGURO = '06' THEN 'ESSALUD' WHEN SEGURO = '07' THEN 'SANIDAD EP' 
   WHEN SEGURO = '08' THEN 'SEGURO PRIVADO' WHEN SEGURO = '09' THEN 'CONSTRUYENDO PERU' WHEN SEGURO = '10' THEN 'SANIDAD FAP'  WHEN SEGURO = '10' THEN 'SANIDAD NAVAL'  
   WHEN SEGURO = '12' THEN 'SANIDAD PNP'  WHEN SEGURO = '13' THEN 'PACIENTE PROGRAMAS'  WHEN SEGURO = '14' THEN 'EXONERADO'  WHEN SEGURO = '15' THEN 'SIS NRUS'  
   WHEN SEGURO = '16' THEN 'INTERCONSULTA'  ELSE 'NO  DEFINIDO' END AS TIPO_SEGURO, convert(varchar(10), fecha_apertura, 103) as FECHA_APER, CARGO, DESCUENTO, ABONO, IMPORTE, ESTADO, HORA_APERTURA, NOMBRE,
   CASE WHEN ORIGEN = 'EM' THEN 'EMERGENCIA' WHEN ORIGEN = 'HO' THEN 'HOSPITALIZACION' WHEN ORIGEN = 'LB' THEN 'LABORATORIO' WHEN ORIGEN = 'CE' THEN 'CONSULTA EXTERNA'  WHEN ORIGEN = 'AD' THEN 'APOYO AL DIAGNOSTICO'
    WHEN ORIGEN = 'OT' THEN 'OTROS' ELSE 'NO DEFINIDO' END AS TIPO_ORIGEN, USUARIO_APERTURA, NROFUA, HORA_APERTURA, FECHA_ACTIVACION, USER_ACTIVACION, PC_ACTIVACION
  FROM CUENTA where CUENTAID = @lcnombre  ORDER BY nrofua DESC  
  
  
select * from CUENTA  order by FECHA_APERTURA desc 

alter table cuenta add FECHA_ACTIVACION DATETIME
alter table cuenta add USER_ACTIVACION VARCHAR(50)
alter table cuenta add PC_ACTIVACION VARCHAR(70)
USE SIGSALUD
alter table emergencia_det_web add FACTOR4 VARCHAR(80)

select * from emergencia_det_web where emergencia_id = '17026070'