use SIGSALUD
select * from CUENTA where CUENTAID = '1724015' 
select  SUM(total) as tt from CUENTADET where CUENTAID = '1724015'   





select SUM(total) as tt from CUENTADET where CUENTAID = '1724015'  and ORDENID = '1717046447'

delete from CUENTADET where CUENTAID = '1724015'  and ITEM like '17%'

INSERT INTO [SIGSALUD].[dbo].[CUENTADET]([CUENTAID],[ITEM],[PRECIO],[CANTIDAD],[IMPORTE],[DESCUENTO],[TOTAL],[TIPO_PAGO],[CATEGORIA],[ORDENID])
select '1724015'  as cuentaid, ITEM, PRECIO, CANTIDAD, IMPORTE, DESCUENTO, SUBTOTAL AS TOTAL, '' AS TIPO_PAGO, 'A' CATEGORIA, ORDENID from ORDEND where ORDENID = '1717046447' 

INSERT INTO [SIGSALUD].[dbo].[CUENTADET]([CUENTAID],[ITEM],[PRECIO],[CANTIDAD],[IMPORTE],[DESCUENTO],[TOTAL],[TIPO_PAGO],[CATEGORIA],[ORDENID])
select '1724015'  as cuentaid, ITEM, PRECIO, CANTIDAD, IMPORTE, DESCUENTO, SUBTOTAL AS TOTAL, '' AS TIPO_PAGO, 'A' CATEGORIA, ORDENID from ORDEND where ORDENID = '1717046441' 



select * from CUENTADET where ORDENID = '1717046441' 



select * from ORDEND where ORDENID = '1717046441' 



declare @lccuentaid varchar(13) =  '1724015' 
  update [SIGSALUD].[dbo].[CUENTADET] set IMPORTE = PRECIO*CANTIDAD WHERE CUENTAID = @lccuentaid
  update [SIGSALUD].[dbo].[CUENTADET] set TOTAL = IMPORTE-DESCUENTO WHERE CUENTAID = @lccuentaid
  UPDATE [SIGSALUD].[dbo].[CUENTA] SET CARGO = (SELECT SUM(TOTAL) FROM [SIGSALUD].[dbo].[CUENTADET]  WHERE CUENTAID = @lccuentaid) WHERE CUENTAID = @lccuentaid
  update [SIGSALUD].[dbo].[CUENTA] set IMPORTE = CARGO-DESCUENTO+ABONO where CUENTAID = @lccuentaid
  


