use SIGSALUD
select CUENTAID, nombre, case when SEGURO = '0' then 'PAGANTE' WHEN SEGURO = '01' THEN 'SIS' WHEN SEGURO = '02' THEN 'SOAT' WHEN SEGURO = '03' THEN 'SEMI SUBSIDIADO' 
   WHEN SEGURO = '04' THEN 'OTROS SEGUROS' WHEN SEGURO = '05' THEN 'CREDITO PACIENTE' WHEN SEGURO = '06' THEN 'ESSALUD' WHEN SEGURO = '07' THEN 'SANIDAD EP' 
   WHEN SEGURO = '08' THEN 'SEGURO PRIVADO' WHEN SEGURO = '09' THEN 'CONSTRUYENDO PERU' WHEN SEGURO = '10' THEN 'SANIDAD FAP'  WHEN SEGURO = '10' THEN 'SANIDAD NAVAL'  
   WHEN SEGURO = '12' THEN 'SANIDAD PNP'  WHEN SEGURO = '13' THEN 'PACIENTE PROGRAMAS'  WHEN SEGURO = '14' THEN 'EXONERADO'  WHEN SEGURO = '15' THEN 'SIS NRUS'  
   WHEN SEGURO = '16' THEN 'INTERCONSULTA'  ELSE 'NO  DEFINIDO' END AS TIPO_SEGURO, FECHA_APERTURA, HORA_APERTURA, ESTADO, 
    CASE WHEN ORIGEN = 'EM' THEN 'EMERGENCIA' WHEN ORIGEN = 'HO' THEN 'HOSPITALIZACION' WHEN ORIGEN = 'LB' THEN 'LABORATORIO' WHEN ORIGEN = 'CE' THEN 'CONSULTA EXTERNA'
    WHEN ORIGEN = 'OT' THEN 'OTROS' ELSE 'NO DEFINIDO' END AS TIPO_ORIGEN, USUARIO_APERTURA, NROFUA    from CUENTA where nombre like 'garcia%' order by cuentaid desc

select ESTADO from CUENTA group by ESTADO 

0 - anulado
1- activo
2-pre liquidado
4-cancelado o auditado
7 / 8 /9 cuentas antiguas


select ORIGEN  from CUENTA group by ORIGEN 

select seguro  from CUENTA group by seguro

select * from SEGURO order by SEGURO asc

