
select * from [SIGSALUD].[dbo].[CUENTA] WHERE ESTADO='2' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA = CONVERT(datetime, '2018-01-14', 101)  AND SEGURO='01';

update [SIGSALUD].[dbo].[CUENTA] set estado = '1' WHERE ESTADO='2' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA = CONVERT(datetime, '2018-01-15', 101)  AND SEGURO='01';

select * from [SIGSALUD].[dbo].[CUENTA] WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA = CONVERT(datetime, '2018-01-15', 101)  AND SEGURO='01';


select * from [SIGSALUD].[dbo].[CUENTA] WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA < CONVERT(datetime, '2018-01-12', 101)  AND SEGURO='01'
order by cuentaid desc



  UPDATE CUENTA SET ESTADO='2' WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA<=getdate() AND SEGURO='01';
	  DELETE FROM CUENTADET WHERE ORDENID IN (SELECT ORDENID FROM ORDENC WHERE FECHA>='01/12/2016' AND ESTADO='0');
	  


select * from [SIGSALUD].[dbo].[CUENTA] WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA<getdate() AND SEGURO='01';

select * from [SIGSALUD].[dbo].[CUENTA] WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA = getdate() AND SEGURO='01';

update [SIGSALUD].[dbo].[CUENTA] set estado = '2' WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA<getdate() AND SEGURO='01';



	  DELETE FROM CUENTADET WHERE ORDENID IN (SELECT ORDENID FROM ORDENC WHERE FECHA>='01/12/2016' AND ESTADO='0');
	  


UPDATE [SIGSALUD].[dbo].[CUENTA] SET ESTADO='2' WHERE ESTADO='1' AND ORIGEN IN ('CE','OT','LB', 'AD') AND FECHA_APERTURA<=getdate() AND SEGURO='01';
	  DELETE FROM CUENTADET WHERE ORDENID IN (SELECT ORDENID FROM ORDENC WHERE FECHA>='01/12/2016' AND ESTADO='0');
	  
	  


declare @lcfecha varchar(10) = CONVERT(DATE, GETDATE(), 103)
update [SIGSALUD].[dbo].[CUENTA] set estado = '2' where estado = '1' and seguro = '01' and ORIGEN = 'EM' and  CUENTAID in 
(select CUENTAID  from [SIGSALUD].[dbo].[EMERGENCIA] where ESTADO in ('4', '5')  AND SEGURO = '01' AND 
FECHA  = CONVERT(DATETIME, @lcfecha, 101) and datediff (hh, CONVERT(TIME, HORA_SAL), CONVERT(TIME, GETDATE())) >= 6)
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN = 'CE' AND SEGURO = '01' AND FECHA_APERTURA < CONVERT(DATETIME, @lcfecha, 101) 	


/* cierre a las 6 horas  */
exec dbo.SP_CIERRE_CUENTAS_LIQUIDACIONES_EMERGENCIA  

/* cierre de cuentas anteriores */

exec dbo.SP_CIERRE_CUENTAS_LIQUIDACIONES_EMERGENCIA  
exec dbo.SP_CIERRE_CUENTAS_LIQUIDACIONES_ANTERIORES


declare @lcfecha_revisar datetime = convert(datetime, CONVERT(VARCHAR(10), GETDATE() - 1, 120) ,101)
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE CUENTAID IN (SELECT B.CUENTAID FROM [SIGSALUD].[dbo].[EMERGENCIA] A LEFT JOIN 
[SIGSALUD].[dbo].[CUENTA] B ON A.CUENTAID = B.CUENTAID where A.ESTADO in ('4', '5')  AND A.SEGURO = '01' AND A.FECHA  <= @lcfecha_revisar
AND B.ORIGEN = 'EM' AND B.ESTADO = '1')
UPDATE [SIGSALUD].[dbo].[CUENTA]  SET ESTADO = '2' WHERE ESTADO = '1' and ORIGEN IN ('LB', 'CE', 'OT', 'AD') AND SEGURO = '01' AND FECHA_APERTURA <= CONVERT(DATETIME, @lcfecha_revisar, 101) 
