/* select cuentaid from [dbo].[TMP_CTA_REV] */
declare @lcfecha1 varchar(10) = '2016-12-01'
declare @lcfecha2 varchar(10) = '2016-12-30'
SELECT CUENTAID, PACIENTE, case when SEGURO = '0' then 'PAGANTE' WHEN SEGURO = '01' THEN 'SIS' WHEN SEGURO = '02' THEN 'SOAT' WHEN SEGURO = '03' THEN 'SEMI SUBSIDIADO' 
   WHEN SEGURO = '04' THEN 'OTROS SEGUROS' WHEN SEGURO = '05' THEN 'CREDITO PACIENTE' WHEN SEGURO = '06' THEN 'ESSALUD' WHEN SEGURO = '07' THEN 'SANIDAD EP' 
   WHEN SEGURO = '08' THEN 'SEGURO PRIVADO' WHEN SEGURO = '09' THEN 'CONSTRUYENDO PERU' WHEN SEGURO = '10' THEN 'SANIDAD FAP'  WHEN SEGURO = '10' THEN 'SANIDAD NAVAL'  
   WHEN SEGURO = '12' THEN 'SANIDAD PNP'  WHEN SEGURO = '13' THEN 'PACIENTE PROGRAMAS'  WHEN SEGURO = '14' THEN 'EXONERADO'  WHEN SEGURO = '15' THEN 'SIS NRUS'  
   WHEN SEGURO = '16' THEN 'INTERCONSULTA'  ELSE 'NO  DEFINIDO' END AS TIPO_SEGURO, convert(varchar(10), fecha_apertura, 103) as FECHA_APER, CARGO, DESCUENTO, ABONO, IMPORTE, ESTADO, HORA_APERTURA, NOMBRE,
   CASE WHEN ORIGEN = 'EM' THEN 'EMERGENCIA' WHEN ORIGEN = 'HO' THEN 'HOSPITALIZACION' WHEN ORIGEN = 'LB' THEN 'LABORATORIO' WHEN ORIGEN = 'CE' THEN 'CONSULTA EXTERNA'
    WHEN ORIGEN = 'OT' THEN 'OTROS' ELSE 'NO DEFINIDO' END AS TIPO_ORIGEN, USUARIO_APERTURA, NROFUA
 FROM CUENTA where fecha_apertura between convert(datetime, @lcfecha1,101) and convert(datetime,@lcfecha2 ,101)  ORDER BY FECHA_APERTURA DESC
 
 
 select * from CUENTA where CUENTAID = '1640198'
select * from CUENTADET where CUENTAID = '1647481'


select CUENTAID, PACIENTE, SEGURO, FECHA_APERTURA, FECHA_CIERRE, FECHA_PAGO, CARGO, DESCUENTO, IMPORTE, ESTADO, HORA_APERTURA, NOMBRE, ORIGEN, USUARIO_APERTURA
 from CUENTA where cuentaid in (select cuentaid from [dbo].[TMP_CTA_REV]) order by CUENTAID desc
 
 /* select *  from CUENTADET where cuentaid in (select CUENTAID from CUENTA where cuentaid in (select cuentaid from [dbo].[TMP_CTA_REV])) order by CUENTAID desc */
 
 select CUENTAID, SUM(TOTAL) as ttotal from CUENTADET where cuentaid in (select CUENTAID from CUENTA where cuentaid in (select cuentaid from [dbo].[TMP_CTA_REV])) group by CUENTAID 
 order by CUENTAID desc
 
 
 
 
 SELECT SEGURO FROM CUENTA GROUP BY SEGURO ORDER BY SEGURO
 
 
SELECT * FROM dbo.SEGURO ORDER BY SEGURO ASC

 SELECT ESTADO FROM CUENTA GROUP BY ESTADO  ORDER BY ESTADO 
 
 
   declare @lcnombre varchar(250) = 'garcia'
 SELECT CUENTAID, PACIENTE, case when SEGURO = '0' then 'PAGANTE' WHEN SEGURO = '01' THEN 'SIS' WHEN SEGURO = '02' THEN 'SOAT' WHEN SEGURO = '03' THEN 'SEMI SUBSIDIADO' 
   WHEN SEGURO = '04' THEN 'OTROS SEGUROS' WHEN SEGURO = '05' THEN 'CREDITO PACIENTE' WHEN SEGURO = '06' THEN 'ESSALUD' WHEN SEGURO = '07' THEN 'SANIDAD EP' 
   WHEN SEGURO = '08' THEN 'SEGURO PRIVADO' WHEN SEGURO = '09' THEN 'CONSTRUYENDO PERU' WHEN SEGURO = '10' THEN 'SANIDAD FAP'  WHEN SEGURO = '10' THEN 'SANIDAD NAVAL'  
   WHEN SEGURO = '12' THEN 'SANIDAD PNP'  WHEN SEGURO = '13' THEN 'PACIENTE PROGRAMAS'  WHEN SEGURO = '14' THEN 'EXONERADO'  WHEN SEGURO = '15' THEN 'SIS NRUS'  
   WHEN SEGURO = '16' THEN 'INTERCONSULTA'  ELSE 'NO  DEFINIDO' END AS TIPO_SEGURO, convert(varchar(10), fecha_apertura, 103) as FECHA_APER, CARGO, DESCUENTO, ABONO, IMPORTE, ESTADO, HORA_APERTURA, NOMBRE,
   CASE WHEN ORIGEN = 'EM' THEN 'EMERGENCIA' WHEN ORIGEN = 'HO' THEN 'HOSPITALIZACION' WHEN ORIGEN = 'LB' THEN 'LABORATORIO' WHEN ORIGEN = 'CE' THEN 'CONSULTA EXTERNA'
    WHEN ORIGEN = 'OT' THEN 'OTROS' ELSE 'NO DEFINIDO' END AS TIPO_ORIGEN, USUARIO_APERTURA, NROFUA
  FROM CUENTA where nombre like '%' + @lcnombre + '%'  ORDER BY nrofua DESC    
   
   
   
   declare @lcnombre varchar(250) = 'garcia'
 SELECT CUENTAID, PACIENTE, case when SEGURO = '0' then 'PAGANTE' WHEN SEGURO = '01' THEN 'SIS' WHEN SEGURO = '02' THEN 'SOAT' WHEN SEGURO = '03' THEN 'SEMI SUBSIDIADO' 
   WHEN SEGURO = '04' THEN 'OTROS SEGUROS' WHEN SEGURO = '05' THEN 'CREDITO PACIENTE' WHEN SEGURO = '06' THEN 'ESSALUD' WHEN SEGURO = '07' THEN 'SANIDAD EP' 
   WHEN SEGURO = '08' THEN 'SEGURO PRIVADO' WHEN SEGURO = '09' THEN 'CONSTRUYENDO PERU' WHEN SEGURO = '10' THEN 'SANIDAD FAP'  WHEN SEGURO = '10' THEN 'SANIDAD NAVAL'  
   WHEN SEGURO = '12' THEN 'SANIDAD PNP'  WHEN SEGURO = '13' THEN 'PACIENTE PROGRAMAS'  WHEN SEGURO = '14' THEN 'EXONERADO'  WHEN SEGURO = '15' THEN 'SIS NRUS'  
   WHEN SEGURO = '16' THEN 'INTERCONSULTA'  ELSE 'NO  DEFINIDO' END AS TIPO_SEGURO, convert(varchar(10), fecha_apertura, 103) as FECHA_APER, CARGO, DESCUENTO, ABONO, IMPORTE, ESTADO, HORA_APERTURA, NOMBRE,
   CASE WHEN ORIGEN = 'EM' THEN 'EMERGENCIA' WHEN ORIGEN = 'HO' THEN 'HOSPITALIZACION' WHEN ORIGEN = 'LB' THEN 'LABORATORIO' WHEN ORIGEN = 'CE' THEN 'CONSULTA EXTERNA'
    WHEN ORIGEN = 'OT' THEN 'OTROS' ELSE 'NO DEFINIDO' END AS TIPO_ORIGEN, USUARIO_APERTURA, NROFUA
  FROM CUENTA   ORDER BY nrofua DESC    
  
   
    
  FROM CUENTA where nombre like '%' + @lcnombre + '%'  ORDER BY FECHA_APERTURA DESC
