USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[ABONO]    Script Date: 12/17/2015 17:37:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ABONO](
	[ABONOID] [char](7) NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[CUENTAID] [char](7) NOT NULL,
	[OBSERVACION] [varchar](50) NOT NULL,
	[PAGOID] [char](8) NOT NULL,
	[TOTAL] [numeric](18, 2) NOT NULL,
	[USUARIO] [char](15) NOT NULL,
	[ESTADO] [char](1) NOT NULL,
PRIMARY KEY NONCLUSTERED 
(
	[ABONOID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ABONO]  WITH CHECK ADD FOREIGN KEY([CUENTAID])
REFERENCES [dbo].[CUENTA] ([CUENTAID])
GO

ALTER TABLE [dbo].[ABONO] ADD  DEFAULT (' ') FOR [OBSERVACION]
GO

ALTER TABLE [dbo].[ABONO] ADD  DEFAULT ((0)) FOR [TOTAL]
GO

ALTER TABLE [dbo].[ABONO] ADD  DEFAULT ('1') FOR [ESTADO]
GO


