use sigsalud 
DROP TABLE dbo.ABONO;
DROP TABLE dbo.CITA_ID_GGJ_COLPOSCOPIA_18_03_2015
DROP TABLE dbo.CITA_ID_GGJ_GINECOLOGIA2_18_03_2015
DROP TABLE [SIGSALUD].[dbo].[CUPO_CONSULT_CITA]
DROP TABLE DNI
DROP TABLE [SIGSALUD].[dbo].[EMERGENCIA_DET_WEB_BACKUP]
DROP TABLE dbo.ENTIDADSIS_09092015_19_38
DROP TABLE dbo.ENTIDADSIS_BACKUP2
DROP TABLE dbo.ICI_COPIA
DROP TABLE [SIGSALUD].[dbo].[ITEM_DETALLE]
DROP TABLE [SIGSALUD].[dbo].[KARDEX_170093]
DROP TABLE [SIGSALUD].[dbo].[NIVEL_ESS]
DROP TABLE [SIGSALUD].[dbo].[NUMEROS]
DROP TABLE [SIGSALUD].[dbo].[OCURRENCIAC_TEST]
DROP TABLE dbo.pagoc_backup
DROP TABLE dbo.pagod_backup
drop table dbo.PRUEBA
drop table [SIGSALUD].[dbo].[RESULTADO_PLANTILLA]
drop table dbo.STOCK_ANTES
drop table dbo.stock2
drop table [SIGSALUD].[dbo].[TABEDADCAB]
drop table [SIGSALUD].[dbo].[TABSITUACION_ANTIGUA]
drop table [SIGSALUD].[dbo].[TMP_STOCK_FECHA]
drop table [SIGSALUD].[dbo].[TMP_TOHISTTOARCH]
drop table [SIGSALUD].[dbo].[ZROL_ARCHIVO]
drop table [SIGSALUD].[dbo].[ZFRACCION]
drop table [SIGSALUD].[dbo].[TMP_ZETAS]
drop table [SIGSALUD].[dbo].[TMP_CODIGO]
drop table dbo.HIS_CAMPANA_042015
drop table [SIGSALUD].[dbo].[HIS_04_05_2015]
drop table dbo.HIS_TEMP








