/* Limpiar BDPersonal  */

use BDPERSONAL
drop table dbo.CADENA
DROP TABLE [BDPERSONAL].[dbo].[CAS]
DROP TABLE [BDPERSONAL].[dbo].[CONTROLMES]
DROP TABLE [BDPERSONAL].[dbo].[DATOSEXCEL]
DROP TABLE dbo.ESTUDIOS
DROP TABLE [BDPERSONAL].[dbo].[EVALUA]
DROP TABLE dbo.META
DROP TABLE dbo.T_Horarios_TEMP
TRUNCATE TABLE dbo.TMPASISTENCIACAS
TRUNCATE TABLE dbo.TMPHISTORICOPERSONALCAS
TRUNCATE TABLE dbo.TMPPERSONALCAS



