USE SIGSALUD
SELECT * FROM ITEM  WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'

SELECT REPLACE(ITEM, '0', cadena_nueva)

SELECT '6'  + SUBSTRING(ITEM, 3,4) FROM ITEM  WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'

SELECT * into sis_1 FROM ITEM  WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'


UPDATE ITEM SET ITEM = '6'  + SUBSTRING(ITEM, 3,4) WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'

SELECT * FROM PRECIO WHERE SUBSTRING(ITEM,1,1) = '6' 

select * from sis_1  order by ITEM desc
delete from ITEM WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'



UPDATE sis_1 SET ITEM = '6'  + '0' + SUBSTRING(ITEM, 3,4) WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7'

select * from PRECIO WHERE SUBSTRING(ITEM,1,1) = '6' and ITEM = '63419'
select * from PRECIO WHERE SUBSTRING(ITEM,1,1) = '6' and ITEM in ('63419', '603419')


