use SIGSALUD

select * from ITEM where CODCPT = 'D0220'


SELECT * FROM PRECIO WHERE ITEM = '64021'


 UPDATE PRECIO SET PRECIOB = PRECIOA-PRECIOA*0.3, PRECIOC = PRECIOA-PRECIOA*0.5, PRECIOD = PRECIOA-PRECIOA, PRECIOE = 0, PRECIOF = PRECIOA, PRECIOG = PRECIOA,
    PRECIOH = 0, PRECIOI = PRECIOA, PRECIOJ = PRECIOA, PRECIOK = PRECIOA WHERE item = '64021'