 use sigsalud
 declare @lcbuscanombres varchar(250) = 'mallma curi'
   select EMERGENCIA_ID, convert(varchar(10), fecha, 103) AS FECHA_EMERGENCIA,   HORA, a.ORDEN, ESTADO, A.PATERNO, A.materno, a.NOMBRE, A.NOMBRES, a.consultorio, b.NOMBRE AS NOMBRE_CONSULTORIO, A.FECHA_NACIMIENTO, A.EDAD, A.SEXO, A.ESTADO_CIVIL, A.DIRECCION, HORA_ATEN, 
     convert(varchar(10), FECHA_ATENCION, 103) AS FECHA_ATENCION_EMERGENCIA, PRIORIDAD,  SINTOMAS, RELATO, EXAMEN_FISICO, CIEX4, TIPO_CIEX4, CIEX5, TIPO_CIEX5,CIEX6, TIPO_CIEX6, TRATAMIENTO, fecha_salida, observacion_egreso,  CIEX1, TIPO_CIEX1, CIEX2, TIPO_CIEX2, CIEX3, TIPO_CIEX3, C.HISTORIA, C.DOCUMENTO, D.NOMBRE NOMBRE_SEGURO, E.NOMBRE NOMBRE_RELIGION,
    UPPER(F.NOMBRE) NOMBRE_OCUPACION, g.NOMBRE as NOMBRE_CIEX4, H.NOMBRE AS NOMBRE_CIEX5, I.NOMBRE AS NOMBRE_CIEX6, J.NOMBRE NOMBRE_MEDICO, FECHA_SALIDA, convert(char(5), FECHA_SALIDA, 108) as HORA_SALIDA,
    CONVERT(VARCHAR(10), FECHA_SALIDA, 103) FECHA_SAL, UPPER(K.NOMBRE) AS NOMBRE_DESTINO, a.destino,  A.ESTABLECIMIENTO, l.NOMBRE as NOMBRE_CIEX1, m.NOMBRE as NOMBRE_CIEX2, n.NOMBRE as NOMBRE_CIEX3, a.TIPO_CIEX1, a.TIPO_CIEX2, a.TIPO_CIEX3
     from emergencia a left join CONSULTORIO b on b.CONSULTORIO = a.CONSULTORIO LEFT JOIN PACIENTE C ON C.PACIENTE = A.PACIENTE  LEFT JOIN SEGURO D ON D.SEGURO = A.SEGURO LEFT JOIN RELIGION E
     ON E.RELIGION = A.RELIGION  LEFT JOIN OCUPACION F ON F.OCUPACION = C.OCUPACION left join CIEX G on g.CIEX = a.CIEX4 LEFT JOIN CIEX H ON H.CIEX = A.CIEX5
     LEFT JOIN CIEX I ON I.CIEX = A.CIEX6 LEFT JOIN MEDICO J ON J.MEDICO = A.QUIEN_ATIENDE LEFT JOIN DESTINO K ON K.DESTINO = A.DESTINO 
     left join CIEX l on l.CIEX = a.CIEX1 left join CIEX M ON M.CIEX = A.CIEX2 left join CIEX N on n.CIEX = a.CIEX3  where  A.NOMBRES like '%' + @lcbuscanombres + '%' ORDER BY FECHA DESC   
     
     

UPDATE EMERGENCIA SET FECHA_SALIDA = CONVERT(DATETIME, '06/02/2017', 103) + CAST('08:45' AS DATETIME) WHERE EMERGENCIA_ID = '17005134'        
UPDATE EMERGENCIA SET FECHA_SALIDA = CONVERT(DATETIME, '25/07/2016', 103) + CAST('16:40' AS DATETIME) WHERE EMERGENCIA_ID = '16032754'  

select PRIORIDAD FROM EMERGENCIA GROUP BY PRIORIDAD  

     



