USE SIGSALUD
GO

SELECT * FROM PAGOC WHERE NOMBRE LIKE '%MISAICO MUNARIS %'

SELECT * FROM PAGOC WHERE PAGOID = '15159609'
SELECT * FROM PAGOD  WHERE PAGOID = '15159609'



SELECT * FROM PAGOC WHERE NOMBRE LIKE '%GUTAPAÑA PERDOMO%'

SELECT * FROM PAGOC WHERE PAGOID = '15159609'

SELECT * FROM PAGOD WHERE PAGOID = '15159609'
SELECT * FROM PAGOD  WHERE PAGOID = '15146799'


select * from PAGOD where len(substring(cast((CANTIDAD - floor(CANTIDAD )) as varchar), 3, 5)) = 2 