SELECT ACTIVO, CODCPT, * FROM ITEM WHERE CODCPT = '76805' ORDER BY ITEM DESC

SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE CODCPT = '76805')


SELECT ACTIVO, CODCPT, * FROM ITEM WHERE CODCPT = '76805' ORDER BY ITEM DESC

SELECT * FROM ATENCIOND WHERE DX = '76805'


SELECT PAGOID FROM PAGOC WHERE  FECHA = CONVERT(DATETIME, '2017-05-12', 101)



SELECT * FROM PAGOD WHERE PAGOID IN (SELECT PAGOID FROM PAGOC WHERE  FECHA BETWEEN CONVERT(DATETIME, '2017-03-01', 101) AND CONVERT(DATETIME, '2017-03-31', 101))
  AND ITEM IN ('62439')
  
  SELECT * FROM PAGOD WHERE PAGOID IN (SELECT PAGOID FROM PAGOC WHERE  FECHA BETWEEN CONVERT(DATETIME, '2017-04-01', 101) AND CONVERT(DATETIME, '2017-04-30', 101))
  AND ITEM IN ('606004')
  
  
  
  
  SELECT TOP 380 ID_CITA FROM ATENCIOND WHERE DX = '76805' ORDER BY ID_CITA DESC
  
   SELECT  ID_CITA FROM ATENCIOND WHERE DX = '76805' ORDER BY ID_CITA DESC
  
  
  SELECT * FROM ATENCIONC WHERE ID_CITA IN (SELECT TOP 380 ID_CITA FROM ATENCIOND WHERE DX = '76805' ORDER BY ID_CITA DESC)  ORDER BY FECHA DESC
  
  
  SELECT * FROM PAGOC WHERE NOMBRE LIKE 'ESPINOZA LOP%' ORDER BY FECHA DESC
  
  SELECT * FROM PAGOD WHERE PAGOID = '17057236'
  
  
  SELECT * FROM ITEM WHERE ITEM = '63381'
  