

 declare @lc_nombre_a_buscar varchar(250) = 'OBESO'
 DECLARE @lcfecha1 datetime = convert(datetime, '2018-01-01', 101)
 DECLARE @lcfecha2 datetime = convert(datetime, '2018-03-14', 101)
 SELECT 'X' as INDICADOR, B.NOMBRE AS NOMBRE, CONVERT(VARCHAR(10), B.FECHA, 103) AS FECHA, B.NUMERO AS BOLETA, upper(A.NOMBRE) AS DESCRIPCION, A.CANTIDAD, A.PRECIO, A.IMPORTE,
 CASE WHEN B.TIPO_PAGO = 'C' THEN 'CONTADO' ELSE 'EXONERADO' END AS TIPO_DE_PAGO, B.PACIENTE FROM [SIGSALUD].[dbo].[V_PAGOD] A LEFT JOIN [SIGSALUD].[dbo].[PAGOC] B ON B.PAGOID = A.PAGOID
 WHERE A.PAGOID IN (SELECT PAGOID FROM [SIGSALUD].[dbo].[PAGOC] WHERE NOMBRE LIKE '%' + @lc_nombre_a_buscar + '%' AND FECHA BETWEEN @lcfecha1 AND @lcfecha2 AND ESTADO = '2') ORDER BY B.NUMERO