USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TARIFARIO_REPORTE_PRECIOS]    Script Date: 04/10/2018 12:02:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TARIFARIO_REPORTE_PRECIOS](
	[CPT] [varchar](50) NULL,
	[NOMBRE] [varchar](250) NULL,
	[PRECIO_PAGANTE] [numeric](18, 2) NULL,
	[PRECIO_SIS] [numeric](18, 2) NULL,
	[PRECIO_SOAT] [numeric](18, 2) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


