
USE SIGSALUD
SELECT NOM_LOTE,CODHIS,NUM_PAG,COUNT(NUM_REG) AS NUM_REG,COD_SERVSA,MT 
 FROM HIS WHERE periodo='022017' GROUP BY NOM_LOTE,CODHIS,NUM_PAG,COD_SERVSA,MT ORDER BY NOM_LOTE,NUM_PAG
 


USE HIS
SELECT NOM_LOTE,CODHIS,NUM_PAG,COUNT(NUM_REG) AS NUM_REG,COD_SERVSA,MT 
 FROM HIS WHERE periodo='" & xperi & "' GROUP BY NOM_LOTE,CODHIS,NUM_PAG,COD_SERVSA,MT ORDER BY NOM_LOTE,NUM_PAG
 
 
use sigsalud 
select * from emergencia where nombres like 'ricalde hernand%' order by fecha desc


SELECT * FROM ITEM WHERE CODCPT = '88141' 

SELECT * FROM ITEM WHERE NOMBRE LIKE '%ATENCION%' ORDER BY ITEM DESC

SELECT * FROM PRECIO WHERE ITEM = '53236'

SELECT * FROM ITEM WHERE ITEM IN ('67057', '63466')
SELECT * FROM PRECIO WHERE ITEM IN ('67057', '63466')
SELECT * FROM PRECIO WHERE ITEM IN ('53236', '51123')
SELECT * FROM PRECIO WHERE ITEM IN ('62720', '52894')

SELECT * FROM PRECIO WHERE ITEM IN ('60068')

SELECT * FROM ITEM WHERE NOMBRE LIKE '%PERFIL PRE%' ORDER BY ITEM DESC

SELECT * FROM PRECIO WHERE ITEM = '54246'

SELECT * FROM ITEM WHERE CODCPT IN ('85021')

SELECT * FROM PRECIO WHERE ITEM IN ('62477')

UPDATE PRECIO SET PRECIOC = PRECIOA*0.5






SELECT * FROM PRECIO WHERE ITEM IN ('62964', '606555')
UPDATE PRECIO SET PRECIOA = 0, PRECIOB = 0, PRECIOC = 0, PRECIOD = 0, PRECIOE = 0, PRECIOF = 0, PRECIOG = 0, PRECIOH = 0, PRECIOI = 0, PRECIOJ = 0, PRECIOK = 0
   WHERE ITEM IN ('62964', '606555')
   
   
   
SELECT ACTIVO, CODCPT, * FROM ITEM WHERE ITEM = '60068'   
SELECT * FROM PRECIO WHERE ITEM = '60068'   


SELECT ACTIVO, CODCPT, * FROM ITEM WHERE ITEM = '50694'   
SELECT * FROM PRECIO WHERE ITEM = '50694'   




UPDATE PRECIO SET PRECIOC = PRECIOA*0.5 WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '1')

SELECT PRECIOE, PRECIOF, PRECIOG FROM PRECIO  WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '7')

UPDATE PRECIO SET PRECIOD = (PRECIOA- PRECIOA*1) FROM PRECIO  WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '6' AND ACTIVO = '1')


select 
   
   
   
   
