USE SIGSALUD
SELECT * FROM PAGOC WHERE NOMBRE LIKE 'SANCHEZ RIVERO%' AND FECHA BETWEEN CONVERT(DATETIME, '2017-08-19', 101) AND CONVERT(DATETIME, '2017-08-31', 101)
AND ESTADO = '2' ORDER BY FECHA ASC

SELECT * FROM V_PAGOD WHERE PAGOID IN (SELECT PAGOID FROM PAGOC WHERE NOMBRE LIKE 'SANCHEZ RIVERO%' AND FECHA BETWEEN CONVERT(DATETIME, '2017-08-19', 101) AND CONVERT(DATETIME, '2017-08-31', 101)
AND ESTADO = '2')

SELECT B.NOMBRE AS NOMBRE, CONVERT(VARCHAR(10), B.FECHA, 103) AS FECHA, B.NUMERO AS BOLETA, upper(A.NOMBRE) AS MEDICAMENTO, A.CANTIDAD, A.PRECIO, A.IMPORTE,
CASE WHEN B.TIPO_PAGO = 'C' THEN 'CONTADO' ELSE 'EXONERADO' END AS TIPO_DE_PAGO FROM V_PAGOD A LEFT JOIN PAGOC B ON B.PAGOID = A.PAGOID
WHERE A.PAGOID IN (SELECT PAGOID FROM PAGOC WHERE NOMBRE LIKE 'SANCHEZ RIVERO%' AND FECHA BETWEEN CONVERT(DATETIME, '2017-08-19', 101) AND CONVERT(DATETIME, '2017-08-31', 101)
AND ESTADO = '2') ORDER BY B.PAGOID 