/* REVISAR LO GRABADO */
USE SIGSALUD
SELECT * FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6'
SELECT * FROM precio WHERE item in (SELECT ITEM FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6')

/* SIS - SOAT */
SELECT * FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6'
SELECT * FROM precio WHERE item in (SELECT ITEM FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6')

/*********************************/

SELECT * FROM dbo.TARIFARIO_MARZO_2017

SELECT * FROM dbo.TARIFARIO_ABRIL_2017 WHERE PROCESO LIKE '1%'
SELECT * FROM dbo.TARIFARIO_ABRIL_2017 WHERE PROCESO LIKE '2%'





/*************************************/


/*****************  PAGANTES **************/
UPDATE ITEM SET agregar_cpt = ''

/* ITEMS AGREGADOS */
SELECT * FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'A' /* 39 */
SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'A')


/* ITEMS MODIFICADOS */
SELECT * FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'M'  /* 3579 */
SELECT * FROM PRECIO WHERE ITEM IN (SELECT ITEM FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'M')

/* FALLO AL AGREGAR PRECIO  */
SELECT * FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'F'  /* 0 */

/* NO SE AGREGO NADA   */
SELECT * FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'N'  /* 3579 */

/************** */

SELECT * FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'A' /* 39 */

/* ITEMS MODIFICADOS */
SELECT * FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'M'  /* 3579 */


/* FALLO AL AGREGAR PRECIO  */
SELECT * FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'F'  /* 0 */

/* NO SE AGREGO NADA   */
SELECT * FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6' AND agregar_cpt = 'N'  /* 3579 */



/****************************************/
/* MANEJO DE PRECIOS */


PRECIOA : PRINCIPAL
PRECIOB: 30% DE DESCUENTO
PRECIOC: 50% DESCUENTO
PRECIOD: 100% DESCUENTO
PRECIOE: SIS
PRECIOF: SUSALUD
PRECIOG: ESSALUD
PRECIOH:SOAT
PRECIOI:FFAA
PRECIOJ: DEMANANDA A
PRECIOK: POR CONVENIOS


SELECT * FROM  dbo.ROLACTIVIDAD WHERE CONSULTORIO = '2022' AND PERIODO = '201704'

SELECT * FROM CONSULTORIO WHERE NOMBRE LIKE 'TRAUMATO%'




/********************************************/


SELECT * FROM dbo.TARIFARIO_MARZO_2017 WHERE ACTIVO = '1' ORDER BY ITEM ASC


SELECT * FROM dbo.TARIFARIO_MARZO_2017 WHERE CODCPT = 'AD011'

SELECT * FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '5'  AND ABREVIATURA IS NOT NULL 

SELECT * FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '5'  AND ABREVIATURA IS NOT NULL 

SELECT * FROM PRECIO WHERE ITEM = '50599'



/**************************************************************/

UPDATE PRECIO SET PRECIOB = PRECIOA-PRECIOA*0.3, PRECIOC = PRECIOA-PRECIOA*0.5, PRECIOD = PRECIOA-PRECIOA, PRECIOE = 0, PRECIOF = PRECIOA, PRECIOG = PRECIOA,
  PRECIOH = 0, PRECIOI = PRECIOA, PRECIOJ = PRECIOA, PRECIOK = PRECIOA WHERE item in (SELECT ITEM FROM ITEM WHERE ACTIVO = '1' AND SUBSTRING(ITEM,1,1) = '6')
  

UPDATE PRECIO SET PRECIOA = 0, PRECIOB = 0, PRECIOC = 0, PRECIOD = 0, PRECIOF = 0, PRECIOG = 0, PRECIOI = 0, PRECIOJ = 0, PRECIOK = 0
  WHERE item in (SELECT ITEM FROM ITEM WHERE ACTIVO = '7' AND SUBSTRING(ITEM,1,1) = '6')
  

