DELETE FROM PRECIO WHERE SUBSTRING(ITEM,1,1) = '6'
INSERT INTO [SIGSALUD].[dbo].[PRECIO]([ITEM],[FECHA],[PRECIOA],[PRECIOB],[PRECIOC],[PRECIOD],[PRECIOE],[PRECIOF],[PRECIOG],[PRECIOH],[PRECIOI],[PRECIOJ],[PRECIOK],
    [COSTO],[UTILIDAD],[PRECIOPUB],[DESCUENTO],[PRECIO],[HORA],[PRECIOX],[PROMEDIO],[SYSINSERT],[SYSUPDATE],[INGRESOID])
SELECT ITEM, CONVERT(DATETIME, CONVERT (char(10), getdate(), 102), 102) AS FECHA, PRECIO*1 AS PRECIOA, PRECIO*0.46 AS PRECIOB, PRECIO*0.33 AS PRECIOC, 
0 AS PRECIOD, SIS AS PRECIOE, 0.1 AS PRECIOF, 0.1 AS PRECIOG, PRECIO*0.89 AS PRECIOH, 0.1 AS PRECIOI, PRECIO AS PRECIOJ, 0.1 AS PRECIOK, 0 AS COSTO,
0 AS UTIIDAD, 0 AS PRECIOPUB, 0 AS DESCUENTO, 0 AS PRECIO, '' AS HORA, 0 AS PRECIOX, 0 AS PROMEDIO, '' AS SYSINSERT, '' AS SYSUPDATE, '' AS INGRESOID
FROM [SIGSALUD].[dbo].[TARIFARIO_GENERAL_2017]

  
USE SIGSALUD
SELECT *  FROM [SIGSALUD].[dbo].[TARIFARIO_GENERAL_2017]
SELECT * FROM PRECIO ORDER BY IDRECORD DESC  

SELECT * FROM PRECIO WHERE SUBSTRING(ITEM,1,1) = '5' ORDER BY IDRECORD DESC  

select * from ITEM where NOMBRE like '%medici%' and SUBSTRING(ITEM,1,1) = '5'

SELECT * FROM PRECIO WHERE ITEM = '50356'


SELECT * FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '6' AND NOMBRE LIKE ''

SELECT * FROM ITEM WHERE SUBSTRING(ITEM,1,1) = '5' AND NOMBRE LIKE '%INCISI%'

codcpt :23930

CODCPT : 23030

select * from V_PRECIO

update ITEM set ACTIVO = '1'  WHERE SUBSTRING(ITEM,1,1) = '6'
update ITEM set ACTIVO = '5' WHERE SUBSTRING(ITEM,1,1) = '5'

select * from TARIFARIO_GENERAL_2017 where NOMBRE like '%intramus%'


select ITEM, SERVICIO, CPT, sis into  precio_sis_nuevo from TARIFARIO_GENERAL_2017 

select * from precio_sis
select * from precio_sis_nuevo

select * from ITEM where item in ('63370', '63371')

update ITEM set activo = '7' where item in ('63370', '63371')


select * from TARIFARIO_GENERAL_2017 where NOMBRE like '%orina%'



SELECT * FROM PRECIO SET PRECIOE = (SELECT SIS FROM TARIFARIO_GENERAL_2017 WHERE )

use sigsalud
select * from item   where NOMBRE like '%curacion%' and  SUBSTRING(ITEM,1,1) = '6'

select ACTIVO, * from item   where NOMBRE like '%orina%' and  SUBSTRING(ITEM,1,1) = '6'
select ACTIVO, * from item   where NOMBRE like '%orina%' and  SUBSTRING(ITEM,1,1) = '5'

select * from item_2017

SELECT * FROM PRECIO ORDER BY IDRECORD DESC

SELECT * FROM PRECIO WHERE SUBSTRING(ITEM,1,1) = '6'

DELETE FROM PRECIO WHERE SUBSTRING(ITEM,1,1) = '6'

