INSERT INTO [SIGSALUD].[dbo].[ITEM]([ITEM],[NOMBRE],[ABREVIATURA],[GRUPO_RECAUDACION], [CLASIFICADOR],[GRUPO_LIQUIDACION],[GRUPO_TARIFARIO],[PRESENTACION],[FAMILIA],[CLASE],[GENERICO],[LABORATORIO],
  [FRACCION],[INTERFASE1],[VARIABLE],[MODULO],[ACTIVO],[SYSINSERT],[SYSUPDATE],[SYSDELETE],[INTERFASE2],[PETITORIO],[STOCK],[STOCK_MINIMO],[ITEM_EXCLUSION],[ESTADO_A_CUENTA],[STOCK_CRITICO],[DISPONIBILIDAD],
   [APLICA_DSCTO],[PRESENTA],[CONCENTRA],[NOMBRECORTO],[CODCPT],[SECCION],[SUBSECCION])

SELECT [ITEM], NOMBRE, ABREVIATURA, GRUPO_RECAUDACION, CLASIFICADOR,  GRUPO_LIQUIDACION, '0' GRUPO_TARIFARIO, '0' PRESENTACION, '0' FAMILIA, '0' CLASE, '0' GENERICO, '0' LABORATORIO, 
1 FRACCION, '' AS INTERFASE1, 'N' VARIABLE, 'CAJA' MODULO, ACTIVO, '' SYSINSERT, '' SYSUPDATE, '' SYSDELETE, '' INTERFASE2, 0 PETITORIO, 0 STOCK, 0 STOCK_MINIMO,
 '' ITEM_EXCLUSION, '4' ESTADO_A_CUENTA, 0 STOCK_CRITICO, '' AS DISPONIBILIDAD, '' AS APLICA_DSCTO, '' AS PRESENTA, '' AS CONCENTRA, '' AS NOMBRECORTO, CPT AS CODCPT, '' AS SECCION, '' AS SUBSECCION
 FROM  [SIGSALUD].[dbo].[ITEM_SIS]
  
  SELECT * FROM  [SIGSALUD].[dbo].[ITEM]
GO

           
