use SIGSALUD
select * from PAGOC where NUMERO = '001-1749467'
update PAGOC set USUARIO = 'EARELLANO' where NUMERO = '001-1749467'

 select NOMBRE, USUARIO, CONTRASENA  from [SIGSALUD].[dbo].[USUARIO]
 where MODULO = 'CAJA' AND ACTIVO = '1'  ORDER BY NOMBRE ASC