USE TRAMITE
INSERT INTO [TRAMITE].[dbo].[USUARIO]([MODULO], [USUARIO],[CONTRASENA], DIRECCION, TELEFONO, NOMBRE  ,[CARGO],[FECHA_EXPIRACION],
   [ACTIVO],[ACTOR],[JEFATURA], CONSULTORIO)
     VALUES ('TRAMITE', 'GHUAMANI', '1234567', 'GERSON HUAMANI', '', '', 'TECNICO', CONVERT(DATETIME, '2025-12-31', 101), '1', '0403', 'N', '')
     
UPDATE [TRAMITE].[dbo].[USUARIOD] SET USUARIO = 'GHUAMANI' WHERE USUARIO = 'MVITOR'

