/* COMPRUEBA LA GRABACION DE DATOS */
USE SIGSALUD
DECLARE @lidemergencia VARCHAR(13) = '16031369'
SELECT EMERGENCIA_ID, ESTADO, MEDICO, MEDICO1, QUIEN_ATIENDE, fecha_salida, HORA, NOMBRES, GPOBS, FUROBS, FPPOBS, EGUMOBS, EGECOOBS, USUARIO_ANT_OBSTETRICIA FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia
SELECT TEMPERATURA,PRESION,PRESIOND,PULSO,FR,PESO,FC,SAT_OX,USUARIO_FN_VITALES, ESTADO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE  FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia
SELECT ALTURA_UTERINA, PRESENTACION, LCF, DILATACION, INCORPORACION, ALTURA_PRESENTACION, MEMBRANAS, USUARIO_EXAMEN_OBSTETRICO, PRESENTACION2, LCF2, TV, MEDICO_CODIGO_GINE  FROM EMERGENCIA WHERE EMERGENCIA_ID = @lidemergencia 


/* select * from v_emergencia where emergencia_id = @lidemergencia */