

use SIGSALUD
select  *  from EMERGENCIA where CONSULTORIO in ('4050', '4060')

select  emergencia_id, nombres, fecha,  furobs, fppobs, EGUMOBS, DATEDIFF(week,  furobs, fecha) as semanas  from EMERGENCIA 
  where CONSULTORIO in ('4050', '4060') order by fecha desc
  
select  emergencia_id, nombres, fecha,  furobs, fppobs, EGUMOBS, DATEDIFF(week,  furobs, fecha) as semanas  from EMERGENCIA 
  where CONSULTORIO in ('4050', '4060') and furobs <> '' and FPPOBS <> '' and DATEDIFF(week,  furobs, fecha) between 0 and 36 order by fecha desc
  
  
update EMERGENCIA set EGUMOBS =  DATEDIFF(week,  furobs, fecha)   where CONSULTORIO in ('4050', '4060') and furobs <> '' and FPPOBS <> '' and DATEDIFF(week,  furobs, fecha) between 0 and 36
update EMERGENCIA set USUARIO_FN_VITALES = 'MCS', USUARIO_ANT_OBSTETRICIA = 'MCS', USUARIO_EXAMEN_OBSTETRICO = 'MCS' WHERE EMERGENCIA_ID = '16029568'
update EMERGENCIA_DET_WEB set PROFESIONAL = 'MCS' WHERE EMERGENCIA_ID = '16029568'
UPDATE EMERGENCIA SET PRESENTACION = 'CEFALICA' WHERE  CONSULTORIO in ('4050', '4060') AND PRESENTACION = 'C' 
UPDATE EMERGENCIA SET PRESENTACION = 'PODALICA' WHERE  CONSULTORIO in ('4050', '4060') AND PRESENTACION = 'P' 
UPDATE EMERGENCIA SET PRESENTACION = 'TRANSVERSA' WHERE  CONSULTORIO in ('4050', '4060') AND PRESENTACION = 'T' 
UPDATE EMERGENCIA SET PRESENTACION = 'OBLICUA' WHERE  CONSULTORIO in ('4050', '4060') AND PRESENTACION = 'O' 
UPDATE EMERGENCIA SET PRESENTACION2 = 'CEFALICA' WHERE  CONSULTORIO in ('4050', '4060') AND PRESENTACION2 = 'C' 
UPDATE EMERGENCIA SET MEMBRANAS = 'ROTAS' WHERE  CONSULTORIO in ('4050', '4060') AND MEMBRANAS = 'R' 
UPDATE EMERGENCIA SET MEMBRANAS = 'INTEGRAS' WHERE  CONSULTORIO in ('4050', '4060') AND MEMBRANAS = 'I' 
UPDATE EMERGENCIA SET TV  = 'NO APLICA' WHERE  CONSULTORIO in ('4050', '4060') AND TV = 'N' 
UPDATE EMERGENCIA SET TV  = 'SIN MODIFICACION' WHERE  CONSULTORIO in ('4050', '4060') AND TV = 'S' 
UPDATE EMERGENCIA SET TV  = 'CERVIX ABIERTO' WHERE  CONSULTORIO in ('4050', '4060') AND TV = 'C' 



use SIGSALUD
declare @lidemergencia varchar(13) = '16029568'
select  fecha, CONSULTORIO, MEDICO, MEDICO1, MEDICO2, QUIEN_ATIENDE, nombres, usuario_fn_vitales, USUARIO_ANT_OBSTETRICIA, USUARIO_EXAMEN_OBSTETRICO, MEDICO_CODIGO_GINE 
 from EMERGENCIA where EMERGENCIA_ID = @lidemergencia and CONSULTORIO in ('4050', '4060')
select * from EMERGENCIA_DET_WEB where EMERGENCIA_ID = @lidemergencia ORDER BY FECHA_HORA_REG ASC
SELECT PRESENTACION, PRESENTACION2, MEMBRANAS, TV FROM EMERGENCIA WHERE  CONSULTORIO in ('4050', '4060')  ORDER BY FECHA DESC 
