USE SIGSALUD
/* ARAGONEZ */

SELECT * FROM EMERGENCIA WHERE EMERGENCIA_ID = '16047319'
SELECT * FROM EMERGENCIA_DET_WEB WHERE EMERGENCIA_ID = '16047319'

NO MUESTRA EN * REPORTE LA EDAD GESTACIONAL POR ECOGRAFIA


/* como limpiear una historia en emergencia medicina */

/* PARA VER EL CONTENIDO DE EMERGENCIA */
EXEC SP_GET_EMERGENCIA_15 '16047319'




SELECT MEDICO, NOMBRE, COLEGIO, DNI, TIENE_FIRMA, CASE WHEN TIENE_FIRMA = '1' THEN 'TIENE FIRMA' ELSE '** NO TIENE FIRMA **' END AS FIRMA   FROM MEDICO WHERE NOMBRE LIKE '%' + 'MORALES' + '%'