USE SIGSALUD
ALTER TABLE EMERGENCIA ALTER COLUMN PRESENTACION VARCHAR(30)
ALTER TABLE EMERGENCIA ALTER COLUMN PRESENTACION2 VARCHAR(30)
ALTER TABLE EMERGENCIA ALTER COLUMN MEMBRANAS VARCHAR(30)
ALTER TABLE EMERGENCIA ALTER COLUMN TV VARCHAR(30)



