

select * from ARCHIVO_MOV where ID_CITA = '160052087'

select * from ARCHIVO_MOV where FECHA = CONVERT(DATETIME, '2016-04-11', 101) AND MEDICO = 'QMZ' AND TURNO = 'M'  ORDER BY NUMERO  ASC

SELECT * FROM V_ARCHIVOMOV WHERE FECHA = CONVERT(DATETIME, '2016-04-11', 101) AND MEDICO = 'QMZ' AND TURNO = 'M'  ORDER BY NUMERO ASC

ZARATE
select * from PAGOC where NOMBRE LIKE 'MENENDEZ CASTILLO%' ORDER BY FECHA DESC

SELECT * FROM PAGOD WHERE PAGOID = '16054496'

SELECT * FROM ITEM WHERE ITEM = '50358     '

/* UPDATE PAGOC SET PACIENTE = '2015254267' WHERE PAGOID = '16054496' */

/* UPDATE PAGOC SET MEDICO  = 'QMZ' WHERE PAGOID = '16054496' */

SELECT * FROM MEDICO WHERE NOMBRE LIKE 'QUISPE%'  -  QMZ