USE [SIGSALUD]
GO

/****** Object:  View [dbo].[V_ATENCIONES]    Script Date: 10/07/2015 11:40:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[V_ATENCIONES]
AS
SELECT     TOP (100) PERCENT dbo.ARCHIVO_MOV.ID_CITA, dbo.ARCHIVO_MOV.PACIENTE, dbo.ARCHIVO_MOV.HISTORIA, dbo.ARCHIVO_MOV.NOMBRES, 
                      dbo.PACIENTE.TIPO_DOCUMENTO, dbo.PACIENTE.DOCUMENTO, dbo.PACIENTE.DISTRITO, dbo.UBIGEO.DISTRITO AS NOMDISTRITO,
                      -- dbo.PACIENTE.EDAD, 
                      dbo.FN_CALCULAR_EDAD(CONVERT(VARCHAR(10), PACIENTE.FECHA_NACIMIENTO, 103)) EDAD,
                      dbo.PACIENTE.SEXO, dbo.ARCHIVO_MOV.SEGURO, dbo.ARCHIVO_MOV.MEDICO, dbo.ARCHIVO_MOV.CONSULTORIO, dbo.ARCHIVO_MOV.FECHA, 
                      dbo.ARCHIVO_MOV.TURNO, dbo.PACIENTE.FECHA_NACIMIENTO, dbo.ARCHIVO_MOV.EST_PAC, dbo.SEGURO.NOMBRE, dbo.ARCHIVO_MOV.NUMERO, 
                      dbo.CITA.HORA, dbo.CITA.FECHA_PAGO, dbo.ARCHIVO_MOV.HORA_SAL, dbo.CITA.TIPO_CITA, dbo.CONSULTORIO.NOMBRE AS CE, 
                      dbo.TURNO_CONSULTA.NOMBRE AS TURNO_NOMBRE
FROM         dbo.ARCHIVO_MOV INNER JOIN
                      dbo.PACIENTE ON dbo.ARCHIVO_MOV.PACIENTE = dbo.PACIENTE.PACIENTE INNER JOIN
                      dbo.UBIGEO ON dbo.PACIENTE.DISTRITO = dbo.UBIGEO.UBIGEO INNER JOIN
                      dbo.SEGURO ON dbo.ARCHIVO_MOV.SEGURO = dbo.SEGURO.SEGURO INNER JOIN
                      dbo.CITA ON dbo.ARCHIVO_MOV.ID_CITA = dbo.CITA.CITA_ID INNER JOIN
                      dbo.CONSULTORIO ON dbo.ARCHIVO_MOV.CONSULTORIO = dbo.CONSULTORIO.CONSULTORIO INNER JOIN
                      dbo.TURNO_CONSULTA ON dbo.ARCHIVO_MOV.TURNO = dbo.TURNO_CONSULTA.TURNO_CONSULTA

GO
