 USE SIGSALUD
  TRUNCATE table [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]
  INSERT INTO [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]
           ([DEPARTAMENTO]
           ,[PERIODO]
           ,[UBIGEO]
           ,[ANIO]
           ,[MES]
           ,[DIA]
           ,[FICHAFAM]
           ,[EDAD]
           ,[TIPOEDAD]
           ,[SEXO]
           ,[FECHA]
           ,[COD_SERVSA]
           ,[HSERVICIO]
           ,[PROF_CITA]
           ,[CODHIS]
           ,[DESCRIPCION_CODIGO]
           ,[CODIGO])
  SELECT 'MEDICINA' AS  DEPARTAMENTO, PERIODO, UBIGEO, ANIO, MES, DIA, FICHAFAM, EDAD, TIPOEDAD, SEXO, FECHA, COD_SERVSA, HSERVICIO, PROF_CITA, CODHIS, DESCRIPCION_CODIGO, CODIGO
  	 FROM [SIGSALUD].[dbo].[TMPHISTEMP] WHERE 
  HSERVICIO IN ('MEDICINA GENERAL', 'MEDICINA INTERNA', 'NEUMOLOGIA', 'CARDIOLOGIA', 'NEUROLOGIA', 'GASTROENTEROLOGIA', 'DERMATOLOGIA',
   'EPIDEMIOLOGIA', 'PSIQUIATRIA', 'ENDOCRINOLOGIA', 'MEDICINA REHABILITACION') 
 UNION ALL    
  SELECT 'CIRUGIA' AS  DEPARTAMENTO, PERIODO, UBIGEO, ANIO, MES, DIA, FICHAFAM, EDAD, TIPOEDAD, SEXO, FECHA, COD_SERVSA, HSERVICIO, PROF_CITA, CODHIS, DESCRIPCION_CODIGO, CODIGO FROM [SIGSALUD].[dbo].[TMPHISTEMP] WHERE 
  HSERVICIO IN ('CIRUGIA GENERAL', 'TRAUMATOLOGIA', 'OTORRINOLARINGOLOGIA', 'OFTALMOLOGIA', 'UROLOGIA', 'CIRUGIA PLASTICA', 'CIRUGIA PEDIATRICA', 'ANASTESIOLOGIA')
UNION ALL
 SELECT 'PEDIATRIA' AS DEPARTAMENTO , PERIODO, UBIGEO, ANIO, MES, DIA, FICHAFAM, EDAD, TIPOEDAD, SEXO, FECHA, COD_SERVSA, HSERVICIO, PROF_CITA, CODHIS, DESCRIPCION_CODIGO, CODIGO FROM [SIGSALUD].[dbo].[TMPHISTEMP] WHERE 
  HSERVICIO IN ('PEDIATRIA')
UNION ALL 
 SELECT 'GINECOLOGIA Y OBSTETRICIA' AS DEPARTAMENTO, PERIODO, UBIGEO, ANIO, MES, DIA, FICHAFAM, EDAD, TIPOEDAD, SEXO, FECHA, COD_SERVSA, HSERVICIO, PROF_CITA, CODHIS, DESCRIPCION_CODIGO, CODIGO FROM [SIGSALUD].[dbo].[TMPHISTEMP] WHERE   HSERVICIO IN ('GINECO-OBSTETRICIA')
  SELECT * FROM [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]


  SELECT DEPARTAMENTO FROM [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS] GROUP BY DEPARTAMENTO
  
  SELECT * FROM [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]
  
    select *  from [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]  where departamento = 'CIRUGIA'  AND  substring(codigo,1,1) NOT in ('0','1','2','3', '4', '5', '6', '7', '8', '9')
    AND substring(codigo,1,1) NOT in ('U','W','X','Y', 'Z')   order by CODIGO asc



  select CODIGO, DESCRIPCION_CODIGO, COUNT(CODIGO) AS CASOS  from [SIGSALUD].[dbo].[TMP_DEPARTAMENTOS]  where departamento = 'CIRUGIA' AND  substring(codigo,1,1) NOT in ('0','1','2','3', '4', '5', '6', '7', '8', '9')
    AND substring(codigo,1,1) NOT in ('U','W','X','Y', 'Z') GROUP BY CODIGO, DESCRIPCION_CODIGO order by CODIGO asc

