USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_DEPARTAMENTOS]    Script Date: 02/10/2016 17:23:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_DEPARTAMENTOS](
	[IDDEPAR] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTAMENTO] [varchar](150) NULL,
	[PERIODO] [varchar](12) NULL,
	[UBIGEO] [varchar](12) NULL,
	[ANIO] [varchar](12) NULL,
	[MES] [varchar](12) NULL,
	[DIA] [varchar](5) NULL,
	[FICHAFAM] [varchar](50) NULL,
	[EDAD] [varchar](50) NULL,
	[TIPOEDAD] [varchar](50) NULL,
	[SEXO] [varchar](2) NULL,
	[FECHA] [varchar](12) NULL,
	[COD_SERVSA] [varchar](50) NULL,
	[HSERVICIO] [varchar](50) NULL,
	[PROF_CITA] [varchar](50) NULL,
	[CODHIS] [varchar](50) NULL,
	[DESCRIPCION_CODIGO] [varchar](150) NULL,
	[CODIGO] [varchar](50) NULL,
 CONSTRAINT [PK_TMP_DEPARTAMENTOS] PRIMARY KEY CLUSTERED 
(
	[IDDEPAR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


