USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TMP_MEDICOS]    Script Date: 02/10/2016 15:52:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMP_MEDICOS](
	[IDMEDICO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](200) NULL,
	[COLEGIO] [varchar](100) NULL,
	[ESPECIALIDAD] [varchar](100) NULL,
	[CONSULTORIO] [varchar](150) NULL,
	[DNI] [varchar](10) NULL,
	[SITUACION] [varchar](4) NULL,
	[FECHA_INGRESO] [datetime] NULL,
	[FECHA_BAJA] [datetime] NULL,
	[FECHA_REGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TMP_MEDICOS] PRIMARY KEY CLUSTERED 
(
	[IDMEDICO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


