use SIGSALUD

select * from CIEXHIS where CODIGO like 'F91%'

select * from CIEXHIS where NOMBRE like '%FRONTERIZO%'


SELECT * FROM ATENCIOND 
WHERE ID_CITA IN (SELECT ID_CITA FROM ATENCIONC  WHERE FECHA = CONVERT(DATETIME, '2016-08-08', 101) AND MEDICO = 'GRL')

hc:
045976