/* REPORTE DE ATENCIONES ODONTOLOGIA */

DECLARE @lmes INT = 7
declare @lanio int = 2016

SELECT FECHA, NOMBRES, TIPOEDAD, EDAD FROM ATENCIONC WHERE ESTADO <> '5' AND CONSULTORIO IN ('5050', '5010', '5011') 
 AND MONTH(FECHA) = @lmes AND YEAR(FECHA) = @lanio AND TIPOEDAD = 'A' AND EDAD BETWEEN 1 AND 12 
union all
 SELECT FECHA, NOMBRES, TIPOEDAD,  EDAD FROM ATENCIONC WHERE ESTADO <> '5' AND CONSULTORIO IN ('5050', '5010', '5011') 
 AND MONTH(FECHA) = @lmes AND YEAR(FECHA) = @lanio AND TIPOEDAD = 'M' AND EDAD BETWEEN 1 AND 12  
 