SELECT * FROM CONSULTORIO 
SELECT * FROM MEDICO WHERE NOMBRE LIKE '%MEJIA%'

SELECT a.ID_CITA, b.ID_CITA,  a.FECHA, a.HISTORIA, a.NOMBRES, a.DNI, a.EDAD,a.SEXO, b.TIPODX, b.DX, UPPER(b.DX_DES) DESCRIPCION FROM ATENCIONC A
 left join ATENCIOND b on b.ID_CITA = a.ID_CITA 
 where a.MEDICO = 'MPS' AND MONTH(a.FECHA) = 7 AND YEAR(a.FECHA) = 2016  AND a.FINANCIA = '2' order by a.NOMBRES asc

SELECT * FROM ATENCIONC WHERE MEDICO = 'MPS' AND MONTH(FECHA) = 5 AND YEAR(FECHA) = 2016  AND FINANCIA = '2' order by FECHA asc


SELECT * FROM ATENCIONC WHERE MEDICO = 'MPS' AND MONTH(FECHA) = 6 AND YEAR(FECHA) = 2016  AND FINANCIA = '2'