update ATENCIONC set NOMBRES = 'ORDOÑEZ MAXIMILIANO GABRIELA ESTEFANY' WHERE  id_cita = '160171103' 
update HIS set PACIENTE = 'ORDOÑEZ MAXIMILIANO GABRIELA ESTEFANY' where PERIODO = '122016'  and DIA = '30' and PROF_CITA = 'MARTINEZ HEREDIA JAIME TEODOCIO' and ID_PACIENTE = '2014236887'
