USE [SIGSALUD]
GO

/****** Object:  Table [dbo].[TFUAC16]    Script Date: 07/20/2016 17:25:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TFUAC16](
	[IDFUAC] [int] IDENTITY(1,1) NOT NULL,
	[FUAINICIAL2016] [varchar](13) NULL,
	[FUAIMPINICIAL] [varchar](13) NULL,
	[CANTIDAD] [int] NULL,
	[FUAIMPFINAL] [varchar](13) NULL,
	[FECHAREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TFUAC16] PRIMARY KEY CLUSTERED 
(
	[IDFUAC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


