USE SIGSALUD 
declare @lcperiodo varchar(6) = '012016'
declare @lcperiodo2 varchar(6) = '012016'
declare @lcodigo as varchar(10) = 'Z0274'

SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF1 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD1) AS DESCRIPCION, CODIGO1 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2  AND CODIGO1 = @lcodigo
UNION ALL 
SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF2 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD2) AS DESCRIPCION, CODIGO2 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2 AND CODIGO2 = @lcodigo
UNION ALL
SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF3 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD3) AS DESCRIPCION, CODIGO3 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2   AND CODIGO3 = @lcodigo
UNION ALL 
SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF4 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD4) AS DESCRIPCION, CODIGO4 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2   AND CODIGO4 = @lcodigo
UNION ALL
SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF5 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD5) AS DESCRIPCION, CODIGO5 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2   AND CODIGO5 = @lcodigo
UNION ALL 
SELECT EDAD, TIPOEDAD, SEXO, PACIENTE, FICHAFAM, DNI, HSERVICIO, LABCONF6 AS LAB, UPPER(DES_COD1) AS MOTIVO, UPPER(DES_COD6) AS DESCRIPCION, CODIGO6 AS CODIGO FROM HIS WHERE PERIODO BETWEEN @lcperiodo AND  @lcperiodo2   AND CODIGO6 = @lcodigo


